[package]
name = "tilezz"
version = "0.0.1"
edition = "2021"

[dependencies]
arrayref = "0.3.8"
num-complex = "0.4.6"
num-integer = "0.1.46"
num-rational = "0.4.2"
num-traits = "0.2.19"
plotters = "0.3.7"
