[package]
name = "tilezz"
version = "0.0.2"
authors = ["Anton Pirogov <apirogov@users.noreply.github.com>"]
description = "Utilities to work with perfect-precision polygonal tiles built on top of complex integer rings."
license = "MIT"

readme = "README.md"
repository = "https://github.com/apirogov/tilezz"
keywords = ["2d", "geometry", "tilings", "math", "algebra"]
categories = ["mathematics", "graphics"]

edition = "2021"

[dependencies]
arrayref = "0.3.8"
num-complex = "0.4.6"
num-integer = "0.1.46"
num-rational = "0.4.2"
num-traits = "0.2.19"
plotters = { version = "^0.3.7", features = ["evcxr", "all_series"], optional = true }

[features]
default = ["plotters"]
plotters = ["dep:plotters"]
