[package]
name = "tilezz"
version = "0.0.3"
authors = ["Anton Pirogov <apirogov@users.noreply.github.com>"]
description = "Utilities to work with perfect-precision polygonal tiles built on top of complex integer rings."
license = "MIT"

readme = "README.md"
repository = "https://github.com/apirogov/tilezz"
keywords = ["2d", "geometry", "tilings", "math", "algebra"]
categories = ["mathematics", "graphics"]

edition = "2021"

exclude = ["examples/*"]

[dependencies]
arrayref = "0.3.8"
num-complex = "0.4.6"
num-integer = "0.1.46"
num-rational = "0.4.2"
num-traits = "0.2.19"
paste = "1.0.15"

plotters = { version = "^0.3.7", features = ["evcxr", "evcxr_bitmap", "all_series"], optional = true }
clap = { version = "4.5.27", features = ["derive"], optional = true }
num_cpus = { version = "1.16.0", optional = true }
crossbeam = { version = "0.8.4", optional = true }
itertools = "0.14.0"

[features]
default = ["plotters", "examples"]
plotters = ["dep:plotters"]
examples = ["plotters", "dep:clap", "dep:crossbeam", "dep:num_cpus"]
