#!/usr/bin/env python3
"""
EXACT, dependency-free clean-room enumerator for self-avoiding closed polygons
on the ZZ10 (decagonal) lattice -- the object counted by OEIS A316200. No
floating point anywhere; every geometric predicate is an exact integer sign
decision in Z[sqrt5]. Written independently of the `tilezz` Rust code to serve
as a second, trustless witness for the A316200 a(11) correction.

Usage:
    python3 zz10_independent.py [LO] [HI]      # default LO=4 HI=10
    python3 zz10_independent.py 4 11           # includes the disputed a(11)

Expected output (the validation gate; LO..10 are the values OEIS and tilezz
agree on, so a correct enumerator MUST reproduce them):
    p= 4  free_count=2
    p= 5  free_count=2
    p= 6  free_count=10
    p= 7  free_count=15
    p= 8  free_count=124
    p= 9  free_count=352
    p=10  free_count=2378
    p=11  free_count=9883      <-- tilezz=9883, OEIS A316200 a(11)=19405

Geometry exact-arithmetic model
--------------------------------
zeta = exp(i*pi/5), a primitive 10th root of unity. The unit step in facing
direction d is zeta^d = (cos(d pi/5), sin(d pi/5)). A vertex is a sum of such
unit vectors. We represent every planar point EXACTLY as

    X-coordinate  = Xx / 4            with Xx in Z[sqrt5]  (i.e. a+b sqrt5)
    Y-coordinate  = s1 * (Yy / 4)     with Yy in Z[sqrt5], s1 = sin(pi/5) > 0

Why this is closed and exact:
  cos(k pi/5) are exactly { 0, +-1, +-(1+sqrt5)/4, +-(sqrt5-1)/4 }  -> *4 -> Z[sqrt5]
  sin(k pi/5) = s1 * u_k, u_k in {0, +-1, +-phi}, phi=(1+sqrt5)/2     -> *4 -> Z[sqrt5]
So scaling by 4, every coordinate is an element of Z[sqrt5] stored as an
integer pair (a, b) meaning a + b*sqrt5. All adds/subs/mults stay in Z[sqrt5].

Predicates reduce to SIGN of expressions:
  - cross product (orientation): cross = (s1/16)*Z[sqrt5]; s1>0 so sign = sign
    of the Z[sqrt5] expression. EXACT.
  - dot product: Xx1*Xx2/16 + s1^2 * Yy1*Yy2/16, s1^2=(5-sqrt5)/8 -> Z[sqrt5]/8.
  - equality: both Z[sqrt5] coords zero. EXACT.

sign(a + b*sqrt5) with a,b integers is decided exactly (compare a^2 vs 5 b^2
when signs differ). No approximation, fully rigorous; no separation argument
needed because there is literally no rounding.

Symmetry / dedup
----------------
A polygon is a CYCLIC sequence of turns. The free (rotation+reflection)
congruence class acts on the turn-sequence via the dihedral group generated by:
  - cyclic rotation        (free choice of starting vertex),
  - sign negation t->-t    (planar reflection),
  - order reversal         (reverse traversal direction).
Canonical form = lexicographic minimum over all rotations of the four variants
{t, reverse(t), -t, reverse(-t)}.

Validated against the exact point-set congruence test (zz10_pointset_crosscheck.py)
for p<=8; at p=9 they diverge (turn=352 vs point-set=351) because two genuinely
distinct simple polygons can occupy the SAME vertex set with different edge
connectivity -- the turn-sequence count is the correct "number of polygons",
and it reproduces the published p<=10 reference values 2,2,10,15,124,352,2378.
"""

import sys, time

# ---- Z[sqrt5] as integer pair (a,b) meaning a + b*sqrt5 ------------------
def s_sign(a, b):
    if a == 0 and b == 0:
        return 0
    if b == 0:
        return 1 if a > 0 else -1
    if a == 0:
        return 1 if b > 0 else -1
    sa = 1 if a > 0 else -1
    sb = 1 if b > 0 else -1
    if sa == sb:
        return sa
    # opposite signs: compare a^2 vs 5 b^2
    l = a * a
    r = 5 * b * b
    if l == r:
        return 0
    if sa == 1:   # a>0, b<0  -> positive iff a^2 > 5 b^2
        return 1 if l > r else -1
    else:         # a<0, b>0  -> positive iff 5 b^2 > a^2
        return 1 if r > l else -1

# step vectors scaled by 4: Xx (a,b), Yy (a,b)  [Y = s1*Yy/4, X = Xx/4]
COSx = [(4,0),(1,1),(-1,1),(1,-1),(-1,-1),(-4,0),(-1,-1),(1,-1),(-1,1),(1,1)]
SINu = [(0,0),(4,0),(2,2),(2,2),(4,0),(0,0),(-4,0),(-2,-2),(-2,-2),(-4,0)]
STEP = [(COSx[d][0], COSx[d][1], SINu[d][0], SINu[d][1]) for d in range(10)]

# s1^2 = (5 - sqrt5)/8 ; represent 8*s1^2 = (5,-1) in Z[sqrt5]
S1SQ8_a, S1SQ8_b = 5, -1   # 8 * s1^2 = 5 - sqrt5

def cross_sign(ox,oa, oya,oyb, ax,aa, aya,ayb, bx,ba, bya,byb):
    """sign of (a-o) x (b-o). cross = (s1/16)*(dx1*dy2 - dy1*dx2)."""
    dx1a, dx1b = ax-ox, aa-oa
    dy1a, dy1b = aya-oya, ayb-oyb
    dx2a, dx2b = bx-ox, ba-oa
    dy2a, dy2b = bya-oya, byb-oyb
    t1a = dx1a*dy2a + 5*dx1b*dy2b
    t1b = dx1a*dy2b + dx1b*dy2a
    t2a = dy1a*dx2a + 5*dy1b*dx2b
    t2b = dy1a*dx2b + dy1b*dx2a
    return s_sign(t1a - t2a, t1b - t2b)

def dot_val(ox,oa,oya,oyb, ax,aa,aya,ayb, bx,ba,bya,byb):
    """returns (a,b) proportional (positive scale) to (a-o).(b-o).
    128*dot = 8 dx1 dx2 + (5 - sqrt5) dy1 dy2, kept in Z[sqrt5]."""
    dx1a, dx1b = ax-ox, aa-oa
    dy1a, dy1b = aya-oya, ayb-oyb
    dx2a, dx2b = bx-ox, ba-oa
    dy2a, dy2b = bya-oya, byb-oyb
    pa = 8*(dx1a*dx2a + 5*dx1b*dx2b)
    pb = 8*(dx1a*dx2b + dx1b*dx2a)
    qa = dy1a*dy2a + 5*dy1b*dy2b
    qb = dy1a*dy2b + dy1b*dy2a
    ra = S1SQ8_a*qa + 5*S1SQ8_b*qb
    rb = S1SQ8_a*qb + S1SQ8_b*qa
    return (pa+ra, pb+rb)

ORIG = (0,0,0,0)

def add(p, d):
    return (p[0]+d[0], p[1]+d[1], p[2]+d[2], p[3]+d[3])

def peq(p, q):
    return p[0]==q[0] and p[1]==q[1] and p[2]==q[2] and p[3]==q[3]

def cs(o,a,b):
    return cross_sign(o[0],o[1],o[2],o[3], a[0],a[1],a[2],a[3], b[0],b[1],b[2],b[3])

def dv(o,a,b):
    return dot_val(o[0],o[1],o[2],o[3], a[0],a[1],a[2],a[3], b[0],b[1],b[2],b[3])

def point_on_seg_closed(p, s, t):
    if cs(s, t, p) != 0:
        return False
    da, db = dv(s, p, t)       # (p-s).(t-s)
    if s_sign(da, db) < 0:
        return False
    la, lb = dv(s, t, t)       # |t-s|^2
    if s_sign(da-la, db-lb) > 0:
        return False
    return True

def segments_intersect(a, b, c, d):
    o1 = cs(a,b,c); o2 = cs(a,b,d)
    o3 = cs(c,d,a); o4 = cs(c,d,b)
    if o1 != o2 and o3 != o4:
        return True
    if point_on_seg_closed(c,a,b): return True
    if point_on_seg_closed(d,a,b): return True
    if point_on_seg_closed(a,c,d): return True
    if point_on_seg_closed(b,c,d): return True
    return False

def canonical(turns):
    """Dihedral canonical form: lexmin over rotations of {t,-t,rev,rev(-t)}."""
    p = len(turns)
    rev = turns[::-1]
    neg = [-t for t in turns]
    negrev = [-t for t in rev]
    best = None
    for s in (turns, rev, neg, negrev):
        for r in range(p):
            rot = tuple(s[r:] + s[:r])
            if best is None or rot < best:
                best = rot
    return best

def enumerate_perimeter(p):
    results = set()
    STEPv = STEP
    v1 = STEPv[0]
    verts = [ORIG, v1]
    edges = [(ORIG, v1)]
    facings = [0]

    def dfs(depth):
        if depth == p:
            if peq(verts[-1], ORIG):
                tc = (facings[0] - facings[-1]) % 10
                if tc > 5: tc -= 10
                if -4 <= tc <= 4:
                    turns = [tc]
                    for i in range(1, p):
                        tt = (facings[i]-facings[i-1]) % 10
                        if tt > 5: tt -= 10
                        turns.append(tt)
                    results.add(canonical(turns))
            return
        pf = facings[-1]
        cur = verts[-1]
        rem_after = p - depth - 1
        rem2 = rem_after * rem_after
        nverts = len(verts)
        nedges = len(edges)
        closing = (depth + 1 == p)
        for t in range(-4, 5):
            nf = (pf + t) % 10
            nv = add(cur, STEPv[nf])
            dup = False
            for j in range(nverts):
                if peq(nv, verts[j]):
                    if j == 0 and closing:
                        pass
                    else:
                        dup = True
                    break
            if dup:
                continue
            bad = False
            for k in range(nedges):
                if k == depth - 1:
                    continue
                if closing and k == 0:
                    continue
                ek = edges[k]
                if segments_intersect(cur, nv, ek[0], ek[1]):
                    bad = True
                    break
            if bad:
                continue
            if not closing:
                da, db = dv(ORIG, nv, nv)  # 128*|nv|^2
                if s_sign(da - 128*rem2, db) > 0:
                    continue
            verts.append(nv); edges.append((cur, nv)); facings.append(nf)
            dfs(depth + 1)
            verts.pop(); edges.pop(); facings.pop()

    dfs(1)
    return len(results)

if __name__ == "__main__":
    targets = {4:2,5:2,6:10,7:15,8:124,9:352,10:2378}
    lo = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    hi = int(sys.argv[2]) if len(sys.argv) > 2 else 10
    for p in range(lo, hi+1):
        t0 = time.time()
        c = enumerate_perimeter(p)
        dt = time.time()-t0
        exp = targets.get(p)
        tag = ""
        if exp is not None:
            tag = "  OK" if c==exp else "  *** MISMATCH expected %d" % exp
        print("p=%2d  free_count=%d  (%.1fs)%s" % (p,c,dt,tag))
        sys.stdout.flush()
