#!/usr/bin/env python3
"""Pre-release executability check for the evcxr (Rust-kernel) notebooks.

Picture the kernel's view: evcxr runs a notebook as one growing program.
Each code cell is appended to a shared scope and re-compiled, with cell
`:dep` lines pulling crates in and a cell's trailing expression rendered
inline. This script reconstructs that program statically -- it splices
every code cell of a notebook into a single `fn main()`, points the
`:dep tilezz = { path = "..", ... }` at the WORKING TREE (not whatever
the cell pins), and then compiles and runs it. Compilation catches API
drift (a renamed module, a changed signature); running catches the
panics a type-check cannot (a bad `unwrap`, an out-of-range index).

It is intentionally a coarse net, not a faithful evcxr emulator: it does
not force the final SVG/PNG serialization of a trailing `.display(&vp)`
(scene + geometry construction is exercised, the byte-level render is
not), and it only understands `:dep` lines for the crate under test
(`tilezz`); a notebook that pulls in other crates via `:dep` will surface
that as a compile error rather than a silent skip.

Usage:
    python3 notebooks/check.py                # build + run every notebook
    python3 notebooks/check.py --no-run       # compile only (faster)
    python3 notebooks/check.py --timeout 120  # per-notebook seconds

Exit code is non-zero if any notebook fails, so it drops straight into a
release gate (a justfile recipe or a CI step).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

CRATE = "tilezz"  # the crate under test; its :dep features are honored
REPO = Path(__file__).resolve().parent.parent
NB_DIR = REPO / "notebooks"
# Generated harness lives under target/ (git-ignored); its own build
# cache persists there so repeat runs are fast.
HARNESS = REPO / "target" / "nbcheck"

# A line that ends a cell as a bare expression (e.g. `scene.display(&vp)`)
# must gain a `;` once spliced mid-function, or the concatenation will not
# parse. We append one unless the line already closes a statement/block.
_STMT_END = (";", "{", "}", ",")


def extract(nb_path: Path) -> tuple[set[str], str]:
    """Return (tilezz features, splice-ready Rust source) for a notebook."""
    doc = json.loads(nb_path.read_text())
    features: set[str] = set()
    body: list[str] = []
    for cell in doc.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        kept: list[str] = []
        for raw in cell["source"]:
            line = raw.rstrip("\n")
            if line.lstrip().startswith(":"):
                # evcxr magic; harvest features off the tilezz :dep, drop it.
                if CRATE in line:
                    m = re.search(r"features\s*=\s*\[([^\]]*)\]", line)
                    if m:
                        features |= {
                            f.strip().strip("\"'")
                            for f in m.group(1).split(",")
                            if f.strip()
                        }
                continue
            kept.append(line)
        # Find the cell's last meaningful line and terminate a trailing
        # expression so the next cell's statements parse after it.
        j = len(kept) - 1
        while j >= 0 and (not kept[j].strip() or kept[j].lstrip().startswith("//")):
            j -= 1
        if j >= 0:
            tail = kept[j].rstrip()
            if tail and tail[-1] not in _STMT_END:
                kept[j] = tail + ";"
        body.extend(kept)
    return features, "\n".join(body)


def write_harness(notebooks: list[Path]) -> list[tuple[Path, str]]:
    """Generate the harness crate; return [(notebook, bin_name)]."""
    (HARNESS / "src").mkdir(parents=True, exist_ok=True)
    union: set[str] = set()
    bins: list[tuple[Path, str]] = []
    for nb in notebooks:
        feats, code = extract(nb)
        union |= feats
        stem = re.sub(r"[^0-9A-Za-z_]", "_", nb.stem)
        (HARNESS / "src" / f"{stem}.rs").write_text(
            "#![allow(warnings)]\nfn main() {\n" + code + "\n}\n"
        )
        bins.append((nb, stem))

    feat_list = ", ".join(f'"{f}"' for f in sorted(union))
    cargo = (
        "# Auto-generated by notebooks/check.py -- do not edit.\n"
        '[package]\nname = "nbcheck"\nversion = "0.0.0"\nedition = "2021"\n\n'
        "[dependencies]\n"
        f'{CRATE} = {{ path = "{REPO.as_posix()}", features = [{feat_list}] }}\n'
    )
    for _, stem in bins:
        cargo += f'\n[[bin]]\nname = "{stem}"\npath = "src/{stem}.rs"\n'
    (HARNESS / "Cargo.toml").write_text(cargo)
    return bins


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--no-run",
        dest="run",
        action="store_false",
        help="compile only; do not execute the notebooks",
    )
    ap.add_argument(
        "--timeout",
        type=int,
        default=300,
        help="per-notebook seconds before giving up (default 300)",
    )
    args = ap.parse_args()

    notebooks = sorted(p for p in NB_DIR.glob("*.ipynb"))
    if not notebooks:
        print(f"no notebooks found under {NB_DIR}", file=sys.stderr)
        return 1

    bins = write_harness(notebooks)
    verb = "run" if args.run else "build"
    print(f"checking {len(bins)} notebook(s) against the working tree ({verb}):\n")

    failures: list[str] = []
    for nb, stem in bins:
        print(f"  {nb.name} ... ", end="", flush=True)
        cmd = ["cargo", verb, "--quiet", "--bin", stem]
        try:
            proc = subprocess.run(
                cmd,
                cwd=HARNESS,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                timeout=args.timeout,
            )
        except subprocess.TimeoutExpired:
            failures.append(nb.name)
            print(f"TIMEOUT (>{args.timeout}s)")
            continue
        if proc.returncode == 0:
            print("ok")
        else:
            failures.append(nb.name)
            print("FAIL")
            sys.stdout.write(proc.stdout)

    print()
    if failures:
        print(f"FAILED: {len(failures)}/{len(bins)} -- {', '.join(failures)}")
        return 1
    print(f"OK: all {len(bins)} notebooks {verb} cleanly.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
