//! Generic engine for integer-basis cyclotomic rings.
//!
//! Every ring `ZZ_n` whose minimal polynomial of `zeta = e^(2*pi*i/n)` over
//! `Z` is the cyclotomic polynomial `Phi_n(x)` can be stored as an integer
//! coefficient vector against the power basis `{1, zeta, ..., zeta^(phi(n)-1)}`.
//! The pieces that vary per ring are:
//!
//! * `n` -- the order of `zeta`,
//! * `phi(n)` -- the dimension of the basis (= storage width),
//! * the *reduction rule* for `zeta^phi(n)` back into the basis (encoded as
//!   `Phi_n(x) = 0`), and
//! * a small set of *precomputed projections* (conjugation matrix, Cartesian
//!   embedding, real/imag-part decomposition into the ring's real subring,
//!   ...) that the macro-driven per-ring impls feed into the generic helpers.
//!
//! This module is the *engine* for that representation: it exposes pure
//! free functions parametric over `const PHI` (and where relevant a second
//! `const K = phi(n)/2` for the real subring), all operating on bare
//! `[i64; PHI]` storage and per-ring constant tables. No types are defined
//! here -- types live in the per-ring modules generated by `define_integral_zz!`
//! (added in step 2 of the refactor).
//!
//! ZZ12 in `zz12.rs` is the reference, hand-written implementation of this
//! same layout. Its inline math (reduction rule, conjugation, Cartesian
//! projection, real/imag-sign, 3-mul `intersect_unit_segments`) is what the
//! generic helpers in this file generalize -- each helper's doc-comment
//! refers back to the relevant ZZ12 fragment.
//!
//! All helpers are `#[inline]` and `const PHI`-generic so LLVM can fully
//! unroll the inner loops when `PHI` is known at the call site (it always is,
//! per-ring).

use num_complex::Complex64;

// ----------------
// Trivial linear ops.

/// Coefficient-wise addition.
///
/// Mirrors `ZZ12`'s `Add` impl in `zz12.rs`.
#[inline]
pub fn add_basis<const PHI: usize>(x: &[i64; PHI], y: &[i64; PHI]) -> [i64; PHI] {
    let mut out = [0i64; PHI];
    let mut i = 0;
    while i < PHI {
        out[i] = x[i] + y[i];
        i += 1;
    }
    out
}

/// Coefficient-wise subtraction.
#[inline]
pub fn sub_basis<const PHI: usize>(x: &[i64; PHI], y: &[i64; PHI]) -> [i64; PHI] {
    let mut out = [0i64; PHI];
    let mut i = 0;
    while i < PHI {
        out[i] = x[i] - y[i];
        i += 1;
    }
    out
}

/// Coefficient-wise negation.
#[inline]
pub fn neg_basis<const PHI: usize>(x: &[i64; PHI]) -> [i64; PHI] {
    let mut out = [0i64; PHI];
    let mut i = 0;
    while i < PHI {
        out[i] = -x[i];
        i += 1;
    }
    out
}

// ----------------
// Multiplication, mod the cyclotomic polynomial.

/// Multiply two elements in the power basis `{1, zeta, ..., zeta^(PHI-1)}`,
/// reducing modulo `Phi_n(x) = 0`.
///
/// `reduction[k]` is the coefficient of `zeta^k` in the basis expansion of
/// `zeta^PHI`. For example, for ZZ12 with `Phi_12(x) = x^4 - x^2 + 1`,
/// `zeta^4 = zeta^2 - 1`, so `reduction = [-1, 0, 1, 0]`.
///
/// Strategy: compute the unreduced polynomial product into a scratch buffer
/// of length `2*PHI - 1`, then fold every power `>= PHI` into the lower
/// half by repeated application of the reduction rule. Because `reduction`
/// is applied at most `PHI - 1` times, the cost is `O(PHI^2)` total --
/// the same complexity as ZZ12's hand-written `Mul`.
///
/// LLVM unrolls all inner loops when `PHI` is a compile-time constant.
///
/// # Example
///
/// A tiny 2-element ring (think `Z[i]` with the basis `{1, i}` and the
/// reduction `i^2 = -1`, so `reduction = [-1, 0]`):
///
/// ```
/// use tilezz::cyclotomic::integral_basis::mul_basis;
/// let one_i = [0i64, 1];     // = i
/// let reduction = [-1i64, 0]; // i^2 = -1
/// // (1 + i) * (1 + i) = 1 + 2i + i^2 = 2i
/// let x = [1i64, 1];
/// let y = [1i64, 1];
/// assert_eq!(mul_basis::<2>(&x, &y, &reduction), [0, 2]);
/// // i * i = -1
/// assert_eq!(mul_basis::<2>(&one_i, &one_i, &reduction), [-1, 0]);
/// ```
#[inline]
pub fn mul_basis<const PHI: usize>(
    x: &[i64; PHI],
    y: &[i64; PHI],
    reduction: &[i64; PHI],
) -> [i64; PHI] {
    // Allocate the scratch buffer on the stack at size `2 * PHI`. We only
    // populate the first `2*PHI - 1` entries; the trailing slot is unused
    // and never read. Using `2 * PHI` here (rather than `2 * PHI - 1`) lets
    // us avoid `generic_const_exprs` -- on stable Rust we cannot name
    // `[i64; 2*PHI - 1]` directly from a generic.
    let mut scratch = [0i64; 32];
    debug_assert!(
        2 * PHI <= scratch.len(),
        "mul_basis: PHI={} too large for 32-slot scratch",
        PHI,
    );

    // Polynomial product.
    let mut i = 0;
    while i < PHI {
        let xi = x[i];
        if xi != 0 {
            let mut j = 0;
            while j < PHI {
                scratch[i + j] += xi * y[j];
                j += 1;
            }
        }
        i += 1;
    }

    // Reduce powers `>= PHI` down into `0..PHI`. We work from the highest
    // power downward, so each fold is a single application of the rule.
    // After folding `zeta^k` (for `k > PHI`), the contribution lives in
    // `scratch[k - PHI ..= k - 1]` (i.e. shifted into the next-lower power
    // window), which then gets folded in turn.
    //
    // Concretely: `zeta^k = zeta^(k - PHI) * zeta^PHI
    //                     = zeta^(k - PHI) * sum_j reduction[j] * zeta^j
    //                     = sum_j reduction[j] * zeta^(k - PHI + j)`.
    let mut k = 2 * PHI - 2;
    while k >= PHI {
        let coeff = scratch[k];
        if coeff != 0 {
            scratch[k] = 0;
            let base = k - PHI;
            let mut j = 0;
            while j < PHI {
                scratch[base + j] += coeff * reduction[j];
                j += 1;
            }
        }
        k -= 1;
    }

    // Extract the low `PHI` slots.
    let mut out = [0i64; PHI];
    let mut i = 0;
    while i < PHI {
        out[i] = scratch[i];
        i += 1;
    }
    out
}

// ----------------
// Conjugation (precomputed matrix).

/// Apply a precomputed conjugation matrix: returns `conj(z) = M * z` where
/// `M[i][j]` is the coefficient of `zeta^i` in the basis expansion of
/// `conj(zeta^j)`.
///
/// The matrix is derivable from `reduction` via [`derive_conj_matrix`].
/// For ZZ12, this generalizes the hand-written formula
/// `conj((a, b, c, d)) = (a + c, b, -c, -b - d)` from `zz12.rs`.
#[inline]
pub fn conj_basis<const PHI: usize>(
    x: &[i64; PHI],
    conj_matrix: &[[i64; PHI]; PHI],
) -> [i64; PHI] {
    let mut out = [0i64; PHI];
    let mut i = 0;
    while i < PHI {
        let mut acc: i64 = 0;
        let mut j = 0;
        while j < PHI {
            acc += conj_matrix[i][j] * x[j];
            j += 1;
        }
        out[i] = acc;
        i += 1;
    }
    out
}

// ----------------
// Cartesian projection.

/// Project an integral-basis element to Cartesian `Complex64` via a
/// precomputed per-basis-element complex value table.
///
/// `cartesian[k]` is the `Complex64` value of `zeta^k`. The result is
/// `sum_k x[k] * cartesian[k]`.
///
/// This generalizes ZZ12's hand-written `complex64()` in `zz12.rs`, which
/// inlines the `(1, zeta, zeta^2, zeta^3)` table for `zeta = sqrt(3)/2 + i/2`.
#[inline]
pub fn complex64_basis<const PHI: usize>(
    x: &[i64; PHI],
    cartesian: &[Complex64; PHI],
) -> Complex64 {
    let mut acc = Complex64::new(0.0, 0.0);
    let mut i = 0;
    while i < PHI {
        let xi = x[i] as f64;
        acc += Complex64::new(xi * cartesian[i].re, xi * cartesian[i].im);
        i += 1;
    }
    acc
}

// ----------------
// Re/Im sign extraction via real-subring projection.
//
// For a cyclotomic ring `ZZ_n` with `phi(n) = 2K`, the real subring has
// dimension `K = phi(n)/2`. Re(zeta^k) and Im(zeta^k) both live in this
// real subring, and each can be written as a vector of `K` integer
// coefficients against some symbolic real-subring basis (the same basis
// the per-ring `signum_sum_sqrt_expr_*` function consumes).
//
// `re_decomp[k]` is the K-vector of coefficients of Re(zeta^k); likewise
// `im_decomp[k]`. The denominator implicit in these decompositions (e.g.
// the `/2` in ZZ12's `Re(zeta) = sqrt(3)/2`) is positive and shared across
// all entries, so it doesn't affect the sign and is omitted from the
// generic shape.

/// Sign of `Re(z)` via projection to the ring's real subring, then per-ring
/// `real_sign`.
///
/// `re_decomp[k]` is the K-vector of real-subring coefficients for
/// `Re(zeta^k)`. The accumulated K-vector for `Re(z)` is
/// `sum_k x[k] * re_decomp[k]`, fed to `real_sign`.
///
/// For ZZ12, this generalizes the hand-written
/// `re_sign(self) = sign_m_plus_n_sqrt3(2a + c, b)` from `zz12.rs`.
#[inline]
pub fn re_sign_basis<const PHI: usize, const K: usize>(
    x: &[i64; PHI],
    re_decomp: &[[i64; K]; PHI],
    real_sign: fn(&[i64; K]) -> i8,
) -> i8 {
    let mut acc = [0i64; K];
    let mut i = 0;
    while i < PHI {
        let xi = x[i];
        if xi != 0 {
            let mut j = 0;
            while j < K {
                acc[j] += xi * re_decomp[i][j];
                j += 1;
            }
        }
        i += 1;
    }
    real_sign(&acc)
}

/// Sign of `Im(z)` via projection to the ring's real subring, then per-ring
/// `real_sign`. Same shape as [`re_sign_basis`] but indexes `im_decomp`.
#[inline]
pub fn im_sign_basis<const PHI: usize, const K: usize>(
    x: &[i64; PHI],
    im_decomp: &[[i64; K]; PHI],
    real_sign: fn(&[i64; K]) -> i8,
) -> i8 {
    let mut acc = [0i64; K];
    let mut i = 0;
    while i < PHI {
        let xi = x[i];
        if xi != 0 {
            let mut j = 0;
            while j < K {
                acc[j] += xi * im_decomp[i][j];
                j += 1;
            }
        }
        i += 1;
    }
    real_sign(&acc)
}

// ----------------
// Unit-segment intersection (3-multiplication fast path).

/// Generic version of ZZ12's `intersect_unit_segments` fast path.
///
/// Assumes both segments have unit length (i.e. `s.1 - s.0` is a unit of
/// the ring's CCW unit group); endpoint coincidence already filtered.
///
/// Math (see `zz12.rs` for the full derivation -- the helper is shape-
/// identical, just generalized):
///
/// ```text
///   uA = s1.1 - s1.0,  uB = s2.1 - s2.0,  delta = s2.0 - s1.0
///   v_z = conj(uA) * delta            ZZ mul #1 (V = Im(v_z), and Re(v_z) = dot(uA, delta))
///   k_z = conj(uA) * uB               ZZ mul #2 (K = Im(k_z))
///   w_z = conj(delta) * uB            ZZ mul #3 (W = Im(w_z))
/// ```
///
/// Non-colinear branch (when `sign(K) != 0`):
///
/// ```text
///   (sign(V) > 0) != (sign(V + K) > 0)
///   && (sign(W) > 0) != (sign(W - K) > 0)
/// ```
///
/// Colinear sub-case (`sign(K) == 0`): `k_z` is then a real `+/-1`. We read
/// `Re(v_z) = dot(uA, delta) = T` (via the same `v_z` already computed) and
/// the interior-overlap condition depends on whether `k_z` reduces to `+1`
/// (`uA == uB`, overlap iff `-1 < T < 1`) or `-1` (`uA == -uB`, overlap iff
/// `0 < T < 2`). The K-vector for `T +/- 1` is `re_decomp[0] -/+
/// re_decomp[0]_at_one`... but the practical implementation reads
/// `re_decomp` against `v_z` to get the symbolic K-vector and shifts the
/// first coordinate to test `T - bound` for each cutoff.
///
/// Note: the shift representation depends on the per-ring symbolic basis
/// (specifically how `1` is expressed in `re_decomp`). To keep this helper
/// closed-form across rings we pass `one_in_real_basis: &[i64; K]` -- the
/// K-vector for the constant `+1` -- so the call site doesn't have to know
/// the basis layout.
///
/// `re_decomp[k]` here is the K-vector of `Re(zeta^k)` -- the *same* table
/// used by [`re_sign_basis`]. We do not need `im_decomp` here because the
/// imaginary part comes from `Im(v_z)`, `Im(k_z)`, `Im(w_z)` via
/// [`im_sign_basis`].
///
/// In step 1 this helper is provided primarily for shape and is not yet
/// exercised by any ring -- ZZ12 still uses its hand-written specialization.
/// Step 2 routes ZZ12 through this helper once we are happy with the
/// generic version.
#[inline]
#[allow(clippy::too_many_arguments)]
pub fn intersect_unit_segments_basis<const PHI: usize, const K: usize>(
    s1: &([i64; PHI], [i64; PHI]),
    s2: &([i64; PHI], [i64; PHI]),
    reduction: &[i64; PHI],
    conj_matrix: &[[i64; PHI]; PHI],
    re_decomp: &[[i64; K]; PHI],
    im_decomp: &[[i64; K]; PHI],
    one_in_real_basis: &[i64; K],
    real_sign: fn(&[i64; K]) -> i8,
) -> bool {
    let (a, b) = (s1.0, s1.1);
    let (c, d) = (s2.0, s2.1);

    // Touching endpoints do not count as a proper intersection.
    if a == c || a == d || b == c || b == d {
        return false;
    }

    let u_a = sub_basis::<PHI>(&b, &a);
    let u_b = sub_basis::<PHI>(&d, &c);
    let delta = sub_basis::<PHI>(&c, &a);

    let conj_u_a = conj_basis::<PHI>(&u_a, conj_matrix);

    // Mul #1: v_z = conj(uA) * delta.
    let v_z = mul_basis::<PHI>(&conj_u_a, &delta, reduction);
    let sign_v = im_sign_basis::<PHI, K>(&v_z, im_decomp, real_sign);

    // Mul #2: k_z = conj(uA) * uB.
    let k_z = mul_basis::<PHI>(&conj_u_a, &u_b, reduction);
    let sign_k = im_sign_basis::<PHI, K>(&k_z, im_decomp, real_sign);

    if sign_k == 0 {
        // uA parallel to uB. If V != 0 the lines are distinct parallels.
        if sign_v != 0 {
            return false;
        }
        // Colinear. T = Re(v_z) = dot(uA, delta) lives in the real subring;
        // its K-vector is sum_k v_z[k] * re_decomp[k].
        let t = project_re::<PHI, K>(&v_z, re_decomp);
        // k_z is +/-1 (a real unit). Decide which by checking
        // sign(k_z[0] - 1) etc, but it is cheaper to read the integer-basis
        // coeff of `1`, i.e. k_z[0], plus the others being zero -- those
        // are guaranteed when sign_k == 0 in the unit-segment setting.
        // For robustness across rings we use the projected real part of
        // k_z (a single integer comparison), which is +1 or -1 in either
        // case.
        let k_real = project_re::<PHI, K>(&k_z, re_decomp);
        let sign_k_real = real_sign(&k_real);
        if sign_k_real > 0 {
            // uA == uB: interior overlap iff -1 < T < 1.
            let t_plus_1 = add_kvec::<K>(&t, one_in_real_basis);
            let t_minus_1 = sub_kvec::<K>(&t, one_in_real_basis);
            return real_sign(&t_plus_1) > 0 && real_sign(&t_minus_1) < 0;
        } else {
            // uA == -uB: interior overlap iff 0 < T < 2.
            let two = scale_kvec::<K>(one_in_real_basis, 2);
            let t_minus_2 = sub_kvec::<K>(&t, &two);
            return real_sign(&t) > 0 && real_sign(&t_minus_2) < 0;
        }
    }

    // Non-colinear case.
    let v_plus_k = add_basis::<PHI>(&v_z, &k_z);
    let sign_v_plus_k = im_sign_basis::<PHI, K>(&v_plus_k, im_decomp, real_sign);
    if (sign_v > 0) == (sign_v_plus_k > 0) {
        return false;
    }

    // Mul #3: w_z = conj(delta) * uB.
    let conj_delta = conj_basis::<PHI>(&delta, conj_matrix);
    let w_z = mul_basis::<PHI>(&conj_delta, &u_b, reduction);
    let w_minus_k = sub_basis::<PHI>(&w_z, &k_z);
    let sign_w = im_sign_basis::<PHI, K>(&w_z, im_decomp, real_sign);
    let sign_w_minus_k = im_sign_basis::<PHI, K>(&w_minus_k, im_decomp, real_sign);
    (sign_w > 0) != (sign_w_minus_k > 0)
}

#[inline]
fn project_re<const PHI: usize, const K: usize>(
    x: &[i64; PHI],
    re_decomp: &[[i64; K]; PHI],
) -> [i64; K] {
    let mut acc = [0i64; K];
    let mut i = 0;
    while i < PHI {
        let xi = x[i];
        if xi != 0 {
            let mut j = 0;
            while j < K {
                acc[j] += xi * re_decomp[i][j];
                j += 1;
            }
        }
        i += 1;
    }
    acc
}

#[inline]
fn add_kvec<const K: usize>(x: &[i64; K], y: &[i64; K]) -> [i64; K] {
    let mut out = [0i64; K];
    let mut i = 0;
    while i < K {
        out[i] = x[i] + y[i];
        i += 1;
    }
    out
}

#[inline]
fn sub_kvec<const K: usize>(x: &[i64; K], y: &[i64; K]) -> [i64; K] {
    let mut out = [0i64; K];
    let mut i = 0;
    while i < K {
        out[i] = x[i] - y[i];
        i += 1;
    }
    out
}

#[inline]
fn scale_kvec<const K: usize>(x: &[i64; K], s: i64) -> [i64; K] {
    let mut out = [0i64; K];
    let mut i = 0;
    while i < K {
        out[i] = x[i] * s;
        i += 1;
    }
    out
}

// ----------------
// Derived per-ring tables (intended for use at startup, behind `OnceLock`).

/// Build the conjugation matrix `M` such that `conj(z) = M * z` (column-major:
/// column `j` is `conj(zeta^j)` expanded into the integer basis).
///
/// `n` is the order of `zeta`; conjugation is `conj(zeta^j) = zeta^(n - j)`.
/// We compute `zeta^k` for `k = 0..n` by iterated multiplication by `zeta`
/// (using [`mul_basis`] with the given `reduction`), then read out
/// `conj_matrix[i][j] = (zeta^(n - j))[i]`.
///
/// # Example
///
/// For the 2-element `Z[i]` ring with `n = 4`, basis `{1, i}`, reduction
/// `[-1, 0]`:
///
/// ```
/// use tilezz::cyclotomic::integral_basis::derive_conj_matrix;
/// let m = derive_conj_matrix::<2>(4, &[-1, 0]);
/// // conj(1) = 1            -> column 0 = [1, 0]
/// // conj(zeta) = zeta^3 = -i = (0, -1) (since zeta = i, zeta^2 = -1, zeta^3 = -i)
/// //   -> column 1 = [0, -1]
/// assert_eq!(m, [[1, 0], [0, -1]]);
/// ```
pub fn derive_conj_matrix<const PHI: usize>(
    n: usize,
    reduction: &[i64; PHI],
) -> [[i64; PHI]; PHI] {
    let units = derive_units_lookup::<PHI>(n, reduction);
    let mut out = [[0i64; PHI]; PHI];
    let mut j = 0;
    while j < PHI {
        // conj(zeta^j) = zeta^(n - j), with zeta^0 used when j == 0.
        let idx = if j == 0 { 0 } else { n - j };
        let col = &units[idx];
        let mut i = 0;
        while i < PHI {
            out[i][j] = col[i];
            i += 1;
        }
        j += 1;
    }
    out
}

/// Compute the unit lookup table: `zeta^k` in the integer basis for
/// `k = 0..=n`. Index `0` is `1`, index `n` is `1` again (full turn).
///
/// Implementation: start at `zeta^0 = (1, 0, ..., 0)` and repeatedly multiply
/// by `zeta = (0, 1, 0, ..., 0)`, reducing each step via [`mul_basis`].
///
/// For each per-ring `OnceLock` unit table, the macro-generated impl wraps a
/// call to this helper and indexes by `angle.rem_euclid(n)`.
pub fn derive_units_lookup<const PHI: usize>(
    n: usize,
    reduction: &[i64; PHI],
) -> Vec<[i64; PHI]> {
    assert!(PHI >= 1, "PHI must be >= 1");
    let mut out: Vec<[i64; PHI]> = Vec::with_capacity(n + 1);

    let mut one = [0i64; PHI];
    one[0] = 1;
    out.push(one);

    if PHI == 1 {
        // Degenerate case: ZZ_1 / ZZ_2. zeta is +/-1, captured entirely by
        // the reduction rule `reduction[0] = +/-1`. zeta^k cycles with
        // period 1 or 2.
        let mut k = 1;
        while k <= n {
            let prev = out[k - 1];
            // zeta * prev: only the zeta^0 slot got prev[0], pushed up to
            // zeta^1 which immediately reduces.
            let mut next = [0i64; PHI];
            next[0] = prev[0] * reduction[0];
            out.push(next);
            k += 1;
        }
        return out;
    }

    let mut zeta = [0i64; PHI];
    zeta[1] = 1;

    let mut k = 1;
    while k <= n {
        let prev = out[k - 1];
        let next = mul_basis::<PHI>(&prev, &zeta, reduction);
        out.push(next);
        k += 1;
    }
    out
}

// ----------------
// Macro skeleton.

/// Define an integer-basis cyclotomic ring `ZZ_n`.
///
/// **Step 1 status:** this macro currently generates only a struct shell --
/// a `[i64; PHI]`-backed wrapper with `from_int_coeffs` / `int_coeffs`
/// accessors and the standard derives -- to validate that the
/// macro+const-generic shape compiles. Step 2 expands the body into the full
/// impl-bag (Add/Sub/Mul/Neg, SymNum, Conj, Units, ReImSign, WithinRadius,
/// IntersectUnitSegments, ...) by routing each impl to the generic
/// `integral_basis::*` helpers parameterized on the per-ring constants
/// listed below.
///
/// # Parameters
///
/// * `name` -- ring type name (`ZZ12`, `ZZ24`, ...).
/// * `n` -- order of `zeta`.
/// * `phi` -- `phi(n)`, the storage width.
/// * `real_dim` -- `phi(n)/2`, the real-subring dimension `K`.
/// * `reduction` -- `[i64; PHI]`, expansion of `zeta^PHI` in the integer basis.
/// * `re_decomp` -- `[[i64; K]; PHI]`, K-vector of `Re(zeta^k)` per `k`.
/// * `im_decomp` -- `[[i64; K]; PHI]`, K-vector of `Im(zeta^k)` per `k`.
/// * `cartesian` -- `[Complex64; PHI]`, Cartesian value of `zeta^k` per `k`.
/// * `real_sign_fn` -- `fn(&[i64; K]) -> i8`, sign of a K-vector against the
///   ring's real-subring symbolic basis (one of `signum_sum_sqrt_expr_*`
///   from `cyclotomic::sign`, wrapped to the right K).
/// * `has` -- list of `HasZZk` subring-containment markers, e.g.
///   `[HasZZ4, HasZZ6, HasZZ12]`. The macro emits a `zz_triv_impl!`-style
///   empty `Has*Impl` block per entry (step 2).
#[macro_export]
macro_rules! define_integral_zz {
    (
        name: $name:ident,
        n: $n:expr,
        phi: $phi:expr,
        real_dim: $k:expr,
        reduction: $reduction:expr,
        re_decomp: $re_decomp:expr,
        im_decomp: $im_decomp:expr,
        cartesian: $cartesian:expr,
        real_sign_fn: $real_sign:path,
        has: [$($has:ident),* $(,)?] $(,)?
    ) => {
        // Step 1: emit only the struct shell plus const-access helpers. The
        // const-generic call sites baked in here will exercise the
        // const-generic surface of `integral_basis::*` end-to-end without
        // forcing the rest of the per-ring impl-bag to land in step 1.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub struct $name {
            coeffs: [i64; $phi],
        }

        impl $name {
            /// The order of `zeta` for this ring.
            pub const N: usize = $n;
            /// The storage width, `phi(n)`.
            pub const PHI: usize = $phi;
            /// The real-subring dimension, `phi(n) / 2`.
            pub const REAL_DIM: usize = $k;
            /// The reduction rule for `zeta^PHI` in the integer basis.
            pub const REDUCTION: [i64; $phi] = $reduction;

            #[inline]
            pub const fn from_int_coeffs(coeffs: [i64; $phi]) -> Self {
                Self { coeffs }
            }

            /// Raw access to the integer-basis coefficients.
            #[inline]
            pub const fn int_coeffs(&self) -> [i64; $phi] {
                self.coeffs
            }
        }

        // Silence "constant never used" warnings for the per-ring tables on
        // step-1 builds where they aren't routed through impls yet. Each is
        // a `const` already, so this is just a single use-site to keep the
        // value live.
        impl $name {
            #[doc(hidden)]
            pub const __RE_DECOMP: [[i64; $k]; $phi] = $re_decomp;
            #[doc(hidden)]
            pub const __IM_DECOMP: [[i64; $k]; $phi] = $im_decomp;
            #[doc(hidden)]
            pub const __CARTESIAN: [num_complex::Complex64; $phi] = $cartesian;
            #[doc(hidden)]
            pub const __REAL_SIGN: fn(&[i64; $k]) -> i8 = $real_sign;
        }

        // Mark the requested subring-containment traits (no-op step 1: just
        // record the names so the call sites validate).
        $(
            const _: fn() = || {
                // Drop the literal in a typecheck-only context so it's not
                // an unused-variable warning. Treats `$has` as an ident the
                // caller is expected to import.
                #[allow(dead_code)]
                fn _check<T: $crate::cyclotomic::$has>() {}
            };
        )*
    };
}

// ----------------
// Tests

#[cfg(test)]
mod tests {
    use super::*;

    // A tiny "ZZ_4 as Z[i]" smoke test: basis {1, i}, reduction i^2 = -1.
    // Not a real ring of interest, just a fast sanity check of the engine.
    const RED_I: [i64; 2] = [-1, 0];

    #[test]
    fn add_sub_neg() {
        let x = [3i64, 4];
        let y = [1i64, 2];
        assert_eq!(add_basis::<2>(&x, &y), [4, 6]);
        assert_eq!(sub_basis::<2>(&x, &y), [2, 2]);
        assert_eq!(neg_basis::<2>(&x), [-3, -4]);
    }

    #[test]
    fn mul_smoke_z_i() {
        // (a + bi)(c + di) = (ac - bd) + (ad + bc)i
        let x = [3i64, 4]; // 3 + 4i
        let y = [1i64, 2]; // 1 + 2i
        // (3 + 4i)(1 + 2i) = 3 + 6i + 4i + 8i^2 = 3 + 10i - 8 = -5 + 10i
        assert_eq!(mul_basis::<2>(&x, &y, &RED_I), [-5, 10]);

        // i * i = -1
        let i = [0i64, 1];
        assert_eq!(mul_basis::<2>(&i, &i, &RED_I), [-1, 0]);
    }

    #[test]
    fn derive_conj_matrix_z_i() {
        // n = 4, basis {1, i}, conj(1) = 1, conj(i) = -i.
        let m = derive_conj_matrix::<2>(4, &RED_I);
        assert_eq!(m, [[1, 0], [0, -1]]);

        // Apply: conj(3 + 4i) = 3 - 4i.
        let z = [3i64, 4];
        assert_eq!(conj_basis::<2>(&z, &m), [3, -4]);
    }

    #[test]
    fn derive_units_lookup_z_i() {
        // n = 4: zeta^0 = 1, zeta^1 = i, zeta^2 = -1, zeta^3 = -i, zeta^4 = 1.
        let u = derive_units_lookup::<2>(4, &RED_I);
        assert_eq!(u.len(), 5);
        assert_eq!(u[0], [1, 0]);
        assert_eq!(u[1], [0, 1]);
        assert_eq!(u[2], [-1, 0]);
        assert_eq!(u[3], [0, -1]);
        assert_eq!(u[4], [1, 0]);
    }

    #[test]
    fn mul_smoke_zz12_pattern() {
        // Use ZZ12's reduction rule: Phi_12 = x^4 - x^2 + 1, so
        // zeta^4 = zeta^2 - 1, i.e. reduction = [-1, 0, 1, 0].
        const RED_ZZ12: [i64; 4] = [-1, 0, 1, 0];

        // zeta * zeta = zeta^2.
        let zeta = [0i64, 1, 0, 0];
        assert_eq!(mul_basis::<4>(&zeta, &zeta, &RED_ZZ12), [0, 0, 1, 0]);

        // zeta^2 * zeta^2 = zeta^4 = zeta^2 - 1.
        let zeta_sq = [0i64, 0, 1, 0];
        assert_eq!(
            mul_basis::<4>(&zeta_sq, &zeta_sq, &RED_ZZ12),
            [-1, 0, 1, 0],
        );

        // zeta^3 * zeta^3 = zeta^6 = zeta * zeta^5 = ... = -1.
        let zeta_cu = [0i64, 0, 0, 1];
        assert_eq!(mul_basis::<4>(&zeta_cu, &zeta_cu, &RED_ZZ12), [-1, 0, 0, 0]);
    }

    #[test]
    fn re_im_sign_z_i() {
        // For Z[i]: Re(1) = 1, Re(i) = 0, Im(1) = 0, Im(i) = 1.
        // Real subring is just Z, so K = 1 and real_sign is plain sign of
        // the lone integer coefficient.
        const RE: [[i64; 1]; 2] = [[1], [0]];
        const IM: [[i64; 1]; 2] = [[0], [1]];
        fn sgn(x: &[i64; 1]) -> i8 {
            x[0].signum() as i8
        }
        let z = [3i64, -4];
        assert_eq!(re_sign_basis::<2, 1>(&z, &RE, sgn), 1);
        assert_eq!(im_sign_basis::<2, 1>(&z, &IM, sgn), -1);
    }

    #[test]
    fn complex64_z_i() {
        use num_complex::Complex64;
        let cart = [Complex64::new(1.0, 0.0), Complex64::new(0.0, 1.0)];
        let z = [3i64, -4];
        let c = complex64_basis::<2>(&z, &cart);
        assert!((c.re - 3.0).abs() < 1e-12);
        assert!((c.im + 4.0).abs() < 1e-12);
    }
}
