//! Per-ring `define_integral_zz!` invocations.
//!
//! Each ring in this file lives in the integer-basis cyclotomic
//! representation (`[i64; phi(n)]` over `{1, zeta, ..., zeta^(phi(n)-1)}`)
//! and is generated by a single macro invocation feeding the per-ring
//! constant bundle (reduction rule, real/imag decomposition tables,
//! Cartesian projection, sign function) into the generic engine in
//! `cyclotomic::integral_basis`.

use num_complex::Complex64;
use num_rational::Ratio;

use crate::cyclotomic::gaussint::GaussInt;
use crate::cyclotomic::params::{
    ZZ10_PARAMS, ZZ10_Y, ZZ12_PARAMS, ZZ16_PARAMS, ZZ16_Y, ZZ20_PARAMS, ZZ24_PARAMS, ZZ32_PARAMS,
    ZZ32_Z, ZZ4_PARAMS, ZZ60_PARAMS, ZZ8_PARAMS,
};
use crate::define_integral_zz;

// ----------------
// Generic Display helper for integer-basis rings.
//
// Each per-ring display function projects its integer-basis vector back to
// a vector of `GaussInt<Ratio<i64>>` coefficients against the symbolic
// `sqrt(lbl)` basis (the same basis the legacy `impl_symnum_display`
// expected), then calls this helper to format the symbolic sum.
//
// Output shape matches the legacy macro-generated display:
//   - "0" when all coefficients are zero
//   - "<coeff>" for the `sqrt(1)` term
//   - "<coeff>*sqrt(<lbl>)" for a non-unit sqrt term, with parens around
//     compound coefficient strings.
fn format_symbolic<const K: usize>(
    coeffs: &[GaussInt<Ratio<i64>>; K],
    labels: &[&'static str; K],
    f: &mut std::fmt::Formatter<'_>,
) -> std::fmt::Result {
    let mut parts: Vec<String> = Vec::new();
    for (coeff, lbl) in coeffs.iter().zip(labels.iter()) {
        let s = format!("{coeff}");
        if s == "0" {
            continue;
        }
        let is_real_unit = *lbl == "1";
        let lbl_str = format!("sqrt({lbl})");
        if s == "1" {
            parts.push(if is_real_unit {
                "1".to_string()
            } else {
                lbl_str
            });
        } else if is_real_unit {
            parts.push(s);
        } else {
            parts.push(format!("({s})*{lbl_str}"));
        }
    }
    let joined = parts.join(" + ");
    let result = if joined.is_empty() {
        "0".to_string()
    } else {
        joined
    };
    write!(f, "{result}")
}

// ----------------
// ZZ4 -- Gauss integers Z[i].
//
// `zeta = i`, `Phi_4(x) = x^2 + 1`, so `zeta^2 = -1`. Storage: `[i64; 2]`
// over `{1, i}`. The real subring is just `Z` (K = 1, basis `{1}`).

#[inline]
fn zz4_complex64(coeffs: &[i64; 2]) -> Complex64 {
    Complex64::new(coeffs[0] as f64, coeffs[1] as f64)
}

const ZZ4_CARTESIAN: [Complex64; 2] = [
    Complex64::new(1.0, 0.0), // zeta^0 = 1
    Complex64::new(0.0, 1.0), // zeta^1 = i
];

fn zz4_display(coeffs: &[i64; 2], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    // Match the legacy GaussInt<Ratio> Display format used by the symbolic
    // single-root ring shape (only `sqrt(1)` term, so output is just the
    // GaussInt).
    let g = GaussInt::new(
        Ratio::<i64>::from_integer(coeffs[0]),
        Ratio::<i64>::from_integer(coeffs[1]),
    );
    write!(f, "{g}")
}

/// Sign of an integer K-vector `[m]` against basis `{sqrt(1)}` = `{1}`: just
/// the sign of `m`.
#[inline]
fn zz4_real_sign(x: &[i64; 1]) -> i8 {
    x[0].signum() as i8
}

define_integral_zz! {
    name: ZZ4,
    n: 4,
    phi: 2,
    real_dim: 1,
    // Phi_4(x) = x^2 + 1, so zeta^2 = -1.
    reduction: [-1i64, 0],
    // Re(zeta^0) = 1, Re(zeta^1) = 0.
    re_decomp: [[1i64], [0]],
    // Im(zeta^0) = 0, Im(zeta^1) = 1.
    im_decomp: [[0i64], [1]],
    cartesian: ZZ4_CARTESIAN,
    params: ZZ4_PARAMS,
    one_in_real_basis: [1i64],
    display_fn: zz4_display,
    complex64_fn: zz4_complex64,
    has: [HasZZ4Impl, IsZZ4Impl],
}

impl From<(i64, i64)> for ZZ4 {
    /// `(re, im)` where `i = zeta^1`, so `(a, b) = a + b*i` maps to
    /// integer-basis coefficients `[a, b]`.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        Self::from_int_coeffs([re, im])
    }
}

crate::impl_integral_units_via_basis!(ZZ4, 4);
crate::impl_integral_mul_via_basis!(ZZ4, 2);
crate::impl_integral_conj_via_basis!(ZZ4, 2);
crate::impl_integral_re_im_sign_via_basis!(ZZ4, 2, 1, zz4_real_sign);
crate::impl_integral_intersect_unit_segments_via_basis!(ZZ4, 2, 1, zz4_real_sign);
crate::impl_integral_within_radius_via_complex64!(ZZ4);
crate::zz_integral_ring_tests!(name: ZZ4);

// ----------------
// ZZ8 -- compass integers Z[zeta_8].
//
// `zeta = e^(2*pi*i/8) = (sqrt(2) + i*sqrt(2)) / 2`, `Phi_8(x) = x^4 + 1`,
// so `zeta^4 = -1`. Storage: `[i64; 4]` over `{1, zeta, zeta^2, zeta^3}`.
// The real subring is `Z[sqrt(2)]` (K = 2, basis `{1, sqrt(2)}`) with
// `/2` implicit denominator on the decomposition tables.

const HALF_SQRT_2: f64 = std::f64::consts::SQRT_2 * 0.5;

#[inline]
fn zz8_complex64(coeffs: &[i64; 4]) -> Complex64 {
    // zeta = (sqrt(2)/2, sqrt(2)/2), zeta^2 = (0, 1), zeta^3 = (-sqrt(2)/2, sqrt(2)/2).
    let [a, b, c, d] = *coeffs;
    let (a, b, c, d) = (a as f64, b as f64, c as f64, d as f64);
    let re = a + (b - d) * HALF_SQRT_2;
    let im = (b + d) * HALF_SQRT_2 + c;
    Complex64::new(re, im)
}

const ZZ8_CARTESIAN: [Complex64; 4] = [
    Complex64::new(1.0, 0.0),
    Complex64::new(HALF_SQRT_2, HALF_SQRT_2),
    Complex64::new(0.0, 1.0),
    Complex64::new(-HALF_SQRT_2, HALF_SQRT_2),
];

/// Display impl for ZZ8: project `(a, b, c, d)` back to GaussInt-Ratio
/// coefficients of `{sqrt(1), sqrt(2)}` (the symbolic basis the legacy
/// `impl_symnum_display` consumed).
///
/// ```text
///   zeta^0 = 1                        -> c0 += a
///   zeta^1 = sqrt(2)/2 * (1 + i)      -> c1 += b * (1 + i) / 2
///   zeta^2 = i                        -> c0 += c*i
///   zeta^3 = sqrt(2)/2 * (-1 + i)     -> c1 += d * (-1 + i) / 2
/// ```
fn zz8_display(coeffs: &[i64; 4], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let [a, b, c, d] = *coeffs;
    let half = Ratio::<i64>::new_raw(1, 2);
    let c0 = GaussInt::new(Ratio::<i64>::from_integer(a), Ratio::<i64>::from_integer(c));
    let c1 = GaussInt::new(
        Ratio::<i64>::from_integer(b - d) * half,
        Ratio::<i64>::from_integer(b + d) * half,
    );
    format_symbolic(&[c0, c1], &["1", "2"], f)
}

/// Sign of `a + b*sqrt(2)` for integers `a`, `b`.
#[inline]
fn zz8_real_sign(x: &[i64; 2]) -> i8 {
    crate::cyclotomic::sign::signum_sum_sqrt_expr_2::<i64>(x[0], 1, x[1], 2) as i8
}

define_integral_zz! {
    name: ZZ8,
    n: 8,
    phi: 4,
    real_dim: 2,
    // Phi_8(x) = x^4 + 1, so zeta^4 = -1.
    reduction: [-1i64, 0, 0, 0],
    // Re(zeta^k) in basis {1, sqrt(2)} with implicit /2:
    //   Re(zeta^0) = 1            -> [2, 0] / 2
    //   Re(zeta^1) = sqrt(2)/2    -> [0, 1] / 2
    //   Re(zeta^2) = 0            -> [0, 0] / 2
    //   Re(zeta^3) = -sqrt(2)/2   -> [0, -1] / 2
    re_decomp: [[2i64, 0], [0, 1], [0, 0], [0, -1]],
    // Im(zeta^k):
    //   Im(zeta^0) = 0            -> [0, 0] / 2
    //   Im(zeta^1) = sqrt(2)/2    -> [0, 1] / 2
    //   Im(zeta^2) = 1            -> [2, 0] / 2
    //   Im(zeta^3) = sqrt(2)/2    -> [0, 1] / 2
    im_decomp: [[0i64, 0], [0, 1], [2, 0], [0, 1]],
    cartesian: ZZ8_CARTESIAN,
    params: ZZ8_PARAMS,
    // `1` in basis {1, sqrt(2)} with /2 denominator: [2, 0].
    one_in_real_basis: [2i64, 0],
    display_fn: zz8_display,
    complex64_fn: zz8_complex64,
    has: [HasZZ4Impl, HasZZ8Impl],
}

impl From<(i64, i64)> for ZZ8 {
    /// `(re, im)` where `i = zeta^2`, so `(a, b) = a + b*i` maps to
    /// integer-basis coefficients `[a, 0, b, 0]`.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        Self::from_int_coeffs([re, 0, im, 0])
    }
}

crate::impl_integral_units_via_basis!(ZZ8, 8);
crate::impl_integral_mul_via_basis!(ZZ8, 4);
crate::impl_integral_conj_via_basis!(ZZ8, 4);
crate::impl_integral_re_im_sign_via_basis!(ZZ8, 4, 2, zz8_real_sign);
crate::impl_integral_intersect_unit_segments_via_basis!(ZZ8, 4, 2, zz8_real_sign);
crate::impl_integral_within_radius_via_complex64!(ZZ8);
crate::zz_integral_ring_tests!(name: ZZ8);

// ----------------
// ZZ12

/// Hand-rolled `complex64` for ZZ12: inline `Re`/`Im` of `(a, b, c, d)`
/// in the `{1, zeta, zeta^2, zeta^3}` basis, avoiding the
/// `complex64_basis` loop. Called from `cell_of` on the hot path.
#[inline]
fn zz12_complex64(coeffs: &[i64; 4]) -> Complex64 {
    // zeta = sqrt(3)/2 + i/2
    // Re = a + b * sqrt(3)/2 + c * 1/2 + d * 0
    // Im = 0 + b * 1/2       + c * sqrt(3)/2 + d
    const HALF_SQRT_3: f64 = 0.866_025_403_784_438_6_f64;
    let [a, b, c, d] = *coeffs;
    let (a, b, c, d) = (a as f64, b as f64, c as f64, d as f64);
    let re = a + b * HALF_SQRT_3 + 0.5 * c;
    let im = 0.5 * b + c * HALF_SQRT_3 + d;
    Complex64::new(re, im)
}

/// Cartesian projection table for ZZ12: `zeta^k` as a `Complex64`, for
/// `zeta = e^(i*pi/6) = sqrt(3)/2 + i/2`.
const ZZ12_CARTESIAN: [Complex64; 4] = {
    // sqrt(3)/2 to f64. Kept as a literal to allow `const` evaluation.
    const HALF_SQRT_3: f64 = 0.866_025_403_784_438_6_f64;
    [
        // zeta^0 = 1
        Complex64::new(1.0, 0.0),
        // zeta^1 = sqrt(3)/2 + i/2
        Complex64::new(HALF_SQRT_3, 0.5),
        // zeta^2 = 1/2 + i*sqrt(3)/2
        Complex64::new(0.5, HALF_SQRT_3),
        // zeta^3 = i
        Complex64::new(0.0, 1.0),
    ]
};

/// Display impl for ZZ12. Matches the legacy hand-written format in
/// `zz12.rs`: project the integer-basis vector back to symbolic
/// `{sqrt(1), sqrt(3)}` form and emit the same per-term shape that the
/// macro-generated rings use.
///
/// For `(a, b, c, d)`:
///
/// ```text
///   c0 = ((2a + c)/2) + i*((b + 2d)/2)   coefficient of sqrt(1)
///   c1 = (b/2)        + i*(c/2)          coefficient of sqrt(3)
/// ```
fn zz12_display(coeffs: &[i64; 4], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let [a, b, c, d] = *coeffs;
    let half = Ratio::<i64>::new_raw(1, 2);
    let c0 = GaussInt::new(
        Ratio::<i64>::from_integer(2 * a + c) * half,
        Ratio::<i64>::from_integer(b + 2 * d) * half,
    );
    let c1 = GaussInt::new(
        Ratio::<i64>::from_integer(b) * half,
        Ratio::<i64>::from_integer(c) * half,
    );
    format_symbolic(&[c0, c1], &["1", "3"], f)
}

define_integral_zz! {
    name: ZZ12,
    n: 12,
    phi: 4,
    real_dim: 2,
    // Phi_12(x) = x^4 - x^2 + 1, so zeta^4 = zeta^2 - 1.
    reduction: [-1i64, 0, 1, 0],
    // K-vector of Re(zeta^k) against {sqrt(1), sqrt(3)}, with implicit /2:
    //   Re(zeta^0) = 1            -> [2, 0] / 2
    //   Re(zeta^1) = sqrt(3)/2    -> [0, 1] / 2
    //   Re(zeta^2) = 1/2          -> [1, 0] / 2
    //   Re(zeta^3) = 0            -> [0, 0] / 2
    re_decomp: [[2i64, 0], [0, 1], [1, 0], [0, 0]],
    // K-vector of Im(zeta^k):
    //   Im(zeta^0) = 0            -> [0, 0] / 2
    //   Im(zeta^1) = 1/2          -> [1, 0] / 2
    //   Im(zeta^2) = sqrt(3)/2    -> [0, 1] / 2
    //   Im(zeta^3) = 1            -> [2, 0] / 2
    im_decomp: [[0i64, 0], [1, 0], [0, 1], [2, 0]],
    cartesian: ZZ12_CARTESIAN,
    params: ZZ12_PARAMS,
    // The real-subring element `1` against {sqrt(1), sqrt(3)} with the
    // implicit /2 denominator: 1 = (2 + 0*sqrt(3)) / 2, so the K-vector
    // before the /2 normalization is [2, 0].
    one_in_real_basis: [2i64, 0],
    display_fn: zz12_display,
    complex64_fn: zz12_complex64,
    has: [HasZZ4Impl, HasZZ6Impl, HasZZ12Impl],
}

impl From<(i64, i64)> for ZZ12 {
    /// `(re, im)` where `i = zeta^3`, so `(a, b) = a + b*i = a + b*zeta^3`.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        Self::from_int_coeffs([re, 0, 0, im])
    }
}

// ----------------
// Hand-rolled ZZ12 `Mul` and `Conj` -- the inner two hot helpers in the
// rat_enum hot path. ZZ12-specific polynomial expansions below substantially
// outperform the generic `mul_basis` / `conj_basis` engines (`mul_basis`
// allocates a 32-slot scratch, has two folding loops; `conj_basis` indirects
// through a OnceLock-cached matrix). Step 2 perf measurement showed these
// two specializations together close ~ all of the regression vs the
// pre-port hand-written ZZ12.

impl std::ops::Mul<ZZ12> for ZZ12 {
    type Output = Self;
    /// Multiplication in the integral cyclotomic basis `{1, zeta, zeta^2, zeta^3}`,
    /// using `Phi_12(x) = x^4 - x^2 + 1`, so `zeta^4 = zeta^2 - 1`,
    /// `zeta^5 = zeta^3 - zeta`, `zeta^6 = -1`.
    ///
    /// For `x = (a, b, c, d)` and `y = (e, f, g, h)`:
    ///
    /// ```text
    ///   result_0 = ae - bh - cg - df - dh
    ///   result_1 = af + be - ch - dg
    ///   result_2 = ag + bf + ce + bh + cg + df
    ///   result_3 = ah + bg + cf + de + ch + dg
    /// ```
    #[inline]
    fn mul(self, other: Self) -> Self {
        let [a, b, c, d] = self.int_coeffs();
        let [e, f, g, h] = other.int_coeffs();
        let r0 = a * e - b * h - c * g - d * f - d * h;
        let r1 = a * f + b * e - c * h - d * g;
        let r2 = a * g + b * f + c * e + b * h + c * g + d * f;
        let r3 = a * h + b * g + c * f + d * e + c * h + d * g;
        Self::from_int_coeffs([r0, r1, r2, r3])
    }
}

impl crate::cyclotomic::Conj for ZZ12 {
    /// Conjugation in `{1, zeta, zeta^2, zeta^3}`:
    ///
    /// `conj(zeta) = zeta^11 = zeta - zeta^3`  ->  `(0,  1, 0, -1)`
    /// `conj(zeta^2) = zeta^10 = 1 - zeta^2`   ->  `(1,  0, -1, 0)`
    /// `conj(zeta^3) = zeta^9 = -zeta^3`        ->  `(0, 0, 0, -1)`
    ///
    /// So `conj((a, b, c, d)) = (a + c, b, -c, -b - d)`.
    #[inline]
    fn conj(&self) -> Self {
        let [a, b, c, d] = self.int_coeffs();
        Self::from_int_coeffs([a + c, b, -c, -b - d])
    }
}

impl crate::cyclotomic::Units for ZZ12 {
    /// Static-baked `zeta^k` lookup for `k` in `0..12`. Avoids the OnceLock
    /// + Vec indirection of the generic `derive_units_lookup` path.
    #[inline]
    fn unit(angle: i8) -> Self {
        static UNIT_TABLE: [[i64; 4]; 12] = [
            [1, 0, 0, 0],  // 1
            [0, 1, 0, 0],  // zeta
            [0, 0, 1, 0],  // zeta^2
            [0, 0, 0, 1],  // zeta^3 = i
            [-1, 0, 1, 0], // zeta^4 = zeta^2 - 1
            [0, -1, 0, 1], // zeta^5 = zeta^3 - zeta
            [-1, 0, 0, 0], // zeta^6 = -1
            [0, -1, 0, 0], // zeta^7
            [0, 0, -1, 0], // zeta^8
            [0, 0, 0, -1], // zeta^9
            [1, 0, -1, 0], // zeta^10
            [0, 1, 0, -1], // zeta^11
        ];
        let idx = angle.rem_euclid(12) as usize;
        Self::from_int_coeffs(UNIT_TABLE[idx])
    }
}

// ----------------
// Hand-rolled ZZ12 hot-path overrides.
//
// These three impls (`ReImSign`, `WithinRadius`, `IntersectUnitSegments`)
// are the perf-critical surface in `rat_enum`. The generic
// `integral_basis::*` helpers are correct, but the per-ring specialization
// here exploits ZZ12-specific symbolic structure (the basis being
// `{sqrt(1), sqrt(3)}` with implicit /2) to:
//
//   * read `Re`/`Im` components inline as `(2a + c, b)` / `(b + 2d, c)`,
//     skipping the K-vector projection and decomposition-table lookup;
//   * compare squared norms in pure i64 arithmetic (no Complex64);
//   * route `intersect_unit_segments` through the original 3-multiplication
//     ZZ12 fast path that consumed `im_components` directly off each product.
//
// The matching `impl_integral_re_im_sign_via_basis!` /
// `impl_integral_intersect_unit_segments_via_basis!` /
// `impl_integral_within_radius_via_complex64!` macros are available for
// other rings to opt into the generic path with one line each.

/// Sign of `m + n*sqrt(3)` where m, n are i64. Returns -1, 0, or 1.
///
/// Cheap cases (one zero, both same sign) resolve without multiplication;
/// mixed-sign case compares `m^2` vs `3 * n^2`.
#[inline]
fn sign_m_plus_n_sqrt3(m: i64, n: i64) -> i8 {
    if m == 0 && n == 0 {
        return 0;
    }
    if m >= 0 && n >= 0 {
        return 1;
    }
    if m <= 0 && n <= 0 {
        return -1;
    }
    // Mixed signs.
    let m_sq = m
        .checked_mul(m)
        .expect("ZZ12 sign_m_plus_n_sqrt3 overflow: m*m");
    let n_sq = n
        .checked_mul(n)
        .expect("ZZ12 sign_m_plus_n_sqrt3 overflow: n*n");
    let three_n_sq = 3i64
        .checked_mul(n_sq)
        .expect("ZZ12 sign_m_plus_n_sqrt3 overflow: 3*n*n");
    if m > 0 {
        match m_sq.cmp(&three_n_sq) {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        }
    } else {
        match three_n_sq.cmp(&m_sq) {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        }
    }
}

impl crate::cyclotomic::ReImSign for ZZ12 {
    /// `Re(z) = ((2a + c) + b*sqrt(3)) / 2`, denominator positive, so the
    /// sign reduces to `sign((2a + c) + b*sqrt(3))`.
    #[inline]
    fn re_sign(&self) -> i8 {
        let [a, b, c, _] = self.int_coeffs();
        sign_m_plus_n_sqrt3(2 * a + c, b)
    }

    /// `Im(z) = ((b + 2d) + c*sqrt(3)) / 2`.
    #[inline]
    fn im_sign(&self) -> i8 {
        let [_, b, c, d] = self.int_coeffs();
        sign_m_plus_n_sqrt3(b + 2 * d, c)
    }
}

impl crate::cyclotomic::WithinRadius for ZZ12 {
    /// Pure-i64 squared-norm comparison.
    ///
    /// For `z = (a, b, c, d)`:
    /// `|z|^2 = (M + N*sqrt(3)) / 4` with
    ///   M = (2a + c)^2 + 3*b^2 + (b + 2d)^2 + 3*c^2
    ///   N = 2 * ((2a + c)*b + (b + 2d)*c)
    ///
    /// `|z|^2 <= radius^2` iff `sign_m_plus_n_sqrt3(M - 4*r^2, N) <= 0`.
    #[inline]
    fn within_radius(&self, radius: i64) -> bool {
        let [a, b, c, d] = self.int_coeffs();
        let s = 2 * a + c;
        let t = b + 2 * d;
        let m = s * s + 3 * b * b + t * t + 3 * c * c;
        let n = 2 * (s * b + t * c);
        let four_r_sq = 4 * radius * radius;
        sign_m_plus_n_sqrt3(m - four_r_sq, n) <= 0
    }
}

/// Imaginary-part components of a ZZ12 value `z = (a, b, c, d)`:
/// `Im(z) = (im_m + im_n * sqrt(3)) / 2` where `im_m = b + 2*d`, `im_n = c`.
#[inline]
fn im_components(coeffs: &[i64; 4]) -> (i64, i64) {
    let [_, b, c, d] = *coeffs;
    (b + 2 * d, c)
}

/// Real-part components of a ZZ12 value `z = (a, b, c, d)`:
/// `Re(z) = (re_m + re_n * sqrt(3)) / 2` where `re_m = 2*a + c`, `re_n = b`.
#[inline]
fn re_components(coeffs: &[i64; 4]) -> (i64, i64) {
    let [a, b, c, _] = *coeffs;
    (2 * a + c, b)
}

impl crate::cyclotomic::IntersectUnitSegments for ZZ12 {
    /// 3-multiplication pure-i64 fast path that exploits the unit-length
    /// structure of both input segments. See `zz12.rs` history for the
    /// full math derivation; the shape is identical to the generic
    /// `intersect_unit_segments_basis` but inlines `Re`/`Im` component
    /// extraction off each multiplication result.
    #[inline]
    fn intersect_unit_segments(s1: &(ZZ12, ZZ12), s2: &(ZZ12, ZZ12)) -> bool {
        use crate::cyclotomic::Conj;

        let (a, b) = *s1;
        let (c, d) = *s2;

        // Touching endpoints do not count as a proper intersection.
        if a == c || a == d || b == c || b == d {
            return false;
        }

        let u_a = b - a;
        let u_b = d - c;
        let delta = c - a;

        // ZZ12 mul #1: K = wedge(uA, uB).
        let k_z = u_a.conj() * u_b;
        let (k_m, k_n) = im_components(&k_z.int_coeffs());
        let sign_k = sign_m_plus_n_sqrt3(k_m, k_n);

        // ZZ12 mul #2: V = wedge(uA, delta) (Im(v_z)). We also reuse Re(v_z)
        // = dot(uA, delta) for the inline colinear-overlap test below.
        let v_z = u_a.conj() * delta;
        let (v_m, v_n) = im_components(&v_z.int_coeffs());
        let sign_v = sign_m_plus_n_sqrt3(v_m, v_n);

        if sign_k == 0 {
            if sign_v != 0 {
                return false;
            }
            // Colinear. T = Re(v_z) = dot(uA, delta).
            let (t_m, t_n) = re_components(&v_z.int_coeffs());
            let k_coeffs = k_z.int_coeffs();
            debug_assert_eq!([k_coeffs[1], k_coeffs[2], k_coeffs[3]], [0, 0, 0]);
            if k_coeffs[0] == 1 {
                // uA == uB. Interior overlap iff -1 < T < 1.
                return sign_m_plus_n_sqrt3(t_m + 2, t_n) > 0
                    && sign_m_plus_n_sqrt3(t_m - 2, t_n) < 0;
            } else {
                debug_assert_eq!(k_coeffs[0], -1);
                // uA == -uB. Interior overlap iff 0 < T < 2.
                return sign_m_plus_n_sqrt3(t_m, t_n) > 0
                    && sign_m_plus_n_sqrt3(t_m - 4, t_n) < 0;
            }
        }

        // Non-colinear case.
        let sign_v_plus_k = sign_m_plus_n_sqrt3(v_m + k_m, v_n + k_n);
        if (sign_v > 0) == (sign_v_plus_k > 0) {
            return false;
        }

        // ZZ12 mul #3: W = wedge(delta, uB).
        let (w_m, w_n) = im_components(&(delta.conj() * u_b).int_coeffs());
        let sign_w = sign_m_plus_n_sqrt3(w_m, w_n);
        let sign_w_minus_k = sign_m_plus_n_sqrt3(w_m - k_m, w_n - k_n);
        (sign_w > 0) != (sign_w_minus_k > 0)
    }
}

// ----------------
// Generic algebraic / cyclotomic-structure test suite for ZZ12.
//
// Emits a sibling `zz12_generic_ring_tests` module of ~25 ring-axiom
// tests. The ring-specific `mod tests` below stays for ZZ12-only checks
// (Display format, specific value assertions).
crate::zz_integral_ring_tests!(name: ZZ12);

// ----------------
// ZZ24 -- digiclock integers Z[zeta_24].
//
// `zeta = e^(2*pi*i/24) = cos(15) + i*sin(15)`, `Phi_24(x) = x^8 - x^4 + 1`,
// so `zeta^8 = zeta^4 - 1`. Storage: `[i64; 8]` over
// `{1, zeta, zeta^2, ..., zeta^7}`. The real subring is
// `Z[sqrt(2), sqrt(3), sqrt(6)]` (K = 4, basis `{1, sqrt(2), sqrt(3), sqrt(6)}`)
// with `/4` implicit denominator on the decomposition tables.
//
// All real-sign extraction is exact via `signum_sum_sqrt_expr_4(a, 1, b, 2,
// c, 3, d, 6)` -- both `m = 2` and `n = 3` are integer constants and
// `l = m*n = 6`, so the algebraic identity holds.

/// Symbolic-projection `complex64` for ZZ24.
///
/// Computes `Re(z)` and `Im(z)` by first projecting the integer-basis vector
/// `(a, b, c, d, e, f, g, h)` to a K-vector against `{1, sqrt(2), sqrt(3),
/// sqrt(6)}`, then evaluating each term as `coeff * sqrt(N)` in `f64` and
/// dividing by the implicit `4` denominator. This preserves the bit-exact
/// equalities asserted by `cyclotomic::constants::tests::test_constants`
/// (e.g. `sqrt2::<ZZ24>().complex64().re == f64::sqrt(2.0)`).
#[inline]
fn zz24_complex64(coeffs: &[i64; 8]) -> Complex64 {
    let [a, b, c, d, e, f_, g, h] = *coeffs;
    let (a, b, c, d, e, f_, g, h) = (
        a as f64, b as f64, c as f64, d as f64, e as f64, f_ as f64, g as f64, h as f64,
    );
    let sqrt2 = std::f64::consts::SQRT_2;
    let sqrt3 = 3.0_f64.sqrt();
    let sqrt6 = 6.0_f64.sqrt();
    // Re K-vector (scaled by 4): coefficients of {1, sqrt(2), sqrt(3), sqrt(6)}.
    let r0 = 4.0 * a + 2.0 * e;
    let r1 = b + 2.0 * d - f_ + h;
    let r2 = 2.0 * c;
    let r3 = b + f_ - h;
    let re = (r0 + r1 * sqrt2 + r2 * sqrt3 + r3 * sqrt6) * 0.25;
    // Im K-vector (scaled by 4).
    let i0 = 2.0 * c + 4.0 * g;
    let i1 = -b + 2.0 * d + f_ + h;
    let i2 = 2.0 * e;
    let i3 = b + f_ + h;
    let im = (i0 + i1 * sqrt2 + i2 * sqrt3 + i3 * sqrt6) * 0.25;
    Complex64::new(re, im)
}

const ZZ24_CARTESIAN: [Complex64; 8] = {
    const COS_15: f64 = 0.9659258262890683;
    const SIN_15: f64 = 0.25881904510252074;
    const HALF_SQRT_3: f64 = 0.8660254037844386;
    const HALF_SQRT_2: f64 = std::f64::consts::SQRT_2 * 0.5;
    [
        Complex64::new(1.0, 0.0),
        Complex64::new(COS_15, SIN_15),
        Complex64::new(HALF_SQRT_3, 0.5),
        Complex64::new(HALF_SQRT_2, HALF_SQRT_2),
        Complex64::new(0.5, HALF_SQRT_3),
        Complex64::new(SIN_15, COS_15),
        Complex64::new(0.0, 1.0),
        Complex64::new(-SIN_15, COS_15),
    ]
};

/// Display impl for ZZ24: project `(a..h)` back to GaussInt-Ratio coefficients
/// of `{sqrt(1), sqrt(2), sqrt(3), sqrt(6)}` (the symbolic basis the legacy
/// `impl_symnum_display` consumed).
fn zz24_display(coeffs: &[i64; 8], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let [a, b, c, d, e, f_, g, h] = *coeffs;
    let quarter = Ratio::<i64>::new_raw(1, 4);
    // Coeffs of sqrt(1), sqrt(2), sqrt(3), sqrt(6), each with real and imag
    // parts (everything scaled by 4 to share the implicit denominator).
    let c0 = GaussInt::new(
        Ratio::<i64>::from_integer(4 * a + 2 * e) * quarter,
        Ratio::<i64>::from_integer(2 * c + 4 * g) * quarter,
    );
    let c1 = GaussInt::new(
        Ratio::<i64>::from_integer(b + 2 * d - f_ + h) * quarter,
        Ratio::<i64>::from_integer(-b + 2 * d + f_ + h) * quarter,
    );
    let c2 = GaussInt::new(
        Ratio::<i64>::from_integer(2 * c) * quarter,
        Ratio::<i64>::from_integer(2 * e) * quarter,
    );
    let c3 = GaussInt::new(
        Ratio::<i64>::from_integer(b + f_ - h) * quarter,
        Ratio::<i64>::from_integer(b + f_ + h) * quarter,
    );
    format_symbolic(&[c0, c1, c2, c3], &["1", "2", "3", "6"], f)
}

/// Sign of `a + b*sqrt(2) + c*sqrt(3) + d*sqrt(6)` for integers `a, b, c, d`,
/// exact via `signum_sum_sqrt_expr_4` (closed-form algebraic comparison since
/// `2`, `3`, `6 = 2*3` are all integer constants).
#[inline]
fn zz24_real_sign(x: &[i64; 4]) -> i8 {
    crate::cyclotomic::sign::signum_sum_sqrt_expr_4::<i64>(x[0], 1, x[1], 2, x[2], 3, x[3], 6) as i8
}

define_integral_zz! {
    name: ZZ24,
    n: 24,
    phi: 8,
    real_dim: 4,
    // Phi_24(x) = x^8 - x^4 + 1, so zeta^8 = zeta^4 - 1.
    reduction: [-1i64, 0, 0, 0, 1, 0, 0, 0],
    // Re(zeta^k) in basis {1, sqrt(2), sqrt(3), sqrt(6)} with implicit /4:
    //   Re(zeta^0) = 1            -> [4, 0, 0, 0]
    //   Re(zeta^1) = cos(15)      -> [0, 1, 0, 1]   (= (sqrt(6)+sqrt(2))/4)
    //   Re(zeta^2) = cos(30)      -> [0, 0, 2, 0]   (= sqrt(3)/2)
    //   Re(zeta^3) = cos(45)      -> [0, 2, 0, 0]   (= sqrt(2)/2)
    //   Re(zeta^4) = cos(60)      -> [2, 0, 0, 0]   (= 1/2)
    //   Re(zeta^5) = cos(75)      -> [0, -1, 0, 1]  (= (sqrt(6)-sqrt(2))/4)
    //   Re(zeta^6) = cos(90)      -> [0, 0, 0, 0]
    //   Re(zeta^7) = cos(105)     -> [0, 1, 0, -1]  (= (sqrt(2)-sqrt(6))/4)
    re_decomp: [
        [4i64, 0, 0, 0], [0, 1, 0, 1], [0, 0, 2, 0], [0, 2, 0, 0],
        [2, 0, 0, 0], [0, -1, 0, 1], [0, 0, 0, 0], [0, 1, 0, -1],
    ],
    // Im(zeta^k):
    //   Im(zeta^0) = 0
    //   Im(zeta^1) = sin(15)      -> [0, -1, 0, 1]  (= (sqrt(6)-sqrt(2))/4)
    //   Im(zeta^2) = sin(30)      -> [2, 0, 0, 0]   (= 1/2)
    //   Im(zeta^3) = sin(45)      -> [0, 2, 0, 0]   (= sqrt(2)/2)
    //   Im(zeta^4) = sin(60)      -> [0, 0, 2, 0]   (= sqrt(3)/2)
    //   Im(zeta^5) = sin(75)      -> [0, 1, 0, 1]   (= (sqrt(6)+sqrt(2))/4)
    //   Im(zeta^6) = sin(90)      -> [4, 0, 0, 0]   (= 1)
    //   Im(zeta^7) = sin(105)     -> [0, 1, 0, 1]   (= (sqrt(6)+sqrt(2))/4)
    im_decomp: [
        [0i64, 0, 0, 0], [0, -1, 0, 1], [2, 0, 0, 0], [0, 2, 0, 0],
        [0, 0, 2, 0], [0, 1, 0, 1], [4, 0, 0, 0], [0, 1, 0, 1],
    ],
    cartesian: ZZ24_CARTESIAN,
    params: ZZ24_PARAMS,
    // `1` in basis {1, sqrt(2), sqrt(3), sqrt(6)} with /4 denominator.
    one_in_real_basis: [4i64, 0, 0, 0],
    display_fn: zz24_display,
    complex64_fn: zz24_complex64,
    has: [HasZZ4Impl, HasZZ6Impl, HasZZ8Impl, HasZZ12Impl],
}

impl From<(i64, i64)> for ZZ24 {
    /// `(re, im)` where `i = zeta^6`, so `(a, b) = a + b*i` maps to
    /// integer-basis coefficients `[a, 0, 0, 0, 0, 0, b, 0]`.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        Self::from_int_coeffs([re, 0, 0, 0, 0, 0, im, 0])
    }
}

crate::impl_integral_units_via_basis!(ZZ24, 24);
crate::impl_integral_mul_via_basis!(ZZ24, 8);
crate::impl_integral_conj_via_basis!(ZZ24, 8);
crate::impl_integral_re_im_sign_via_basis!(ZZ24, 8, 4, zz24_real_sign);
crate::impl_integral_intersect_unit_segments_via_basis!(ZZ24, 8, 4, zz24_real_sign);
crate::impl_integral_within_radius_via_complex64!(ZZ24);
crate::zz_integral_ring_tests!(name: ZZ24);

// ----------------
// ZZ20 -- penrose integers Z[zeta_20].
//
// `zeta = e^(2*pi*i/20) = cos(18) + i*sin(18)`, `Phi_20(x) = x^8 - x^6 +
// x^4 - x^2 + 1`, so `zeta^8 = zeta^6 - zeta^4 + zeta^2 - 1`. Storage:
// `[i64; 8]` over `{1, zeta, ..., zeta^7}`. The real subring is
// `Z[sqrt(5), sqrt(10 - 2*sqrt(5))]` (K = 4, basis
// `{1, sqrt(5), sqrt(10-2*sqrt(5)), sqrt(5(10-2*sqrt(5)))}`) with `/8`
// implicit denominator.
//
// Real-sign extraction is exact via the pentagonal closed-form
// `signum_sum_sqrt_expr_4_pentagonal`. Note the basis includes
// `b3 = sqrt(5)*b2` (not the more general `sqrt(m*n)`-shape ZZ24 has).
//
// Useful identity:
//   sqrt(10 + 2*sqrt(5)) = (1 + sqrt(5)) * sqrt(10 - 2*sqrt(5)) / 2
//                       = (b2 + b3) / 2
// which is how cos(18), cos(54), sin(72), sin(108) all reduce to the
// `{b2, b3}` subspace.

/// Symbolic-projection `complex64` for ZZ20. Mirrors ZZ24's approach but
/// reads the per-ring sqrt values from `ZZ10_Y` (the params constant for
/// `2*(5 - sqrt(5))`), matching the legacy `complex64` path so the
/// `cyclotomic::constants::tests::test_constants` bit-exact assertions
/// (sqrt5, half_sqrt_penta) round-trip identically.
#[inline]
fn zz20_complex64(coeffs: &[i64; 8]) -> Complex64 {
    let [a, b, c, d, e, f_, g, h] = *coeffs;
    let (a, b, c, d, e, f_, g, h) = (
        a as f64, b as f64, c as f64, d as f64, e as f64, f_ as f64, g as f64, h as f64,
    );
    let sq5 = 5.0_f64.sqrt();
    let sq_y = ZZ10_Y.sqrt();
    let sq_5y = (5.0 * ZZ10_Y).sqrt();
    // Re K-vector (scaled by 8) in basis {1, sqrt(5), sqrt(10-2*sqrt(5)),
    // sqrt(5*(10-2*sqrt(5)))}.
    let r0 = 8.0 * a + 2.0 * c - 2.0 * e + 2.0 * g;
    let r1 = 2.0 * c + 2.0 * e - 2.0 * g;
    let r2 = b + 2.0 * d - 2.0 * h;
    let r3 = b;
    let re = (r0 + r1 * sq5 + r2 * sq_y + r3 * sq_5y) * 0.125;
    // Im K-vector (scaled by 8).
    let i0 = -2.0 * b + 2.0 * d + 8.0 * f_ + 2.0 * h;
    let i1 = 2.0 * b + 2.0 * d + 2.0 * h;
    let i2 = 2.0 * c + e + g;
    let i3 = e + g;
    let im = (i0 + i1 * sq5 + i2 * sq_y + i3 * sq_5y) * 0.125;
    Complex64::new(re, im)
}

const ZZ20_CARTESIAN: [Complex64; 8] = {
    // Cached so the unused `CARTESIAN` const has reasonable values for
    // debugging. Not on any hot path (`complex64_fn` is hand-rolled above).
    const COS_18: f64 = 0.9510565162951535;
    const SIN_18: f64 = 0.30901699437494745;
    const COS_36: f64 = 0.8090169943749475;
    const SIN_36: f64 = 0.5877852522924731;
    const COS_54: f64 = 0.5877852522924731;
    const SIN_54: f64 = 0.8090169943749475;
    const COS_72: f64 = 0.30901699437494745;
    const SIN_72: f64 = 0.9510565162951535;
    [
        Complex64::new(1.0, 0.0),
        Complex64::new(COS_18, SIN_18),
        Complex64::new(COS_36, SIN_36),
        Complex64::new(COS_54, SIN_54),
        Complex64::new(COS_72, SIN_72),
        Complex64::new(0.0, 1.0),
        Complex64::new(-COS_72, SIN_72),
        Complex64::new(-COS_54, SIN_54),
    ]
};

/// Display impl for ZZ20: project `(a..h)` to GaussInt-Ratio coefficients of
/// `{sqrt(1), sqrt(5), sqrt(2(5-sqrt(5))), sqrt(10(5-sqrt(5)))}` (the symbolic
/// labels from the legacy `ZZ20_PARAMS`).
fn zz20_display(coeffs: &[i64; 8], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let [a, b, c, d, e, f_, g, h] = *coeffs;
    let eighth = Ratio::<i64>::new_raw(1, 8);
    let c0 = GaussInt::new(
        Ratio::<i64>::from_integer(8 * a + 2 * c - 2 * e + 2 * g) * eighth,
        Ratio::<i64>::from_integer(-2 * b + 2 * d + 8 * f_ + 2 * h) * eighth,
    );
    let c1 = GaussInt::new(
        Ratio::<i64>::from_integer(2 * c + 2 * e - 2 * g) * eighth,
        Ratio::<i64>::from_integer(2 * b + 2 * d + 2 * h) * eighth,
    );
    let c2 = GaussInt::new(
        Ratio::<i64>::from_integer(b + 2 * d - 2 * h) * eighth,
        Ratio::<i64>::from_integer(2 * c + e + g) * eighth,
    );
    let c3 = GaussInt::new(
        Ratio::<i64>::from_integer(b) * eighth,
        Ratio::<i64>::from_integer(e + g) * eighth,
    );
    format_symbolic(
        &[c0, c1, c2, c3],
        &["1", "5", "2(5-sqrt(5))", "10(5-sqrt(5))"],
        f,
    )
}

/// Sign of `a + b*sqrt(5) + c*sqrt(10-2*sqrt(5)) + d*sqrt(5*(10-2*sqrt(5)))`
/// via the closed-form `signum_sum_sqrt_expr_4_pentagonal` (recursive
/// reduction from `Q(sqrt(5), sqrt(10-2*sqrt(5)))` to `Q(sqrt(5))`).
#[inline]
fn zz20_real_sign(x: &[i64; 4]) -> i8 {
    crate::cyclotomic::sign::signum_sum_sqrt_expr_4_pentagonal::<i64>(x[0], x[1], x[2], x[3]) as i8
}

define_integral_zz! {
    name: ZZ20,
    n: 20,
    phi: 8,
    real_dim: 4,
    // Phi_20(x) = x^8 - x^6 + x^4 - x^2 + 1, so zeta^8 = zeta^6 - zeta^4 + zeta^2 - 1.
    reduction: [-1i64, 0, 1, 0, -1, 0, 1, 0],
    // Re(zeta^k) in basis {1, sqrt(5), b2, b3} with implicit /8, where
    //   b2 = sqrt(10 - 2*sqrt(5)),   b3 = sqrt(5)*b2 = sqrt(5*(10-2*sqrt(5))).
    //
    // Useful identity: sqrt(10 + 2*sqrt(5)) = (b2 + b3) / 2, so e.g.
    //   cos(18) = sqrt(10+2*sqrt(5))/4 = (b2 + b3) / 8 -> [0, 0, 1, 1].
    //
    //   Re(zeta^0) = 1                          -> [8, 0, 0, 0]
    //   Re(zeta^1) = cos(18)  = (b2 + b3)/8     -> [0, 0, 1, 1]
    //   Re(zeta^2) = cos(36)  = (1+sqrt(5))/4   -> [2, 2, 0, 0]
    //   Re(zeta^3) = cos(54)  = b2 / 4          -> [0, 0, 2, 0]
    //   Re(zeta^4) = cos(72)  = (sqrt(5)-1)/4   -> [-2, 2, 0, 0]
    //   Re(zeta^5) = cos(90)  = 0               -> [0, 0, 0, 0]
    //   Re(zeta^6) = cos(108) = (1-sqrt(5))/4   -> [2, -2, 0, 0]
    //   Re(zeta^7) = cos(126) = -b2 / 4         -> [0, 0, -2, 0]
    re_decomp: [
        [8i64, 0, 0, 0], [0, 0, 1, 1], [2, 2, 0, 0], [0, 0, 2, 0],
        [-2, 2, 0, 0], [0, 0, 0, 0], [2, -2, 0, 0], [0, 0, -2, 0],
    ],
    // Im(zeta^k):
    //   Im(zeta^0) = 0
    //   Im(zeta^1) = sin(18)  = (sqrt(5)-1)/4   -> [-2, 2, 0, 0]
    //   Im(zeta^2) = sin(36)  = b2 / 4          -> [0, 0, 2, 0]
    //   Im(zeta^3) = sin(54)  = (1+sqrt(5))/4   -> [2, 2, 0, 0]
    //   Im(zeta^4) = sin(72)  = (b2 + b3)/8     -> [0, 0, 1, 1]
    //   Im(zeta^5) = sin(90)  = 1               -> [8, 0, 0, 0]
    //   Im(zeta^6) = sin(108) = (b2 + b3)/8     -> [0, 0, 1, 1]
    //   Im(zeta^7) = sin(126) = (1+sqrt(5))/4   -> [2, 2, 0, 0]
    im_decomp: [
        [0i64, 0, 0, 0], [-2, 2, 0, 0], [0, 0, 2, 0], [2, 2, 0, 0],
        [0, 0, 1, 1], [8, 0, 0, 0], [0, 0, 1, 1], [2, 2, 0, 0],
    ],
    cartesian: ZZ20_CARTESIAN,
    params: ZZ20_PARAMS,
    // `1` in basis {1, sqrt(5), b2, b3} with /8 denominator.
    one_in_real_basis: [8i64, 0, 0, 0],
    display_fn: zz20_display,
    complex64_fn: zz20_complex64,
    has: [HasZZ4Impl, HasZZ10Impl],
}

impl From<(i64, i64)> for ZZ20 {
    /// `(re, im)` where `i = zeta^5`, so `(a, b) = a + b*i` maps to
    /// integer-basis coefficients `[a, 0, 0, 0, 0, b, 0, 0]`.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        Self::from_int_coeffs([re, 0, 0, 0, 0, im, 0, 0])
    }
}

crate::impl_integral_units_via_basis!(ZZ20, 20);
crate::impl_integral_mul_via_basis!(ZZ20, 8);
crate::impl_integral_conj_via_basis!(ZZ20, 8);
crate::impl_integral_re_im_sign_via_basis!(ZZ20, 8, 4, zz20_real_sign);
crate::impl_integral_intersect_unit_segments_via_basis!(ZZ20, 8, 4, zz20_real_sign);
crate::impl_integral_within_radius_via_complex64!(ZZ20);
crate::zz_integral_ring_tests!(name: ZZ20);

// ----------------
// ZZ10 -- halfrose integers Z[zeta_10].
//
// `zeta = e^(2*pi*i/10) = cos(36) + i*sin(36)`, `Phi_10(x) = x^4 - x^3 +
// x^2 - x + 1`, so `zeta^4 = zeta^3 - zeta^2 + zeta - 1`. Storage:
// `[i64; 4]` over `{1, zeta, zeta^2, zeta^3}`.
//
// **Not a CM field with `i`.** `zeta_4 = i` is not in `Q(zeta_10)` (since
// `4 \nmid 10`), so `Re(z)` and `Im(z)` for `z` in the integer basis live
// in different `Q`-subspaces of `R`:
//   Re(z) in `Q(sqrt(5))`                                       (dim 2)
//   Im(z) in `Q(sqrt(5)) * sqrt(10-2*sqrt(5))`                  (dim 2)
//
// We unify them with `K = 4` over basis `{1, sqrt(5), b2, b3}` where
// `b2 = sqrt(10 - 2*sqrt(5))` and `b3 = sqrt(5)*b2`, matching the
// existing legacy `ZZ10_PARAMS.sym_roots_sqs`. The `j2`/`j3` columns of
// `re_decomp` are always zero, and the `j0`/`j1` columns of `im_decomp`
// are always zero, but the unified shape lets us reuse the exact
// `signum_sum_sqrt_expr_4_pentagonal` from ZZ20.

#[inline]
fn zz10_complex64(coeffs: &[i64; 4]) -> Complex64 {
    let [a, b, c, d] = *coeffs;
    let (a, b, c, d) = (a as f64, b as f64, c as f64, d as f64);
    let sq5 = 5.0_f64.sqrt();
    let sq_y = ZZ10_Y.sqrt();
    let sq_5y = (5.0 * ZZ10_Y).sqrt();
    // Re K-vector (scaled by 8) -- only the `{1, sqrt(5)}` coordinates are
    // ever non-zero.
    let r0 = 8.0 * a + 2.0 * b - 2.0 * c + 2.0 * d;
    let r1 = 2.0 * b + 2.0 * c - 2.0 * d;
    let re = (r0 + r1 * sq5) * 0.125;
    // Im K-vector (scaled by 8) -- only the `{b2, b3}` coordinates are
    // ever non-zero.
    let i2 = 2.0 * b + c + d;
    let i3 = c + d;
    let im = (i2 * sq_y + i3 * sq_5y) * 0.125;
    Complex64::new(re, im)
}

const ZZ10_CARTESIAN: [Complex64; 4] = {
    const COS_36: f64 = 0.8090169943749475;
    const SIN_36: f64 = 0.5877852522924731;
    const COS_72: f64 = 0.30901699437494745;
    const SIN_72: f64 = 0.9510565162951535;
    [
        Complex64::new(1.0, 0.0),
        Complex64::new(COS_36, SIN_36),
        Complex64::new(COS_72, SIN_72),
        Complex64::new(-COS_72, SIN_72),
    ]
};

fn zz10_display(coeffs: &[i64; 4], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let [a, b, c, d] = *coeffs;
    let eighth = Ratio::<i64>::new_raw(1, 8);
    // Each c_k = (Re_part + Im_part * i) / 8.
    let c0 = GaussInt::new(
        Ratio::<i64>::from_integer(8 * a + 2 * b - 2 * c + 2 * d) * eighth,
        Ratio::<i64>::from_integer(0) * eighth,
    );
    let c1 = GaussInt::new(
        Ratio::<i64>::from_integer(2 * b + 2 * c - 2 * d) * eighth,
        Ratio::<i64>::from_integer(0) * eighth,
    );
    let c2 = GaussInt::new(
        Ratio::<i64>::from_integer(0) * eighth,
        Ratio::<i64>::from_integer(2 * b + c + d) * eighth,
    );
    let c3 = GaussInt::new(
        Ratio::<i64>::from_integer(0) * eighth,
        Ratio::<i64>::from_integer(c + d) * eighth,
    );
    format_symbolic(
        &[c0, c1, c2, c3],
        &["1", "5", "2(5-sqrt(5))", "10(5-sqrt(5))"],
        f,
    )
}

/// Sign of `a + b*sqrt(5) + c*sqrt(10-2*sqrt(5)) + d*sqrt(5*(10-2*sqrt(5)))`
/// via the closed-form `signum_sum_sqrt_expr_4_pentagonal` (same exact
/// reduction as ZZ20). For ZZ10 the `c`/`d` (or `a`/`b`) entries are zero
/// depending on whether the K-vector is from `re_decomp` or `im_decomp`,
/// but the function handles those cases trivially.
#[inline]
fn zz10_real_sign(x: &[i64; 4]) -> i8 {
    crate::cyclotomic::sign::signum_sum_sqrt_expr_4_pentagonal::<i64>(x[0], x[1], x[2], x[3]) as i8
}

define_integral_zz! {
    name: ZZ10,
    n: 10,
    phi: 4,
    real_dim: 4,
    // Phi_10(x) = x^4 - x^3 + x^2 - x + 1, so zeta^4 = zeta^3 - zeta^2 + zeta - 1.
    reduction: [-1i64, 1, -1, 1],
    // Re(zeta^k) in basis {1, sqrt(5), b2, b3} with implicit /8:
    //   Re(zeta^0) = 1                          -> [8, 0, 0, 0]
    //   Re(zeta^1) = cos(36) = (1+sqrt(5))/4    -> [2, 2, 0, 0]
    //   Re(zeta^2) = cos(72) = (sqrt(5)-1)/4    -> [-2, 2, 0, 0]
    //   Re(zeta^3) = cos(108) = (1-sqrt(5))/4   -> [2, -2, 0, 0]
    re_decomp: [
        [8i64, 0, 0, 0], [2, 2, 0, 0], [-2, 2, 0, 0], [2, -2, 0, 0],
    ],
    // Im(zeta^k):
    //   Im(zeta^0) = 0
    //   Im(zeta^1) = sin(36) = b2 / 4           -> [0, 0, 2, 0]
    //   Im(zeta^2) = sin(72) = (b2 + b3)/8      -> [0, 0, 1, 1]
    //   Im(zeta^3) = sin(108) = (b2 + b3)/8     -> [0, 0, 1, 1]
    im_decomp: [
        [0i64, 0, 0, 0], [0, 0, 2, 0], [0, 0, 1, 1], [0, 0, 1, 1],
    ],
    cartesian: ZZ10_CARTESIAN,
    params: ZZ10_PARAMS,
    one_in_real_basis: [8i64, 0, 0, 0],
    display_fn: zz10_display,
    complex64_fn: zz10_complex64,
    has: [HasZZ10Impl],
}

crate::impl_integral_units_via_basis!(ZZ10, 10);
crate::impl_integral_mul_via_basis!(ZZ10, 4);
crate::impl_integral_conj_via_basis!(ZZ10, 4);
crate::impl_integral_re_im_sign_via_basis!(ZZ10, 4, 4, zz10_real_sign);
crate::impl_integral_intersect_unit_segments_via_basis!(ZZ10, 4, 4, zz10_real_sign);
crate::impl_integral_within_radius_via_complex64!(ZZ10);
crate::zz_integral_ring_tests!(name: ZZ10);

// ----------------
// ZZ16 -- hex integers Z[zeta_16].
//
// `zeta = e^(2*pi*i/16) = cos(22.5) + i*sin(22.5)`, `Phi_16(x) = x^8 + 1`,
// so `zeta^8 = -1`. Storage: `[i64; 8]` over `{1, zeta, ..., zeta^7}`. The
// real subring is `Z[sqrt(2), sqrt(2+sqrt(2))]` (K = 4, basis
// `{1, sqrt(2), b3, b4}` with `b3 = sqrt(2+sqrt(2))`, `b4 = sqrt(2)*b3`)
// with `/2` implicit denominator.
//
// Real-sign extraction is **exact** via `signum_sum_sqrt_expr_4_zz16`
// (closed-form reduction from `Q(sqrt(2), sqrt(2+sqrt(2)))` to `Q(sqrt(2))`
// -- same shape as the pentagonal helper, just with `y = 2+sqrt(2)`).
//
// Useful identity for the decomposition tables:
//   sqrt(2 - sqrt(2)) = sqrt(2) * sqrt(2+sqrt(2)) - sqrt(2+sqrt(2))
//                    = b4 - b3
// which expresses sin(22.5), cos(67.5), sin(157.5), etc. in the chosen basis.

#[inline]
fn zz16_complex64(coeffs: &[i64; 8]) -> Complex64 {
    let [a, b, c, d, e, f_, g, h] = *coeffs;
    let (a, b, c, d, e, f_, g, h) = (
        a as f64, b as f64, c as f64, d as f64, e as f64, f_ as f64, g as f64, h as f64,
    );
    let sqrt2 = std::f64::consts::SQRT_2;
    let sq_y = ZZ16_Y.sqrt();
    let sq_2y = (2.0 * ZZ16_Y).sqrt();
    // Re K-vector (scaled by 2) in basis {1, sqrt(2), b3, b4}.
    let r0 = 2.0 * a;
    let r1 = c - g;
    let r2 = b - d + f_ - h;
    let r3 = d - f_;
    let re = (r0 + r1 * sqrt2 + r2 * sq_y + r3 * sq_2y) * 0.5;
    // Im K-vector (scaled by 2).
    let i0 = 2.0 * e;
    let i1 = c + g;
    let i2 = -b + d + f_ - h;
    let i3 = b + h;
    let im = (i0 + i1 * sqrt2 + i2 * sq_y + i3 * sq_2y) * 0.5;
    Complex64::new(re, im)
}

const ZZ16_CARTESIAN: [Complex64; 8] = {
    const COS_22_5: f64 = 0.9238795325112867;
    const SIN_22_5: f64 = 0.3826834323650898;
    const HALF_SQRT_2: f64 = std::f64::consts::SQRT_2 * 0.5;
    [
        Complex64::new(1.0, 0.0),
        Complex64::new(COS_22_5, SIN_22_5),
        Complex64::new(HALF_SQRT_2, HALF_SQRT_2),
        Complex64::new(SIN_22_5, COS_22_5),
        Complex64::new(0.0, 1.0),
        Complex64::new(-SIN_22_5, COS_22_5),
        Complex64::new(-HALF_SQRT_2, HALF_SQRT_2),
        Complex64::new(-COS_22_5, SIN_22_5),
    ]
};

fn zz16_display(coeffs: &[i64; 8], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let [a, b, c, d, e, f_, g, h] = *coeffs;
    let half = Ratio::<i64>::new_raw(1, 2);
    // Each c_k = (Re_part + Im_part * i) / 2 where Re_part and Im_part are
    // the K-vector entries above, scaled by 2.
    let c0 = GaussInt::new(
        Ratio::<i64>::from_integer(2 * a) * half,
        Ratio::<i64>::from_integer(2 * e) * half,
    );
    let c1 = GaussInt::new(
        Ratio::<i64>::from_integer(c - g) * half,
        Ratio::<i64>::from_integer(c + g) * half,
    );
    let c2 = GaussInt::new(
        Ratio::<i64>::from_integer(b - d + f_ - h) * half,
        Ratio::<i64>::from_integer(-b + d + f_ - h) * half,
    );
    let c3 = GaussInt::new(
        Ratio::<i64>::from_integer(d - f_) * half,
        Ratio::<i64>::from_integer(b + h) * half,
    );
    format_symbolic(
        &[c0, c1, c2, c3],
        &["1", "2", "2+sqrt(2)", "2(2+sqrt(2))"],
        f,
    )
}

/// Sign of `a + b*sqrt(2) + c*sqrt(2+sqrt(2)) + d*sqrt(2*(2+sqrt(2)))`
/// via the closed-form `signum_sum_sqrt_expr_4_zz16` (recursive reduction
/// from `Q(sqrt(2), sqrt(2+sqrt(2)))` to `Q(sqrt(2))`).
#[inline]
fn zz16_real_sign(x: &[i64; 4]) -> i8 {
    crate::cyclotomic::sign::signum_sum_sqrt_expr_4_zz16::<i64>(x[0], x[1], x[2], x[3]) as i8
}

define_integral_zz! {
    name: ZZ16,
    n: 16,
    phi: 8,
    real_dim: 4,
    // Phi_16(x) = x^8 + 1, so zeta^8 = -1.
    reduction: [-1i64, 0, 0, 0, 0, 0, 0, 0],
    // Re(zeta^k) in basis {1, sqrt(2), b3, b4} with implicit /2, where
    //   b3 = sqrt(2 + sqrt(2)),   b4 = sqrt(2) * b3 = sqrt(2(2+sqrt(2))).
    //
    // Identity: sqrt(2 - sqrt(2)) = b4 - b3, so e.g.
    //   sin(22.5) = sqrt(2-sqrt(2))/2 = (b4 - b3) / 2 -> [0, 0, -1, 1].
    //
    //   Re(zeta^0) = 1                  -> [2, 0, 0, 0]
    //   Re(zeta^1) = cos(22.5) = b3/2   -> [0, 0, 1, 0]
    //   Re(zeta^2) = cos(45)   = sqrt(2)/2 -> [0, 1, 0, 0]
    //   Re(zeta^3) = cos(67.5) = sin(22.5) = (b4-b3)/2 -> [0, 0, -1, 1]
    //   Re(zeta^4) = cos(90)   = 0      -> [0, 0, 0, 0]
    //   Re(zeta^5) = cos(112.5)= -sin(22.5) = (b3-b4)/2 -> [0, 0, 1, -1]
    //   Re(zeta^6) = cos(135)  = -sqrt(2)/2 -> [0, -1, 0, 0]
    //   Re(zeta^7) = cos(157.5)= -cos(22.5) = -b3/2 -> [0, 0, -1, 0]
    re_decomp: [
        [2i64, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, -1, 1],
        [0, 0, 0, 0], [0, 0, 1, -1], [0, -1, 0, 0], [0, 0, -1, 0],
    ],
    // Im(zeta^k):
    //   Im(zeta^0) = 0
    //   Im(zeta^1) = sin(22.5)  = (b4-b3)/2 -> [0, 0, -1, 1]
    //   Im(zeta^2) = sin(45)    = sqrt(2)/2 -> [0, 1, 0, 0]
    //   Im(zeta^3) = sin(67.5)  = cos(22.5) = b3/2 -> [0, 0, 1, 0]
    //   Im(zeta^4) = sin(90)    = 1 -> [2, 0, 0, 0]
    //   Im(zeta^5) = sin(112.5) = sin(67.5) = b3/2 -> [0, 0, 1, 0]
    //   Im(zeta^6) = sin(135)   = sqrt(2)/2 -> [0, 1, 0, 0]
    //   Im(zeta^7) = sin(157.5) = sin(22.5) = (b4-b3)/2 -> [0, 0, -1, 1]
    im_decomp: [
        [0i64, 0, 0, 0], [0, 0, -1, 1], [0, 1, 0, 0], [0, 0, 1, 0],
        [2, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, -1, 1],
    ],
    cartesian: ZZ16_CARTESIAN,
    params: ZZ16_PARAMS,
    one_in_real_basis: [2i64, 0, 0, 0],
    display_fn: zz16_display,
    complex64_fn: zz16_complex64,
    has: [HasZZ4Impl, HasZZ8Impl],
}

impl From<(i64, i64)> for ZZ16 {
    /// `(re, im)` where `i = zeta^4`, so `(a, b) = a + b*i` maps to
    /// integer-basis coefficients `[a, 0, 0, 0, b, 0, 0, 0]`.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        Self::from_int_coeffs([re, 0, 0, 0, im, 0, 0, 0])
    }
}

crate::impl_integral_units_via_basis!(ZZ16, 16);
crate::impl_integral_mul_via_basis!(ZZ16, 8);
crate::impl_integral_conj_via_basis!(ZZ16, 8);
crate::impl_integral_re_im_sign_via_basis!(ZZ16, 8, 4, zz16_real_sign);
crate::impl_integral_intersect_unit_segments_via_basis!(ZZ16, 8, 4, zz16_real_sign);
crate::impl_integral_within_radius_via_complex64!(ZZ16);
crate::zz_integral_ring_tests!(name: ZZ16);

// ----------------
// ZZ60 -- babylonian integers Z[zeta_60].
//
// `zeta = e^(2*pi*i/60) = cos(6) + i*sin(6)`. `Phi_60(x) = x^16 + x^14 -
// x^10 - x^8 - x^6 + x^2 + 1`, so `zeta^16 = -zeta^14 + zeta^10 + zeta^8
// + zeta^6 - zeta^2 - 1`. Storage: `[i64; 16]` over
// `{1, zeta, ..., zeta^15}`.
//
// The real subring is `Q(sqrt(3), sqrt(5), sqrt(10-2*sqrt(5)))`, dim 8
// over Q, basis:
//   {1, sqrt(3), sqrt(5), sqrt(y), sqrt(15), sqrt(3y), sqrt(5y), sqrt(15y)}
// where `y = 10 - 2*sqrt(5)`, with `/16` implicit denominator (matching
// the legacy `ZZ60_PARAMS.scaling_fac`).
//
// Real-sign extraction is **exact** via `signum_sum_sqrt_expr_8_zz60`
// (closed-form reduction `Q(sqrt(3), sqrt(5), sqrt(y))` -> biquadratic
// `Q(sqrt(3), sqrt(5))`, where `signum_sum_sqrt_expr_4(_, 1, _, 3, _, 5,
// _, 15)` applies exactly since `m * n = l` for `m=3, n=5, l=15`).
//
// The `re_decomp` / `im_decomp` tables were extracted from the legacy
// `ZZ60::unit(k)` (which has matching algebraic structure) via the
// one-shot `codegen_zz60` binary. Their correctness is then verified by
// the generic `complex64_unit_matches_exp` test in the test suite.

#[inline]
fn zz60_complex64(coeffs: &[i64; 16]) -> Complex64 {
    // Symbolic-projection complex64. We project the integer-basis vector
    // to a K-vector in the symbolic basis, then evaluate each component
    // as `c * sqrt(N)` in f64 and divide by the implicit /16. This is the
    // same recipe used by the legacy `complex64` path, so its bit-exact
    // outputs (used by `cyclotomic::constants::tests::test_constants`) are
    // preserved.
    //
    // Internally we just delegate to the generic `re_sign_basis` /
    // `im_sign_basis`-style projection routed through f64 sqrt(N) terms.
    let sq3 = 3.0_f64.sqrt();
    let sq5 = 5.0_f64.sqrt();
    let sq15 = 15.0_f64.sqrt();
    let sqy = ZZ10_Y.sqrt();
    let sq3y = (3.0 * ZZ10_Y).sqrt();
    let sq5y = (5.0 * ZZ10_Y).sqrt();
    let sq15y = (15.0 * ZZ10_Y).sqrt();

    let proj = |table: &[[i64; 8]; 16]| -> f64 {
        let mut acc = [0i64; 8];
        for k in 0..16 {
            let ck = coeffs[k];
            if ck == 0 {
                continue;
            }
            for j in 0..8 {
                acc[j] += ck * table[k][j];
            }
        }
        (acc[0] as f64
            + (acc[1] as f64) * sq3
            + (acc[2] as f64) * sq5
            + (acc[3] as f64) * sqy
            + (acc[4] as f64) * sq15
            + (acc[5] as f64) * sq3y
            + (acc[6] as f64) * sq5y
            + (acc[7] as f64) * sq15y)
            / 16.0
    };
    let re = proj(&ZZ60_RE_DECOMP);
    let im = proj(&ZZ60_IM_DECOMP);
    Complex64::new(re, im)
}

const ZZ60_CARTESIAN: [Complex64; 16] = {
    // Cached f64 cos/sin pairs for zeta^k = exp(2*pi*i*k/60). Unused at
    // runtime (complex64_fn projects symbolically) but kept as the macro
    // requires a `[Complex64; PHI]` const.
    const fn placeholder() -> Complex64 {
        Complex64::new(0.0, 0.0)
    }
    let mut out = [placeholder(); 16];
    // We cannot call `.cos()` in const context, so leave all-zero. The
    // values are recomputed every call in zz60_complex64.
    out[0] = Complex64::new(1.0, 0.0);
    out
};

// Decomposition tables. Auto-generated from legacy ZZ60 via
// `src/bin/codegen_zz60.rs`.
const ZZ60_RE_DECOMP: [[i64; 8]; 16] = [
    [16, 0, 0, 0, 0, 0, 0, 0],
    [0, 2, 0, 2, 2, 0, 0, 0],
    [-2, 0, 2, 0, 0, 1, 0, 1],
    [0, 0, 0, 2, 0, 0, 2, 0],
    [2, 0, 2, 0, 0, 2, 0, 0],
    [0, 8, 0, 0, 0, 0, 0, 0],
    [4, 0, 4, 0, 0, 0, 0, 0],
    [0, -2, 0, 1, 2, 0, 1, 0],
    [2, 0, -2, 0, 0, 1, 0, 1],
    [0, 0, 0, 4, 0, 0, 0, 0],
    [8, 0, 0, 0, 0, 0, 0, 0],
    [0, 2, 0, -2, 2, 0, 0, 0],
    [-4, 0, 4, 0, 0, 0, 0, 0],
    [0, 2, 0, 1, -2, 0, 1, 0],
    [-2, 0, -2, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
];

const ZZ60_IM_DECOMP: [[i64; 8]; 16] = [
    [0, 0, 0, 0, 0, 0, 0, 0],
    [-2, 0, -2, 0, 0, 2, 0, 0],
    [0, 2, 0, 1, -2, 0, 1, 0],
    [-4, 0, 4, 0, 0, 0, 0, 0],
    [0, 2, 0, -2, 2, 0, 0, 0],
    [8, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 4, 0, 0, 0, 0],
    [2, 0, -2, 0, 0, 1, 0, 1],
    [0, -2, 0, 1, 2, 0, 1, 0],
    [4, 0, 4, 0, 0, 0, 0, 0],
    [0, 8, 0, 0, 0, 0, 0, 0],
    [2, 0, 2, 0, 0, 2, 0, 0],
    [0, 0, 0, 2, 0, 0, 2, 0],
    [-2, 0, 2, 0, 0, 1, 0, 1],
    [0, 2, 0, 2, 2, 0, 0, 0],
    [16, 0, 0, 0, 0, 0, 0, 0],
];

fn zz60_display(coeffs: &[i64; 16], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let sixteenth = Ratio::<i64>::new_raw(1, 16);
    // Project to GaussInt-Ratio coefficients of the symbolic basis, each
    // with the implicit /16 folded in.
    let mut k_coeffs: [GaussInt<Ratio<i64>>; 8] = [GaussInt::new(
        Ratio::<i64>::from_integer(0),
        Ratio::<i64>::from_integer(0),
    ); 8];
    for j in 0..8 {
        let mut re_acc: i64 = 0;
        let mut im_acc: i64 = 0;
        for k in 0..16 {
            re_acc += coeffs[k] * ZZ60_RE_DECOMP[k][j];
            im_acc += coeffs[k] * ZZ60_IM_DECOMP[k][j];
        }
        k_coeffs[j] = GaussInt::new(
            Ratio::<i64>::from_integer(re_acc) * sixteenth,
            Ratio::<i64>::from_integer(im_acc) * sixteenth,
        );
    }
    format_symbolic(
        &k_coeffs,
        &[
            "1",
            "3",
            "5",
            "2(5-sqrt(5))",
            "15",
            "6(5-sqrt(5))",
            "10(5-sqrt(5))",
            "30(5-sqrt(5))",
        ],
        f,
    )
}

/// Sign of an 8-component K-vector in the ZZ60 real subring basis. Exact
/// via the closed-form `signum_sum_sqrt_expr_8_zz60`.
#[inline]
fn zz60_real_sign(x: &[i64; 8]) -> i8 {
    crate::cyclotomic::sign::signum_sum_sqrt_expr_8_zz60::<i64>(
        x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7],
    ) as i8
}

define_integral_zz! {
    name: ZZ60,
    n: 60,
    phi: 16,
    real_dim: 8,
    // Phi_60(x) = x^16 + x^14 - x^10 - x^8 - x^6 + x^2 + 1, so
    // zeta^16 = -zeta^14 + zeta^10 + zeta^8 + zeta^6 - zeta^2 - 1.
    reduction: [-1i64, 0, -1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, -1, 0],
    re_decomp: ZZ60_RE_DECOMP,
    im_decomp: ZZ60_IM_DECOMP,
    cartesian: ZZ60_CARTESIAN,
    params: ZZ60_PARAMS,
    one_in_real_basis: [16i64, 0, 0, 0, 0, 0, 0, 0],
    display_fn: zz60_display,
    complex64_fn: zz60_complex64,
    has: [HasZZ4Impl, HasZZ6Impl, HasZZ10Impl, HasZZ12Impl],
}

impl From<(i64, i64)> for ZZ60 {
    /// `(re, im)` where `i = zeta^15`, so `(a, b) = a + b*i` maps to
    /// integer-basis coefficients with `b` at position 15.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        let mut c = [0i64; 16];
        c[0] = re;
        c[15] = im;
        Self::from_int_coeffs(c)
    }
}

crate::impl_integral_units_via_basis!(ZZ60, 60);
crate::impl_integral_mul_via_basis!(ZZ60, 16);
crate::impl_integral_conj_via_basis!(ZZ60, 16);
crate::impl_integral_re_im_sign_via_basis!(ZZ60, 16, 8, zz60_real_sign);
crate::impl_integral_intersect_unit_segments_via_basis!(ZZ60, 16, 8, zz60_real_sign);
crate::impl_integral_within_radius_via_complex64!(ZZ60);
crate::zz_integral_ring_tests!(name: ZZ60);

// ----------------
// ZZ32 -- Z[zeta_32].
//
// `zeta = e^(2*pi*i/32) = cos(11.25) + i*sin(11.25)`, `Phi_32(x) = x^16 + 1`,
// so `zeta^16 = -1`. Storage: `[i64; 16]` over `{1, zeta, ..., zeta^15}`.
//
// The real subring is `Q(sqrt(2), sqrt(2+sqrt(2)), sqrt(2+sqrt(2+sqrt(2))))`,
// dim 8, basis:
//   {1, sqrt(2), sqrt(2+sqrt(2)), sqrt(2+sqrt(2+sqrt(2))),
//    sqrt(2(2+sqrt(2))), sqrt(2(2+sqrt(2+sqrt(2)))),
//    sqrt((2+sqrt(2))(2+sqrt(2+sqrt(2)))),
//    sqrt(2(2+sqrt(2))(2+sqrt(2+sqrt(2))))}
// with `/2` implicit denominator.
//
// Real-sign extraction is **exact** via `signum_sum_sqrt_expr_8_zz32`
// (two-level recursive reduction `Q(sqrt(2), sqrt(2+sqrt(2)), sqrt(...))`
// -> `Q(sqrt(2), sqrt(2+sqrt(2)))` (the ZZ16 real subring, with its
// own exact sign helper) -> `Q(sqrt(2))`).
//
// Decomp tables generated via `src/bin/codegen_zz32.rs`.

#[inline]
fn zz32_complex64(coeffs: &[i64; 16]) -> Complex64 {
    let sq2 = std::f64::consts::SQRT_2;
    let sq_y = ZZ16_Y.sqrt(); // sqrt(2+sqrt(2))
    let sq_z = ZZ32_Z.sqrt(); // sqrt(2+sqrt(2+sqrt(2)))
    let sq_2y = (2.0 * ZZ16_Y).sqrt();
    let sq_2z = (2.0 * ZZ32_Z).sqrt();
    let sq_yz = (ZZ16_Y * ZZ32_Z).sqrt();
    let sq_2yz = (2.0 * ZZ16_Y * ZZ32_Z).sqrt();

    let proj = |table: &[[i64; 8]; 16]| -> f64 {
        let mut acc = [0i64; 8];
        for k in 0..16 {
            let ck = coeffs[k];
            if ck == 0 {
                continue;
            }
            for j in 0..8 {
                acc[j] += ck * table[k][j];
            }
        }
        (acc[0] as f64
            + (acc[1] as f64) * sq2
            + (acc[2] as f64) * sq_y
            + (acc[3] as f64) * sq_z
            + (acc[4] as f64) * sq_2y
            + (acc[5] as f64) * sq_2z
            + (acc[6] as f64) * sq_yz
            + (acc[7] as f64) * sq_2yz)
            * 0.5
    };
    let re = proj(&ZZ32_RE_DECOMP);
    let im = proj(&ZZ32_IM_DECOMP);
    Complex64::new(re, im)
}

const ZZ32_CARTESIAN: [Complex64; 16] = {
    // Placeholder (macro requires a const). Real values come from the
    // hand-rolled `complex64_fn` above.
    let mut out = [Complex64::new(0.0, 0.0); 16];
    out[0] = Complex64::new(1.0, 0.0);
    out
};

// Decomposition tables. Auto-generated via `src/bin/codegen_zz32.rs`.
const ZZ32_RE_DECOMP: [[i64; 8]; 16] = [
    [2, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, -1, 0],
    [0, 0, -1, 0, 1, 0, 0, 0],
    [0, 0, 0, -1, 0, -1, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 0, -1],
    [0, 0, 1, 0, -1, 0, 0, 0],
    [0, 0, 0, -1, 0, -1, 1, 0],
    [0, -1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, -1, 0],
    [0, 0, -1, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 0, 0, 0],
];

const ZZ32_IM_DECOMP: [[i64; 8]; 16] = [
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, -1, 0, 1],
    [0, 0, -1, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, -1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [2, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, -1, 0],
    [0, 0, -1, 0, 1, 0, 0, 0],
    [0, 0, 0, -1, 0, -1, 0, 1],
];

fn zz32_display(coeffs: &[i64; 16], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let half = Ratio::<i64>::new_raw(1, 2);
    let mut k_coeffs: [GaussInt<Ratio<i64>>; 8] = [GaussInt::new(
        Ratio::<i64>::from_integer(0),
        Ratio::<i64>::from_integer(0),
    ); 8];
    for j in 0..8 {
        let mut re_acc: i64 = 0;
        let mut im_acc: i64 = 0;
        for k in 0..16 {
            re_acc += coeffs[k] * ZZ32_RE_DECOMP[k][j];
            im_acc += coeffs[k] * ZZ32_IM_DECOMP[k][j];
        }
        k_coeffs[j] = GaussInt::new(
            Ratio::<i64>::from_integer(re_acc) * half,
            Ratio::<i64>::from_integer(im_acc) * half,
        );
    }
    format_symbolic(
        &k_coeffs,
        &[
            "1",
            "2",
            "2+sqrt(2)",
            "2+sqrt(2+sqrt(2))",
            "2(2+sqrt(2))",
            "2(2+sqrt(2+sqrt(2)))",
            "(2+sqrt(2))(2+sqrt(2+sqrt(2)))",
            "2(2+sqrt(2))(2+sqrt(2+sqrt(2)))",
        ],
        f,
    )
}

#[inline]
fn zz32_real_sign(x: &[i64; 8]) -> i8 {
    crate::cyclotomic::sign::signum_sum_sqrt_expr_8_zz32::<i64>(
        x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7],
    ) as i8
}

define_integral_zz! {
    name: ZZ32,
    n: 32,
    phi: 16,
    real_dim: 8,
    // Phi_32(x) = x^16 + 1, so zeta^16 = -1.
    reduction: [-1i64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    re_decomp: ZZ32_RE_DECOMP,
    im_decomp: ZZ32_IM_DECOMP,
    cartesian: ZZ32_CARTESIAN,
    params: ZZ32_PARAMS,
    one_in_real_basis: [2i64, 0, 0, 0, 0, 0, 0, 0],
    display_fn: zz32_display,
    complex64_fn: zz32_complex64,
    has: [HasZZ4Impl, HasZZ8Impl],
}

impl From<(i64, i64)> for ZZ32 {
    /// `(re, im)` where `i = zeta^8`, so `(a, b) = a + b*i` maps with
    /// `b` at position 8.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        let mut c = [0i64; 16];
        c[0] = re;
        c[8] = im;
        Self::from_int_coeffs(c)
    }
}

crate::impl_integral_units_via_basis!(ZZ32, 32);
crate::impl_integral_mul_via_basis!(ZZ32, 16);
crate::impl_integral_conj_via_basis!(ZZ32, 16);
crate::impl_integral_re_im_sign_via_basis!(ZZ32, 16, 8, zz32_real_sign);
crate::impl_integral_intersect_unit_segments_via_basis!(ZZ32, 16, 8, zz32_real_sign);
crate::impl_integral_within_radius_via_complex64!(ZZ32);
crate::zz_integral_ring_tests!(name: ZZ32);

// ----------------
// Ring-specific tests for ZZ12 (carried over from the old `zz12.rs`).

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cyclotomic::constants::zz_units_sum;
    use crate::cyclotomic::numtraits::OneImag;
    use crate::cyclotomic::{Ccw, Conj, ReImSign, SymNum, Units, ZZComplex};
    use num_traits::{One, Pow, Zero};

    /// Format-rendering checks across rings -- exercises the per-ring
    /// `display_fn` projecting integer-basis storage back to the
    /// symbolic-roots GaussInt-Ratio shape via `format_symbolic`.
    #[test]
    fn test_display() {
        let x = ZZ24::zero();
        assert_eq!(format!("{x}"), "0");

        let x = ZZ24::one();
        assert_eq!(format!("{x}"), "1");

        let x = ZZ24::one() + ZZ24::one();
        assert_eq!(format!("{x}"), "2");

        let x = -ZZ24::one();
        assert_eq!(format!("{x}"), "-1");

        let x = ZZ24::one() + (ZZ24::ccw()).pow(2i8);
        assert_eq!(format!("{x}"), "1+1/2i + (1/2)*sqrt(3)");

        let x: ZZ10 = zz_units_sum();
        assert_eq!(
            format!("{x}"),
            "-5 + (-15/4i)*sqrt(2(5-sqrt(5))) + (-5/4i)*sqrt(10(5-sqrt(5)))"
        );
    }

    type ZZi = ZZ12;

    #[test]
    fn test_units_periodic() {
        for k in 0i8..12 {
            assert_eq!(<ZZi as Units>::unit(k), <ZZi as Units>::unit(k + 12));
            assert_eq!(<ZZi as Units>::unit(k), <ZZi as Units>::unit(k - 12));
        }
    }

    #[test]
    fn test_units_group() {
        for a in 0..12 {
            for b in 0..12 {
                let lhs = <ZZi as Units>::unit(a) * <ZZi as Units>::unit(b);
                let rhs = <ZZi as Units>::unit(((a as i16 + b as i16) % 12) as i8);
                assert_eq!(lhs, rhs, "unit({a})*unit({b})");
            }
        }
    }

    #[test]
    fn test_zeta_squared() {
        let z = ZZi::ccw();
        assert_eq!(z * z, <ZZi as Units>::unit(2));
    }

    #[test]
    fn test_zeta_cubed_is_i() {
        let z = ZZi::ccw();
        let i = z * z * z;
        assert_eq!(i, ZZ12::one_i());
        assert_eq!(i * i, -ZZ12::one());
    }

    #[test]
    fn test_complex64_roundtrip() {
        for k in 0..12 {
            let u = <ZZi as Units>::unit(k);
            let c = u.complex64();
            let exp_angle = (k as f64) * std::f64::consts::PI / 6.0;
            assert!((c.re - exp_angle.cos()).abs() < 1e-12);
            assert!((c.im - exp_angle.sin()).abs() < 1e-12);
        }
    }

    #[test]
    fn test_conj_round_trip() {
        for k in 0..12 {
            let u = <ZZi as Units>::unit(k);
            assert_eq!(u.conj().conj(), u);
            // |u|^2 == 1 -> u * conj(u) == 1
            assert_eq!(u * u.conj(), ZZi::one(), "k={k}");
        }
    }

    #[test]
    fn test_re_im_signs() {
        for k in 0..12 {
            let u = <ZZi as Units>::unit(k);
            let c = u.complex64();
            let exp_re_sign = if c.re > 1e-9 {
                1
            } else if c.re < -1e-9 {
                -1
            } else {
                0
            };
            let exp_im_sign = if c.im > 1e-9 {
                1
            } else if c.im < -1e-9 {
                -1
            } else {
                0
            };
            assert_eq!(u.re_sign(), exp_re_sign, "k={k}");
            assert_eq!(u.im_sign(), exp_im_sign, "k={k}");
        }
    }

    #[test]
    fn test_basic_arith() {
        assert_eq!(ZZi::zero() + ZZi::zero(), ZZi::zero());
        assert_eq!(ZZi::one() + ZZi::zero(), ZZi::one());
        assert_eq!(ZZi::one() * ZZi::one(), ZZi::one());
        assert_eq!(-ZZi::one() * -ZZi::one(), ZZi::one());
        assert_eq!(ZZi::ccw().pow(12u8), ZZi::one());
        assert_eq!(ZZi::ccw().pow(6u8), -ZZi::one());
    }

    #[test]
    fn test_units_sum_complex() {
        let p: ZZi = zz_units_sum();
        assert!(p.is_complex());
    }
}
