//! Per-ring `define_integral_zz!` invocations.
//!
//! Each ring in this file lives in the integer-basis cyclotomic
//! representation (`[i64; phi(n)]` over `{1, zeta, ..., zeta^(phi(n)-1)}`)
//! and is generated by a single macro invocation feeding the per-ring
//! constant bundle (reduction rule, real/imag decomposition tables,
//! Cartesian projection, sign function) into the generic engine in
//! `cyclotomic::integral_basis`.
//!
//! Step 2: only ZZ12 lives here for now. Steps 3+ will port the other
//! cyclotomic rings off the GaussInt<Ratio> machinery and into this file.

use num_complex::Complex64;
use num_rational::Ratio;

use crate::cyclotomic::gaussint::GaussInt;
use crate::cyclotomic::params::ZZ12_PARAMS;
use crate::define_integral_zz;

// ----------------
// ZZ12

/// Hand-rolled `complex64` for ZZ12: inline `Re`/`Im` of `(a, b, c, d)`
/// in the `{1, zeta, zeta^2, zeta^3}` basis, avoiding the
/// `complex64_basis` loop. Called from `cell_of` on the hot path.
#[inline]
fn zz12_complex64(coeffs: &[i64; 4]) -> Complex64 {
    // zeta = sqrt(3)/2 + i/2
    // Re = a + b * sqrt(3)/2 + c * 1/2 + d * 0
    // Im = 0 + b * 1/2       + c * sqrt(3)/2 + d
    const HALF_SQRT_3: f64 = 0.866_025_403_784_438_6_f64;
    let [a, b, c, d] = *coeffs;
    let (a, b, c, d) = (a as f64, b as f64, c as f64, d as f64);
    let re = a + b * HALF_SQRT_3 + 0.5 * c;
    let im = 0.5 * b + c * HALF_SQRT_3 + d;
    Complex64::new(re, im)
}

/// Cartesian projection table for ZZ12: `zeta^k` as a `Complex64`, for
/// `zeta = e^(i*pi/6) = sqrt(3)/2 + i/2`.
const ZZ12_CARTESIAN: [Complex64; 4] = {
    // sqrt(3)/2 to f64. Kept as a literal to allow `const` evaluation.
    const HALF_SQRT_3: f64 = 0.866_025_403_784_438_6_f64;
    [
        // zeta^0 = 1
        Complex64::new(1.0, 0.0),
        // zeta^1 = sqrt(3)/2 + i/2
        Complex64::new(HALF_SQRT_3, 0.5),
        // zeta^2 = 1/2 + i*sqrt(3)/2
        Complex64::new(0.5, HALF_SQRT_3),
        // zeta^3 = i
        Complex64::new(0.0, 1.0),
    ]
};

/// Display impl for ZZ12. Matches the legacy hand-written format in
/// `zz12.rs`: project the integer-basis vector back to symbolic
/// `{sqrt(1), sqrt(3)}` form and emit the same per-term shape that the
/// macro-generated rings use.
///
/// For `(a, b, c, d)`:
///
/// ```text
///   c0 = ((2a + c)/2) + i*((b + 2d)/2)   coefficient of sqrt(1)
///   c1 = (b/2)        + i*(c/2)          coefficient of sqrt(3)
/// ```
fn zz12_display(coeffs: &[i64; 4], f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    let [a, b, c, d] = *coeffs;
    let half = Ratio::<i64>::new_raw(1, 2);
    let c0 = GaussInt::new(
        Ratio::<i64>::from_integer(2 * a + c) * half,
        Ratio::<i64>::from_integer(b + 2 * d) * half,
    );
    let c1 = GaussInt::new(
        Ratio::<i64>::from_integer(b) * half,
        Ratio::<i64>::from_integer(c) * half,
    );

    let coeffs = [c0, c1];
    let labels = ["1", "3"];
    let mut parts: Vec<String> = Vec::new();
    for (coeff, lbl) in coeffs.iter().zip(labels.iter()) {
        let s = format!("{coeff}");
        if s == "0" {
            continue;
        }
        let is_real_unit = *lbl == "1";
        let lbl_str = format!("sqrt({lbl})");
        if s == "1" {
            parts.push(if is_real_unit {
                "1".to_string()
            } else {
                lbl_str
            });
        } else if is_real_unit {
            parts.push(s);
        } else {
            parts.push(format!("({s})*{lbl_str}"));
        }
    }
    let joined = parts.join(" + ");
    let result = if joined.is_empty() {
        "0".to_string()
    } else {
        joined
    };
    write!(f, "{result}")
}

define_integral_zz! {
    name: ZZ12,
    n: 12,
    phi: 4,
    real_dim: 2,
    // Phi_12(x) = x^4 - x^2 + 1, so zeta^4 = zeta^2 - 1.
    reduction: [-1i64, 0, 1, 0],
    // K-vector of Re(zeta^k) against {sqrt(1), sqrt(3)}, with implicit /2:
    //   Re(zeta^0) = 1            -> [2, 0] / 2
    //   Re(zeta^1) = sqrt(3)/2    -> [0, 1] / 2
    //   Re(zeta^2) = 1/2          -> [1, 0] / 2
    //   Re(zeta^3) = 0            -> [0, 0] / 2
    re_decomp: [[2i64, 0], [0, 1], [1, 0], [0, 0]],
    // K-vector of Im(zeta^k):
    //   Im(zeta^0) = 0            -> [0, 0] / 2
    //   Im(zeta^1) = 1/2          -> [1, 0] / 2
    //   Im(zeta^2) = sqrt(3)/2    -> [0, 1] / 2
    //   Im(zeta^3) = 1            -> [2, 0] / 2
    im_decomp: [[0i64, 0], [1, 0], [0, 1], [2, 0]],
    cartesian: ZZ12_CARTESIAN,
    params: ZZ12_PARAMS,
    // The real-subring element `1` against {sqrt(1), sqrt(3)} with the
    // implicit /2 denominator: 1 = (2 + 0*sqrt(3)) / 2, so the K-vector
    // before the /2 normalization is [2, 0].
    one_in_real_basis: [2i64, 0],
    display_fn: zz12_display,
    complex64_fn: zz12_complex64,
    has: [HasZZ4Impl, HasZZ6Impl, HasZZ12Impl],
}

impl From<(i64, i64)> for ZZ12 {
    /// `(re, im)` where `i = zeta^3`, so `(a, b) = a + b*i = a + b*zeta^3`.
    #[inline]
    fn from((re, im): (i64, i64)) -> Self {
        Self::from_int_coeffs([re, 0, 0, im])
    }
}

// ----------------
// Hand-rolled ZZ12 `Mul` and `Conj` -- the inner two hot helpers in the
// rat_enum hot path. ZZ12-specific polynomial expansions below substantially
// outperform the generic `mul_basis` / `conj_basis` engines (`mul_basis`
// allocates a 32-slot scratch, has two folding loops; `conj_basis` indirects
// through a OnceLock-cached matrix). Step 2 perf measurement showed these
// two specializations together close ~ all of the regression vs the
// pre-port hand-written ZZ12.

impl std::ops::Mul<ZZ12> for ZZ12 {
    type Output = Self;
    /// Multiplication in the integral cyclotomic basis `{1, zeta, zeta^2, zeta^3}`,
    /// using `Phi_12(x) = x^4 - x^2 + 1`, so `zeta^4 = zeta^2 - 1`,
    /// `zeta^5 = zeta^3 - zeta`, `zeta^6 = -1`.
    ///
    /// For `x = (a, b, c, d)` and `y = (e, f, g, h)`:
    ///
    /// ```text
    ///   result_0 = ae - bh - cg - df - dh
    ///   result_1 = af + be - ch - dg
    ///   result_2 = ag + bf + ce + bh + cg + df
    ///   result_3 = ah + bg + cf + de + ch + dg
    /// ```
    #[inline]
    fn mul(self, other: Self) -> Self {
        let [a, b, c, d] = self.int_coeffs();
        let [e, f, g, h] = other.int_coeffs();
        let r0 = a * e - b * h - c * g - d * f - d * h;
        let r1 = a * f + b * e - c * h - d * g;
        let r2 = a * g + b * f + c * e + b * h + c * g + d * f;
        let r3 = a * h + b * g + c * f + d * e + c * h + d * g;
        Self::from_int_coeffs([r0, r1, r2, r3])
    }
}

impl crate::cyclotomic::Conj for ZZ12 {
    /// Conjugation in `{1, zeta, zeta^2, zeta^3}`:
    ///
    /// `conj(zeta) = zeta^11 = zeta - zeta^3`  ->  `(0,  1, 0, -1)`
    /// `conj(zeta^2) = zeta^10 = 1 - zeta^2`   ->  `(1,  0, -1, 0)`
    /// `conj(zeta^3) = zeta^9 = -zeta^3`        ->  `(0, 0, 0, -1)`
    ///
    /// So `conj((a, b, c, d)) = (a + c, b, -c, -b - d)`.
    #[inline]
    fn conj(&self) -> Self {
        let [a, b, c, d] = self.int_coeffs();
        Self::from_int_coeffs([a + c, b, -c, -b - d])
    }
}

impl crate::cyclotomic::Units for ZZ12 {
    /// Static-baked `zeta^k` lookup for `k` in `0..12`. Avoids the OnceLock
    /// + Vec indirection of the generic `derive_units_lookup` path.
    #[inline]
    fn unit(angle: i8) -> Self {
        static UNIT_TABLE: [[i64; 4]; 12] = [
            [1, 0, 0, 0],  // 1
            [0, 1, 0, 0],  // zeta
            [0, 0, 1, 0],  // zeta^2
            [0, 0, 0, 1],  // zeta^3 = i
            [-1, 0, 1, 0], // zeta^4 = zeta^2 - 1
            [0, -1, 0, 1], // zeta^5 = zeta^3 - zeta
            [-1, 0, 0, 0], // zeta^6 = -1
            [0, -1, 0, 0], // zeta^7
            [0, 0, -1, 0], // zeta^8
            [0, 0, 0, -1], // zeta^9
            [1, 0, -1, 0], // zeta^10
            [0, 1, 0, -1], // zeta^11
        ];
        let idx = angle.rem_euclid(12) as usize;
        Self::from_int_coeffs(UNIT_TABLE[idx])
    }
}

// ----------------
// Hand-rolled ZZ12 hot-path overrides.
//
// These three impls (`ReImSign`, `WithinRadius`, `IntersectUnitSegments`)
// are the perf-critical surface in `rat_enum`. The generic
// `integral_basis::*` helpers are correct, but the per-ring specialization
// here exploits ZZ12-specific symbolic structure (the basis being
// `{sqrt(1), sqrt(3)}` with implicit /2) to:
//
//   * read `Re`/`Im` components inline as `(2a + c, b)` / `(b + 2d, c)`,
//     skipping the K-vector projection and decomposition-table lookup;
//   * compare squared norms in pure i64 arithmetic (no Complex64);
//   * route `intersect_unit_segments` through the original 3-multiplication
//     ZZ12 fast path that consumed `im_components` directly off each product.
//
// The matching `impl_integral_re_im_sign_via_basis!` /
// `impl_integral_intersect_unit_segments_via_basis!` /
// `impl_integral_within_radius_via_complex64!` macros are available for
// other rings to opt into the generic path with one line each.

/// Sign of `m + n*sqrt(3)` where m, n are i64. Returns -1, 0, or 1.
///
/// Cheap cases (one zero, both same sign) resolve without multiplication;
/// mixed-sign case compares `m^2` vs `3 * n^2`.
#[inline]
fn sign_m_plus_n_sqrt3(m: i64, n: i64) -> i8 {
    if m == 0 && n == 0 {
        return 0;
    }
    if m >= 0 && n >= 0 {
        return 1;
    }
    if m <= 0 && n <= 0 {
        return -1;
    }
    // Mixed signs.
    let m_sq = m
        .checked_mul(m)
        .expect("ZZ12 sign_m_plus_n_sqrt3 overflow: m*m");
    let n_sq = n
        .checked_mul(n)
        .expect("ZZ12 sign_m_plus_n_sqrt3 overflow: n*n");
    let three_n_sq = 3i64
        .checked_mul(n_sq)
        .expect("ZZ12 sign_m_plus_n_sqrt3 overflow: 3*n*n");
    if m > 0 {
        match m_sq.cmp(&three_n_sq) {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        }
    } else {
        match three_n_sq.cmp(&m_sq) {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        }
    }
}

impl crate::cyclotomic::ReImSign for ZZ12 {
    /// `Re(z) = ((2a + c) + b*sqrt(3)) / 2`, denominator positive, so the
    /// sign reduces to `sign((2a + c) + b*sqrt(3))`.
    #[inline]
    fn re_sign(&self) -> i8 {
        let [a, b, c, _] = self.int_coeffs();
        sign_m_plus_n_sqrt3(2 * a + c, b)
    }

    /// `Im(z) = ((b + 2d) + c*sqrt(3)) / 2`.
    #[inline]
    fn im_sign(&self) -> i8 {
        let [_, b, c, d] = self.int_coeffs();
        sign_m_plus_n_sqrt3(b + 2 * d, c)
    }
}

impl crate::cyclotomic::WithinRadius for ZZ12 {
    /// Pure-i64 squared-norm comparison.
    ///
    /// For `z = (a, b, c, d)`:
    /// `|z|^2 = (M + N*sqrt(3)) / 4` with
    ///   M = (2a + c)^2 + 3*b^2 + (b + 2d)^2 + 3*c^2
    ///   N = 2 * ((2a + c)*b + (b + 2d)*c)
    ///
    /// `|z|^2 <= radius^2` iff `sign_m_plus_n_sqrt3(M - 4*r^2, N) <= 0`.
    #[inline]
    fn within_radius(&self, radius: i64) -> bool {
        let [a, b, c, d] = self.int_coeffs();
        let s = 2 * a + c;
        let t = b + 2 * d;
        let m = s * s + 3 * b * b + t * t + 3 * c * c;
        let n = 2 * (s * b + t * c);
        let four_r_sq = 4 * radius * radius;
        sign_m_plus_n_sqrt3(m - four_r_sq, n) <= 0
    }
}

/// Imaginary-part components of a ZZ12 value `z = (a, b, c, d)`:
/// `Im(z) = (im_m + im_n * sqrt(3)) / 2` where `im_m = b + 2*d`, `im_n = c`.
#[inline]
fn im_components(coeffs: &[i64; 4]) -> (i64, i64) {
    let [_, b, c, d] = *coeffs;
    (b + 2 * d, c)
}

/// Real-part components of a ZZ12 value `z = (a, b, c, d)`:
/// `Re(z) = (re_m + re_n * sqrt(3)) / 2` where `re_m = 2*a + c`, `re_n = b`.
#[inline]
fn re_components(coeffs: &[i64; 4]) -> (i64, i64) {
    let [a, b, c, _] = *coeffs;
    (2 * a + c, b)
}

impl crate::cyclotomic::IntersectUnitSegments for ZZ12 {
    /// 3-multiplication pure-i64 fast path that exploits the unit-length
    /// structure of both input segments. See `zz12.rs` history for the
    /// full math derivation; the shape is identical to the generic
    /// `intersect_unit_segments_basis` but inlines `Re`/`Im` component
    /// extraction off each multiplication result.
    #[inline]
    fn intersect_unit_segments(s1: &(ZZ12, ZZ12), s2: &(ZZ12, ZZ12)) -> bool {
        use crate::cyclotomic::Conj;

        let (a, b) = *s1;
        let (c, d) = *s2;

        // Touching endpoints do not count as a proper intersection.
        if a == c || a == d || b == c || b == d {
            return false;
        }

        let u_a = b - a;
        let u_b = d - c;
        let delta = c - a;

        // ZZ12 mul #1: K = wedge(uA, uB).
        let k_z = u_a.conj() * u_b;
        let (k_m, k_n) = im_components(&k_z.int_coeffs());
        let sign_k = sign_m_plus_n_sqrt3(k_m, k_n);

        // ZZ12 mul #2: V = wedge(uA, delta) (Im(v_z)). We also reuse Re(v_z)
        // = dot(uA, delta) for the inline colinear-overlap test below.
        let v_z = u_a.conj() * delta;
        let (v_m, v_n) = im_components(&v_z.int_coeffs());
        let sign_v = sign_m_plus_n_sqrt3(v_m, v_n);

        if sign_k == 0 {
            if sign_v != 0 {
                return false;
            }
            // Colinear. T = Re(v_z) = dot(uA, delta).
            let (t_m, t_n) = re_components(&v_z.int_coeffs());
            let k_coeffs = k_z.int_coeffs();
            debug_assert_eq!([k_coeffs[1], k_coeffs[2], k_coeffs[3]], [0, 0, 0]);
            if k_coeffs[0] == 1 {
                // uA == uB. Interior overlap iff -1 < T < 1.
                return sign_m_plus_n_sqrt3(t_m + 2, t_n) > 0
                    && sign_m_plus_n_sqrt3(t_m - 2, t_n) < 0;
            } else {
                debug_assert_eq!(k_coeffs[0], -1);
                // uA == -uB. Interior overlap iff 0 < T < 2.
                return sign_m_plus_n_sqrt3(t_m, t_n) > 0
                    && sign_m_plus_n_sqrt3(t_m - 4, t_n) < 0;
            }
        }

        // Non-colinear case.
        let sign_v_plus_k = sign_m_plus_n_sqrt3(v_m + k_m, v_n + k_n);
        if (sign_v > 0) == (sign_v_plus_k > 0) {
            return false;
        }

        // ZZ12 mul #3: W = wedge(delta, uB).
        let (w_m, w_n) = im_components(&(delta.conj() * u_b).int_coeffs());
        let sign_w = sign_m_plus_n_sqrt3(w_m, w_n);
        let sign_w_minus_k = sign_m_plus_n_sqrt3(w_m - k_m, w_n - k_n);
        (sign_w > 0) != (sign_w_minus_k > 0)
    }
}

// ----------------
// Generic algebraic / cyclotomic-structure test suite for ZZ12.
//
// Emits a sibling `zz12_generic_ring_tests` module of ~25 ring-axiom
// tests. The ring-specific `mod tests` below stays for ZZ12-only checks
// (Display format, specific value assertions).
crate::zz_integral_ring_tests!(name: ZZ12);

// ----------------
// Ring-specific tests for ZZ12 (carried over from the old `zz12.rs`).

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cyclotomic::constants::zz_units_sum;
    use crate::cyclotomic::numtraits::OneImag;
    use crate::cyclotomic::{Ccw, Conj, ReImSign, SymNum, Units, ZZComplex};
    use num_traits::{One, Pow, Zero};

    type ZZi = ZZ12;

    #[test]
    fn test_units_periodic() {
        for k in 0i8..12 {
            assert_eq!(<ZZi as Units>::unit(k), <ZZi as Units>::unit(k + 12));
            assert_eq!(<ZZi as Units>::unit(k), <ZZi as Units>::unit(k - 12));
        }
    }

    #[test]
    fn test_units_group() {
        for a in 0..12 {
            for b in 0..12 {
                let lhs = <ZZi as Units>::unit(a) * <ZZi as Units>::unit(b);
                let rhs = <ZZi as Units>::unit(((a as i16 + b as i16) % 12) as i8);
                assert_eq!(lhs, rhs, "unit({a})*unit({b})");
            }
        }
    }

    #[test]
    fn test_zeta_squared() {
        let z = ZZi::ccw();
        assert_eq!(z * z, <ZZi as Units>::unit(2));
    }

    #[test]
    fn test_zeta_cubed_is_i() {
        let z = ZZi::ccw();
        let i = z * z * z;
        assert_eq!(i, ZZ12::one_i());
        assert_eq!(i * i, -ZZ12::one());
    }

    #[test]
    fn test_complex64_roundtrip() {
        for k in 0..12 {
            let u = <ZZi as Units>::unit(k);
            let c = u.complex64();
            let exp_angle = (k as f64) * std::f64::consts::PI / 6.0;
            assert!((c.re - exp_angle.cos()).abs() < 1e-12);
            assert!((c.im - exp_angle.sin()).abs() < 1e-12);
        }
    }

    #[test]
    fn test_conj_round_trip() {
        for k in 0..12 {
            let u = <ZZi as Units>::unit(k);
            assert_eq!(u.conj().conj(), u);
            // |u|^2 == 1 -> u * conj(u) == 1
            assert_eq!(u * u.conj(), ZZi::one(), "k={k}");
        }
    }

    #[test]
    fn test_re_im_signs() {
        for k in 0..12 {
            let u = <ZZi as Units>::unit(k);
            let c = u.complex64();
            let exp_re_sign = if c.re > 1e-9 {
                1
            } else if c.re < -1e-9 {
                -1
            } else {
                0
            };
            let exp_im_sign = if c.im > 1e-9 {
                1
            } else if c.im < -1e-9 {
                -1
            } else {
                0
            };
            assert_eq!(u.re_sign(), exp_re_sign, "k={k}");
            assert_eq!(u.im_sign(), exp_im_sign, "k={k}");
        }
    }

    #[test]
    fn test_basic_arith() {
        assert_eq!(ZZi::zero() + ZZi::zero(), ZZi::zero());
        assert_eq!(ZZi::one() + ZZi::zero(), ZZi::one());
        assert_eq!(ZZi::one() * ZZi::one(), ZZi::one());
        assert_eq!(-ZZi::one() * -ZZi::one(), ZZi::one());
        assert_eq!(ZZi::ccw().pow(12u8), ZZi::one());
        assert_eq!(ZZi::ccw().pow(6u8), -ZZi::one());
    }

    #[test]
    fn test_units_sum_complex() {
        let p: ZZi = zz_units_sum();
        assert!(p.is_complex());
    }
}
