//! Core traits and parameter struct for cyclotomic rings.
//!
//! Every concrete ring (`ZZn` for `n in {4, 8, 10, 12, 16, 20, 24, 32, 60}`)
//! is generated by `define_integral_zz!` in `integral_basis.rs` and lives
//! in `rings.rs`. This module provides the small shared trait surface they
//! all implement.

use std::fmt::{Debug, Display};
use std::hash::Hash;

use num_complex::Complex64;
use num_integer::Integer;
use num_traits::{FromPrimitive, ToPrimitive};

use super::numtraits::{IntField, ZSigned};
use super::traits::IsRingOrField;

/// The integer scalar used throughout: every ring stores `[i64; phi(n)]`.
pub type IntT = i64;

/// Per-ring parameters carried as a `const` and exposed via
/// [`SymNum::zz_params`].
///
/// Slimmed to just `full_turn_steps` -- the only field still used outside
/// the ring itself (by `T::turn()` / `T::hturn()` / `T::qturn()` and by
/// `constants::sqrt2` / `sqrt3` / ... and `intgeom::angles`).
#[derive(Debug)]
pub struct ZZParams {
    /// Number of steps in one full rotation, i.e. `n` for `ZZn`.
    pub full_turn_steps: i8,
}

/// Bound for the scalar coefficient type of a `SymNum` ring. With every
/// ring now using integer-basis storage, `Self::Scalar = i64` in practice.
pub trait SymScalar: IntField + FromPrimitive + ZSigned + Debug + Display {}
impl<T: IntField + FromPrimitive + ZSigned + Debug + Display> SymScalar for T {}

/// Shared cyclotomic-ring trait: every ring implements this with the
/// `define_integral_zz!` macro.
pub trait SymNum: Clone + Copy + PartialEq + Eq + Hash + Debug + Display {
    /// Coefficient type used for the ring's storage vector. Always `i64`
    /// for the integer-basis rings, but kept as an associated type so the
    /// trait can absorb a future field-of-fractions variant.
    type Scalar: SymScalar;

    /// Number of distinct angles in one full turn (i.e. `n` for `ZZn`).
    #[inline]
    fn turn() -> i8 {
        Self::zz_params().full_turn_steps
    }

    /// Half-turn angle, i.e. the angle whose `unit(...)` equals `-1`.
    #[inline]
    fn hturn() -> i8 {
        Self::turn() / 2
    }

    /// `true` if the ring contains `i` (equivalently `4 | n`).
    #[inline]
    fn has_qturn() -> bool {
        Self::turn() % 4 == 0
    }

    /// Quarter-turn angle. Only meaningful when `has_qturn()`.
    #[inline]
    fn qturn() -> i8 {
        Self::turn() / 4
    }

    /// `Some(qturn)` when the ring contains `i`, `None` otherwise.
    #[inline]
    fn opt_qturn() -> Option<i8> {
        if Self::has_qturn() {
            Some(Self::qturn())
        } else {
            None
        }
    }

    /// Scalar multiplication by an integer.
    #[inline]
    fn scale<I: Integer + ToPrimitive>(&self, scalar: I) -> Self
    where
        Self: Sized + Copy,
    {
        let sc = Self::Scalar::from_i64(scalar.to_i64().unwrap()).unwrap();
        let mut ret = *self;
        for c in ret.zz_coeffs_mut().iter_mut() {
            *c = *c * sc;
        }
        ret
    }

    /// Project to a `Complex64`.
    fn complex64(&self) -> Complex64;

    /// Two-coordinate projection: `(re, im)` of `complex64()`.
    #[inline]
    fn xy(&self) -> (f64, f64) {
        let c = self.complex64();
        (c.re, c.im)
    }

    fn zz_coeffs(&self) -> &[Self::Scalar];
    fn zz_coeffs_mut(&mut self) -> &mut [Self::Scalar];

    fn zz_params() -> &'static ZZParams;

    /// Exponentiation by squaring. Used by the `Pow<u8>` / `Pow<i8>` impls
    /// the `define_integral_zz!` macro emits, and by `Units::unit` cache
    /// builders that walk `ccw()^k`.
    fn zz_pow(&self, i: u8) -> Self
    where
        Self: IsRingOrField,
    {
        let mut base = *self;
        let mut exp = i;
        let mut acc = Self::one();
        while exp != 0 {
            if (exp & 1) == 1 {
                acc = acc * base;
            }
            exp >>= 1;
            if exp != 0 {
                base = base * base;
            }
        }
        acc
    }
}

/// Predicates that classify a cyclotomic ring element as purely real,
/// purely imaginary, or strictly complex.
pub trait ZZComplex {
    /// `true` if the value is purely real.
    fn is_real(&self) -> bool;

    /// `true` if the value is purely imaginary.
    fn is_imag(&self) -> bool;

    /// `true` if the value is strictly complex (neither purely real nor
    /// purely imaginary).
    fn is_complex(&self) -> bool {
        !self.is_real() && !self.is_imag()
    }
}
