//! In this module the different ring types are generated using macros.

use std::fmt;
use std::fmt::Display;
use std::ops::{Add, Mul, Neg, Sub};

use num_complex::Complex64;
use num_traits::{One, Pow, ToPrimitive, Zero};

use paste::paste;

use super::gaussint::GaussInt;
use super::numtraits::{Ccw, Conj, InnerIntType, IntRing, OneImag};
use super::params::*;
use super::sign::coeffs_real_sign_fallback;
use super::symnum::{GIntT, RatioT, SymNum, ZZComplex, ZZParams};
use super::traits::{
    ComplexTraits, HasZZ4Impl, HasZZ8Impl, IsRing, IsRingOrField, RingTraits, ZZType,
};
use super::units::Units;

use crate::impl_intersect_unit_segments_via_general;
use crate::impl_re_im_sign_via_proj;
use crate::impl_within_radius_via_norm_sq;

// Re-export the integer-basis rings (generated by `define_integral_zz!` in
// `rings.rs`) so existing `use super::super::types::ZZ4;` paths keep
// resolving.
#[allow(unused_imports)]
pub use super::rings::{ZZ10, ZZ12, ZZ16, ZZ20, ZZ24, ZZ4, ZZ60, ZZ8};

// generate boilerplate implementations

macro_rules! impl_symnum_struct_for {
    ($($n:expr)*) => ($(
        paste! {
            impl_symnum!([<ZZ $n>], [<ZZ $n _PARAMS>], [<zz $n _mul>]);
        }
    )*)
}
macro_rules! zz_from_int_pair {
    ($t:ty) => {
        impl From<(<$t as InnerIntType>::IntType, <$t as InnerIntType>::IntType)> for $t {
            fn from(
                (re, im): (
                    <Self as InnerIntType>::IntType,
                    <Self as InnerIntType>::IntType,
                ),
            ) -> Self {
                Self::one().scale(re) + Self::one_i().scale(im)
            }
        }
    };
}
macro_rules! impl_from_int_pair {
    ($($n:expr)*) => ($(
        paste! {
            zz_from_int_pair!([<ZZ $n>]);
        }
    )*)
}
// NOTE: ZZ4, ZZ8, ZZ10, ZZ12, ZZ16, ZZ20, ZZ24 and ZZ60 are **not**
// generated by these macros. They live in `src/cyclotomic/rings.rs` on
// the new integer-basis storage. ZZ32 is the only remaining ring on the
// legacy symbolic `GaussInt<Ratio>`-coefficient representation.
impl_symnum_struct_for!(32);

// cached unit lookup per concrete complex type
super::units::impl_units_for!(ZZ32);

impl_functional_traits!(ZZ32);

// HasZZ4Impl and IsZZ4Impl are added directly via the `has:` clause in
// `define_integral_zz!` for ZZ4, ZZ8, ZZ16, ZZ20, ZZ24 and ZZ60.
zz_triv_impl!(HasZZ4Impl, ZZ32);
impl_from_int_pair!(32);

// NOTE: ZZ6 and ZZ30 standalone types were removed -- they don't contain
// ZZ4 (no `i`), so the unit-square-grid machinery doesn't apply uniformly.
// The `HasZZ6Impl` trait stays: ZZ6 still exists as a *subring* of ZZ12,
// ZZ24, ZZ60, which is what `T: HasZZ6` captures.
// HasZZ6Impl, HasZZ8Impl, HasZZ10Impl, HasZZ12Impl are added directly
// via the `has:` clause in `define_integral_zz!` for the relevant rings.
// ZZ32 remains the only ring using the legacy path; it implements
// HasZZ8Impl (since 8 | 32).
zz_triv_impl!(HasZZ8Impl, ZZ32);

// Generate the coefficient-projection ReImSign for every complex ring
// **except** ZZ12. ZZ12 provides its own pure-i64 override in `zz12.rs`.
//
// Each ring's `coeffs_real_sign_*` function operates directly on the
// `Ratio<i64>` real (or imaginary) halves of the GaussInt-backed
// coefficient array and the matching `sym_roots_sqs` parameters.
impl_re_im_sign_via_proj!(ZZ32, coeffs_real_sign_fallback);

// Generate the norm_sq-based WithinRadius for every complex ring **except**
// ZZ12. ZZ12 provides its own pure-i64 override in `zz12.rs`.
impl_within_radius_via_norm_sq!(ZZ32);

// Generate the generic-`intersect`-based `IntersectUnitSegments` for every
// complex ring **except** ZZ12. ZZ12 provides its own 3-multiplication
// pure-i64 override in `zz12.rs`.
impl_intersect_unit_segments_via_general!(ZZ32);

#[cfg(test)]
mod tests {
    use super::*;

    use super::super::constants::zz_units_sum;
    use super::super::symnum::{GIntT, SymNum};
    use super::super::units::Units;

    macro_rules! zz_tests {
        ($mod: ident, $type: ident, $($n:expr)*) => ($(
            paste! { zz_test!([<$mod $n>], [<$type $n>]); }
        )*)
    }

    #[test]
    fn test_display() {
        let x = ZZ24::zero();
        assert_eq!(format!("{x}"), "0");

        let x = ZZ24::one();
        assert_eq!(format!("{x}"), "1");

        let x = ZZ24::one() + ZZ24::one();
        assert_eq!(format!("{x}"), "2");

        let x = -ZZ24::one();
        assert_eq!(format!("{x}"), "-1");

        let x = ZZ24::one() + (ZZ24::ccw()).pow(2i8);
        assert_eq!(format!("{x}"), "1+1/2i + (1/2)*sqrt(3)");

        let x: ZZ10 = zz_units_sum();
        assert_eq!(
            format!("{x}"),
            "-5 + (-15/4i)*sqrt(2(5-sqrt(5))) + (-5/4i)*sqrt(10(5-sqrt(5)))"
        );
    }

    // NOTE: only ZZ32 remains on the legacy storage. All other ZZ rings
    // are in `rings.rs` with the integer-basis layout, where the generic
    // SymNum-coefficient tests (e.g. `test_scaling_fac`) don't apply;
    // their tests run via `zz_integral_ring_tests!`.
    zz_tests!(zz, ZZ, 32);
}
