//! In this module the different ring types are generated using macros.

use std::fmt;
use std::fmt::Display;
use std::ops::{Add, Mul, Neg, Sub};

use num_complex::Complex64;
use num_traits::{One, Pow, ToPrimitive, Zero};

use paste::paste;

use super::gaussint::GaussInt;
use super::numtraits::{Ccw, Conj, InnerIntType, IntRing, OneImag};
use super::params::*;
use super::sign::{
    coeffs_real_sign_1_sym, coeffs_real_sign_2_sym, coeffs_real_sign_4_pentagonal,
    coeffs_real_sign_4_sym, coeffs_real_sign_fallback,
};
use super::symnum::{GIntT, RatioT, SymNum, ZZComplex, ZZParams};
use super::traits::{
    ComplexTraits, HasZZ10Impl, HasZZ12Impl, HasZZ4Impl, HasZZ6Impl, HasZZ8Impl, IsRing,
    IsRingOrField, IsZZ4Impl, RingTraits, ZZType,
};
use super::units::Units;

use crate::impl_intersect_unit_segments_via_general;
use crate::impl_re_im_sign_via_proj;
use crate::impl_within_radius_via_norm_sq;

// Re-export the manually-implemented ZZ12 so existing
// `use super::super::types::ZZ12;` paths keep resolving.
#[allow(unused_imports)]
pub use super::zz12::ZZ12;

// generate boilerplate implementations

macro_rules! impl_symnum_struct_for {
    ($($n:expr)*) => ($(
        paste! {
            impl_symnum!([<ZZ $n>], [<ZZ $n _PARAMS>], [<zz $n _mul>]);
        }
    )*)
}
macro_rules! zz_from_int_pair {
    ($t:ty) => {
        impl From<(<$t as InnerIntType>::IntType, <$t as InnerIntType>::IntType)> for $t {
            fn from(
                (re, im): (
                    <Self as InnerIntType>::IntType,
                    <Self as InnerIntType>::IntType,
                ),
            ) -> Self {
                Self::one().scale(re) + Self::one_i().scale(im)
            }
        }
    };
}
macro_rules! impl_from_int_pair {
    ($($n:expr)*) => ($(
        paste! {
            zz_from_int_pair!([<ZZ $n>]);
        }
    )*)
}
// NOTE: ZZ12 is **not** generated by these macros. It lives in
// `src/cyclotomic/zz12.rs` and uses a pure-i64 integral-basis storage
// (`[i64; 4]` over `{1, zeta, zeta^2, zeta^3}`) instead of the symbolic
// `{1, sqrt(3)}` storage used by every other ring.
impl_symnum_struct_for!(4 8 10 16 20 24 32 60);

// cached unit lookup per concrete complex type
super::units::impl_units_for!(ZZ4);
super::units::impl_units_for!(ZZ8);
super::units::impl_units_for!(ZZ10);
super::units::impl_units_for!(ZZ16);
super::units::impl_units_for!(ZZ20);
super::units::impl_units_for!(ZZ24);
super::units::impl_units_for!(ZZ32);
super::units::impl_units_for!(ZZ60);

impl_functional_traits!(ZZ4);
impl_functional_traits!(ZZ8);
impl_functional_traits!(ZZ10);
impl_functional_traits!(ZZ16);
impl_functional_traits!(ZZ20);
impl_functional_traits!(ZZ24);
impl_functional_traits!(ZZ32);
impl_functional_traits!(ZZ60);

zz_triv_impl!(HasZZ4Impl, ZZ4 ZZ8 ZZ16 ZZ20 ZZ24 ZZ32 ZZ60);
zz_triv_impl!(IsZZ4Impl, ZZ4);
impl_from_int_pair!(4 8 16 20 24 32 60);

// NOTE: ZZ6 and ZZ30 standalone types were removed -- they don't contain
// ZZ4 (no `i`), so the unit-square-grid machinery doesn't apply uniformly.
// The `HasZZ6Impl` trait stays: ZZ6 still exists as a *subring* of ZZ12,
// ZZ24, ZZ60, which is what `T: HasZZ6` captures.
zz_triv_impl!(HasZZ6Impl, ZZ24 ZZ60);
zz_triv_impl!(HasZZ8Impl, ZZ8 ZZ16 ZZ24 ZZ32);
zz_triv_impl!(HasZZ10Impl, ZZ10 ZZ20 ZZ60);
zz_triv_impl!(HasZZ12Impl, ZZ24 ZZ60);

// Generate the coefficient-projection ReImSign for every complex ring
// **except** ZZ12. ZZ12 provides its own pure-i64 override in `zz12.rs`.
//
// Each ring's `coeffs_real_sign_*` function operates directly on the
// `Ratio<i64>` real (or imaginary) halves of the GaussInt-backed
// coefficient array and the matching `sym_roots_sqs` parameters.
impl_re_im_sign_via_proj!(ZZ4, coeffs_real_sign_1_sym);
impl_re_im_sign_via_proj!(ZZ8, coeffs_real_sign_2_sym);
impl_re_im_sign_via_proj!(ZZ10, coeffs_real_sign_4_pentagonal);
impl_re_im_sign_via_proj!(ZZ16, coeffs_real_sign_4_sym);
impl_re_im_sign_via_proj!(ZZ20, coeffs_real_sign_4_pentagonal);
impl_re_im_sign_via_proj!(ZZ24, coeffs_real_sign_4_sym);
impl_re_im_sign_via_proj!(ZZ32, coeffs_real_sign_fallback);
impl_re_im_sign_via_proj!(ZZ60, coeffs_real_sign_fallback);

// Generate the norm_sq-based WithinRadius for every complex ring **except**
// ZZ12. ZZ12 provides its own pure-i64 override in `zz12.rs`.
impl_within_radius_via_norm_sq!(ZZ4);
impl_within_radius_via_norm_sq!(ZZ8);
impl_within_radius_via_norm_sq!(ZZ10);
impl_within_radius_via_norm_sq!(ZZ16);
impl_within_radius_via_norm_sq!(ZZ20);
impl_within_radius_via_norm_sq!(ZZ24);
impl_within_radius_via_norm_sq!(ZZ32);
impl_within_radius_via_norm_sq!(ZZ60);

// Generate the generic-`intersect`-based `IntersectUnitSegments` for every
// complex ring **except** ZZ12. ZZ12 provides its own 3-multiplication
// pure-i64 override in `zz12.rs`.
impl_intersect_unit_segments_via_general!(ZZ4);
impl_intersect_unit_segments_via_general!(ZZ8);
impl_intersect_unit_segments_via_general!(ZZ10);
impl_intersect_unit_segments_via_general!(ZZ16);
impl_intersect_unit_segments_via_general!(ZZ20);
impl_intersect_unit_segments_via_general!(ZZ24);
impl_intersect_unit_segments_via_general!(ZZ32);
impl_intersect_unit_segments_via_general!(ZZ60);

#[cfg(test)]
mod tests {
    use super::*;

    use super::super::constants::zz_units_sum;
    use super::super::symnum::{GIntT, SymNum};
    use super::super::units::Units;

    macro_rules! zz_tests {
        ($mod: ident, $type: ident, $($n:expr)*) => ($(
            paste! { zz_test!([<$mod $n>], [<$type $n>]); }
        )*)
    }

    #[test]
    fn test_display() {
        let x = ZZ24::zero();
        assert_eq!(format!("{x}"), "0");

        let x = ZZ24::one();
        assert_eq!(format!("{x}"), "1");

        let x = ZZ24::one() + ZZ24::one();
        assert_eq!(format!("{x}"), "2");

        let x = -ZZ24::one();
        assert_eq!(format!("{x}"), "-1");

        let x = ZZ24::one() + (ZZ24::ccw()).pow(2i8);
        assert_eq!(format!("{x}"), "1+1/2i + (1/2)*sqrt(3)");

        let x: ZZ10 = zz_units_sum();
        assert_eq!(
            format!("{x}"),
            "-5 + (-15/4i)*sqrt(2(5-sqrt(5))) + (-5/4i)*sqrt(10(5-sqrt(5)))"
        );
    }

    // NOTE: ZZ12 is excluded -- it has a non-symbolic storage layout, so the
    // generic SymNum-coefficient tests (e.g. `test_scaling_fac`) don't apply.
    // Its specific tests live in `zz12.rs`.
    zz_tests!(zz, ZZ, 4 8 10 16 20 24 32 60);
}
