import init, { analyze, db_init, db_id_of, db_seq_of } from './pkg/tilezz.js';
await init();

const ringEl = document.getElementById('ring');
const anglesEl = document.getElementById('angles');
const outEl = document.getElementById('out');
const idEl = document.getElementById('rat-id');
const dbControlEl = document.getElementById('db-control');
const clearBtn = document.getElementById('clear-btn');
const diceBtn = document.getElementById('dice-btn');
const idDecBtn = document.getElementById('id-dec-btn');
const idIncBtn = document.getElementById('id-inc-btn');

let previewAngle = null; // null = no preview; integer = active preview

// Latest AnalysisResult produced by run(). Read by the keyboard
// handler (for commit/refuse logic) and by augmentInfoWithDbId (to
// look up the committed rat in the DB). Replaces the previous
// dataset.* round-trip on the wrapper div.
let lastResult = null;

// Placeholder SVG for the "no committed snake, parse error, etc."
// case where JS builds an AnalysisResult locally and doesn't call
// into Rust. Matches the shape Rust returns for the equivalent
// case so applyResult sees a uniform input.
const PLACEHOLDER_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-1 -1 2 2" '
  + 'width="400" height="400"></svg>';

// Per-ring RatDB state. `availableDatasets` is populated once on
// startup by parsing the top-level RO-Crate (./ro-crate-metadata.json):
// ring -> { dir, maxPerimeter, free, nSequences, maxIndexedLength }.
// `dbMeta` is populated by `tryLoadDb` as the user selects a ring:
// `null` = load attempted and failed; absent = not yet attempted;
// `{ total, max_len }` = ready.
const availableDatasets = new Map();
const dbMeta = new Map();         // ring -> { total, max_len }
const dbLoadAttempts = new Map(); // ring -> Promise resolving when init done/failed

// Parse the page-level RO-Crate's `@graph` into a ring -> dataset
// descriptor map. The collection crate is generated by
// `build_web_rocrate` at deploy time; each per-dataset stub carries
// its parameters in `additionalProperty` so the explorer can drive
// off a single fetch without string-parsing identifiers.
async function loadAvailableDatasets() {
  let crate;
  try {
    const r = await fetch('./ro-crate-metadata.json');
    if (!r.ok) return;
    crate = await r.json();
  } catch (err) {
    console.warn('top-level RO-Crate not available:', err);
    return;
  }
  for (const entity of crate['@graph'] || []) {
    if (entity['@type'] !== 'Dataset') continue;
    const id = entity['@id'];
    if (typeof id !== 'string' || !id.startsWith('./data/')) continue;
    const props = {};
    for (const p of entity.additionalProperty || []) {
      props[p.name] = p.value;
    }
    const ring = props.ring;
    if (!Number.isFinite(ring)) continue;
    const ds = {
      dir: id.replace(/\/$/, ''),
      maxPerimeter: props.maxPerimeter,
      free: props.canonicalization === 'free',
      nSequences: props.nSequences,
      maxIndexedLength: props.maxIndexedLength,
    };
    // If multiple datasets exist for the same ring, prefer the
    // deepest enumeration. (Future-proofing for shipping multiple
    // perim bounds per ring.)
    const existing = availableDatasets.get(ring);
    if (!existing || (existing.maxPerimeter ?? -1) < (ds.maxPerimeter ?? -1)) {
      availableDatasets.set(ring, ds);
    }
  }
}

// ZZn angle alphabet: turn by k * (2*pi / n) for integer k with
// |k| < n/2. The endpoints +/- n/2 are excluded (a 180-degree turn
// would fold the polygon back on itself).
function currentRange() {
  const n = parseInt(ringEl.value, 10);
  if (!Number.isFinite(n) || n < 4 || n % 2 !== 0) return [0, 0];
  const hturn = n / 2;
  return [-(hturn - 1), hturn - 1];
}

// Apply a fresh `analyze(...)` result by updating in place rather
// than blowing away outEl.innerHTML. Replacing the wrapper would
// detach the touch target mid-gesture and fire a touchcancel,
// after which the browser stops delivering touchmove events for
// that touch -- breaking continuous swipe scrubbing.
//
// `result` is the structured object returned by Rust's `analyze`:
//   { error, svg, state: { length, angle_sum, closed, angles, rat },
//     preview, self_intersect_at }
function applyResult(result) {
  lastResult = result;
  let live = outEl.querySelector('.rat-explorer-result');
  if (!live) {
    // First call: install the empty skeleton (outer wrapper +
    // .rat-explorer-svg + .rat-explorer-info) so subsequent
    // updates only touch the inner content.
    outEl.innerHTML =
      '<div class="rat-explorer-result">' +
        '<div class="rat-explorer-svg"></div>' +
        '<div class="rat-explorer-info"></div>' +
      '</div>';
    live = outEl.querySelector('.rat-explorer-result');
  }

  const svgWrap = live.querySelector('.rat-explorer-svg');
  if (svgWrap.innerHTML !== result.svg) svgWrap.innerHTML = result.svg;

  const infoWrap = live.querySelector('.rat-explorer-info');
  const infoHtml = renderInfo(result);
  if (infoWrap.innerHTML !== infoHtml) infoWrap.innerHTML = infoHtml;
}

// Build the info-panel HTML from the structured analysis result.
// All labels, ordering, and DOM shape live here -- no rebuild
// needed to tweak any of it.
function renderInfo(result) {
  if (result.error) {
    return '<dl><dt>error</dt><dd class="rat-explorer-error">'
      + esc(result.error) + '</dd></dl>';
  }
  const s = result.state;
  if (s.length === 0 && !result.preview && result.self_intersect_at == null) {
    return '<dl><dt>state</dt><dd>type angles to begin</dd></dl>';
  }

  let html = '<dl>';
  html += row('length', s.length);
  html += row('angle sum', s.angle_sum);

  if (s.closed && s.rat) {
    const r = s.rat;
    html += row('state', '<strong>closed (rat)</strong>');
    const chirLabel = r.chirality > 0 ? '+1 (CCW)'
      : (r.chirality < 0 ? '-1 (CW)' : '0');
    html += row('sequence chirality', chirLabel);
    const rotation = r.rotational_order > 1
      ? `${r.rotational_order}-fold` : 'none';
    html += row('rotational symmetry', rotation);

    // Reflection-symmetry value: "achiral" is plain text;
    // "chiral" is a click-to-flip link that reverses the committed
    // sequence (= the mirror polygon described in the same
    // chirality).
    let reflection;
    if (r.achiral) {
      reflection = 'achiral';
    } else {
      const reversed = [...s.angles].reverse();
      reflection = `<span class="loadable" data-load-angles="${formatSeq(reversed)}" `
        + `title="click to flip to the mirror polygon">chiral</span>`;
    }
    html += row('reflection symmetry', reflection);

    const chiralStr = formatSeq(r.canonical_chiral);
    const achiralStr = formatSeq(r.canonical_achiral);
    html += row('canonical chiral sequence',
      `<span class="loadable" data-load-angles="${chiralStr}" `
      + `title="click to load this sequence">${chiralStr}</span>`);
    html += row('canonical achiral sequence',
      `<span class="loadable" data-load-angles="${achiralStr}" `
      + `title="click to load this sequence">${achiralStr}</span>`);
  } else if (s.length === 0) {
    html += row('state', 'empty');
  } else {
    html += row('state', 'open');
  }
  html += '</dl>';

  // Self-intersect warning. Phrased differently when the very
  // first angle was rejected (no accepted prefix to show).
  if (result.self_intersect_at != null) {
    const idx = result.self_intersect_at;
    const note = s.length === 0
      ? `first angle was already rejected (step ${idx})`
      : `self-intersected at step ${idx}; showing accepted prefix`;
    html += '<dl class="info-notes">' + row('warning', note) + '</dl>';
  }

  return html;
}

function row(key, value) {
  return `<dt>${esc(String(key))}</dt><dd>${value}</dd>`;
}

// Both regular Arrays (from serde-wasm-bindgen) and TypedArrays
// (from direct wasm-bindgen Vec<i8> returns) have `.join`, so we
// accept either.
function formatSeq(arr) {
  if (!arr || typeof arr.join !== 'function') return '';
  return arr.join(' ');
}

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Parse the angle input box into a `Vec<i8>`-compatible `Int8Array`
// before handing it to Rust. Tolerates a trailing bare "-" or "+"
// so live updates don't flash a parse error while the user is
// mid-typing a negative angle.
//
// Returns `{ angles: Int8Array, error: null }` on success and
// `{ angles: null, error: "..." }` on parse failure.
function parseAnglesText(text) {
  const tokens = text.trim().split(/\s+/).filter(t => t.length > 0);
  if (tokens.length > 0) {
    const last = tokens[tokens.length - 1];
    if (last === '-' || last === '+') tokens.pop();
  }
  const out = new Int8Array(tokens.length);
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i];
    if (!/^[+-]?\d+$/.test(t)) {
      return { angles: null, error: `can't parse \`${t}\` as an integer angle` };
    }
    const n = parseInt(t, 10);
    if (n < -128 || n > 127) {
      return { angles: null, error: `angle \`${t}\` out of i8 range` };
    }
    out[i] = n;
  }
  return { angles: out, error: null };
}

// Local fallback AnalysisResult for the cases where JS doesn't
// call into Rust (parse errors). Mirrors the shape Rust returns
// so applyResult / renderInfo can stay single-path.
function errorResult(message) {
  return {
    error: message,
    svg: PLACEHOLDER_SVG,
    state: { length: 0, angle_sum: 0, closed: false, angles: [], rat: null },
    preview: null,
    self_intersect_at: null,
  };
}

function run() {
  const ring = parseInt(ringEl.value, 10);
  const parsed = parseAnglesText(anglesEl.value);
  const result = parsed.error
    ? errorResult(parsed.error)
    : analyze(ring, parsed.angles, previewAngle);
  applyResult(result);
  syncUrl();
  // RatDB row in the info panel: appended async after the SVG
  // renders. The token stops a stale lookup (e.g. user typed
  // faster than the DB walked) from overwriting a newer one.
  runId += 1;
  augmentInfoWithDbId(runId, ring, result);
}
let runId = 0;

// Look up the RatDB ID of the committed rat (if any) and inject
// a row into the info panel. Bails out fast when no DB is loaded
// for the ring, the snake isn't closed, or the length exceeds the
// DB's max_indexed_length. `myRunId` guards against out-of-order
// resolution if multiple lookups overlap.
async function augmentInfoWithDbId(myRunId, ring, result) {
  const meta = dbMeta.get(ring);
  if (!meta) return;
  // Open snake (or self-intersect) -> not in the DB; clear the
  // ID input so it doesn't pretend to still refer to the previous
  // rat. (We only touch the input when the user isn't currently
  // typing into it, to avoid clobbering mid-edit.)
  if (!result.state.closed) {
    setIdInput('');
    return;
  }
  const committed = result.state.angles;
  const tokenCount = committed.length;

  // The DAFSA only indexes rats up to max_len. Longer closures and
  // genuine "not in DB" misses surface as a hoverable "n/a" with a
  // dotted underline -- matches the affordance on the RatDB ID
  // label itself. Hits get rendered as a clickable .loadable
  // carrying the free-canonical sequence the DB returns, so
  // clicking the ID loads the rat's normalised form into the
  // input.
  let valueHtml;
  let resolvedId = null;
  if (tokenCount > meta.max_len) {
    const tip = `polygon perimeter ${tokenCount} exceeds DB maximum ${meta.max_len}`;
    valueHtml = `<span class="db-na" data-tooltip="${tip}">n/a</span>`;
  } else {
    const id = await db_id_of(ring, new Int8Array(committed));
    if (myRunId !== runId) return; // stale; a newer run replaced us
    if (id === undefined || id === null) {
      // Within-envelope miss: the polygon's perimeter is <= the
      // DB's max indexed length, yet the lookup didn't resolve to
      // any ID. That's either an enumeration gap (DFS missed a
      // valid closed simple polygon) or a canonicalization
      // mismatch between the web's `closing_free_canonical`
      // and the DFS's pipeline -- in both cases a bug the
      // maintainer needs to see. Render as a clickable red link
      // that opens a prefilled GitHub issue with the angle
      // sequence + reproduction URL.
      const seqStr = committed.join(',');
      const issueTitle = `Possible RatDB miss: ZZ${ring} [${seqStr}]`;
      const issueBody =
        `The web app's RatDB lookup returned "not in DB" for a polygon ` +
        `that's within the indexed envelope, which most likely indicates ` +
        `an enumeration gap or canonicalization mismatch.\n` +
        `\n` +
        `**Ring:** ZZ${ring}\n` +
        `**Perimeter:** ${tokenCount} (DB max = ${meta.max_len})\n` +
        `**Committed angle sequence:** ${seqStr}\n` +
        `**Reproduce:** ${window.location.href}\n` +
        `\n` +
        `Either the DFS missed this closed simple polygon during ` +
        `enumeration, or the lookup-side free-canonicalization ` +
        `disagrees with the DFS-side one. A screenshot of the ` +
        `rendered polygon would help triage.\n`;
      const issueUrl = 'https://github.com/apirogov/tilezz/issues/new?'
        + 'title=' + encodeURIComponent(issueTitle)
        + '&body=' + encodeURIComponent(issueBody);
      const tip = `polygon within DB envelope (perimeter ${tokenCount} <= ${meta.max_len}) `
        + `but not found -- you most likely hit a bug. Click to file an issue.`;
      valueHtml = `<a class="db-bug" href="${issueUrl}" target="_blank" rel="noopener" `
        + `data-tooltip="${tip}">missing (report)</a>`;
    } else {
      resolvedId = id;
      // Fetch the canonical so the ID can be a self-loading link.
      // Both calls hit the same DAFSA so the second one is mostly
      // cache-warm.
      const canonical = await db_seq_of(ring, id);
      if (myRunId !== runId) return;
      if (canonical && canonical.length > 0) {
        const canonicalStr = formatSeq(canonical);
        valueHtml = `<span class="loadable" data-load-angles="${canonicalStr}" `
          + `title="click to load the free-canonical (= dihedral-reduced) form">${id}</span>`;
      } else {
        valueHtml = String(id);
      }
    }
  }
  // Keep the ID input in sync with the resolved ID (or clear it
  // for misses) so a stale value from a previous lookup can't sit
  // around looking authoritative.
  setIdInput(resolvedId === null ? '' : String(resolvedId));
  // Insert the row before the optional info-notes block, or at the
  // end of the info dl if there's no notes block.
  const live = outEl.querySelector('.rat-explorer-result');
  if (!live) return;
  const info = live.querySelector('.rat-explorer-info');
  if (!info) return;
  // Append a new dl if one doesn't already exist for the DB row.
  let dbDl = info.querySelector('.db-row');
  if (!dbDl) {
    dbDl = document.createElement('dl');
    dbDl.className = 'db-row';
    // Insert right after the first dl (stats), before any h3 or info-notes.
    const firstDl = info.querySelector('dl');
    if (firstDl && firstDl.parentNode === info) {
      firstDl.after(dbDl);
    } else {
      info.appendChild(dbDl);
    }
  }
  dbDl.innerHTML = `<dt>RatDB ID</dt><dd>${valueHtml}</dd>`;
}

// Attempt to load the RatDB asset for `ring`. Caches the promise
// so simultaneous renders don't double-fetch. Sets the UI state
// (input enabled/disabled, metadata strip) when done.
function tryLoadDb(ring) {
  if (dbLoadAttempts.has(ring)) return dbLoadAttempts.get(ring);
  const ds = availableDatasets.get(ring);
  if (!ds) {
    dbLoadAttempts.set(ring, Promise.resolve(null));
    return dbLoadAttempts.get(ring);
  }
  const assetDir = ds.dir;
  const promise = (async () => {
    try {
      const meta = await db_init(ring, assetDir);
      // meta is a plain object from JS side: { total, max_len }
      dbMeta.set(ring, { total: meta.total, max_len: meta.max_len });
      return meta;
    } catch (err) {
      console.warn(`RatDB ring=${ring} not loaded:`, err);
      dbMeta.set(ring, null); // explicit miss
      return null;
    } finally {
      updateDbUi(parseInt(ringEl.value, 10));
    }
  })();
  dbLoadAttempts.set(ring, promise);
  return promise;
}

// Mirror the resolved ID (or "") into the RatDB ID input, but
// don't clobber the user mid-edit: if they have the input focused,
// they're typing -- leave it alone until they blur or submit.
function setIdInput(value) {
  if (document.activeElement === idEl) return;
  if (idEl.value !== value) idEl.value = value;
}

function updateDbUi(ring) {
  const meta = dbMeta.get(ring);
  if (!meta) {
    dbControlEl.classList.add('disabled');
    idEl.disabled = true;
    idEl.value = '';
    const inFlight = dbLoadAttempts.get(ring);
    if (inFlight && !dbMeta.has(ring)) {
      dbControlEl.dataset.tooltip = 'loading RatDB ...';
    } else if (availableDatasets.has(ring)) {
      dbControlEl.dataset.tooltip = 'failed to load RatDB';
    } else {
      dbControlEl.dataset.tooltip = 'no RatDB shipped for this ring';
    }
    diceBtn.disabled = true;
    idDecBtn.disabled = true;
    idIncBtn.disabled = true;
  } else {
    dbControlEl.classList.remove('disabled');
    idEl.disabled = false;
    diceBtn.disabled = false;
    idDecBtn.disabled = false;
    idIncBtn.disabled = false;
    idEl.max = String(meta.total - 1);
    dbControlEl.dataset.tooltip =
      `RatDB: ${meta.total.toLocaleString()} rats, max length n = ${meta.max_len}`;
  }
}

// Submit an ID -> load its canonical sequence via db_seq_of.
idEl.addEventListener('change', async () => {
  const ring = parseInt(ringEl.value, 10);
  const raw = idEl.value.trim();
  if (raw === '') return;
  const id = parseInt(raw, 10);
  if (!Number.isFinite(id) || id < 0) return;
  const seq = await db_seq_of(ring, id);
  if (seq && seq.length > 0) {
    anglesEl.value = formatSeq(seq);
    previewAngle = null;
    run();
  } else {
    // Briefly mark the input as invalid; native tooltip still
    // carries the metadata so the user can see the valid range.
    idEl.classList.add('db-id-invalid');
    setTimeout(() => idEl.classList.remove('db-id-invalid'), 1200);
  }
});

// -/+ stepper buttons. The native number-input spinners are hidden
// via CSS (desktop browsers show them, mobile ones don't), so these
// are the one stepper UI on all devices. Clamp to [0, total) and
// funnel through the same change handler as manual edits.
function stepId(delta) {
  const ring = parseInt(ringEl.value, 10);
  const meta = dbMeta.get(ring);
  if (!meta || meta.total === 0) return;
  const raw = idEl.value.trim();
  // From an empty box both buttons land on a valid endpoint: + on
  // the first ID, - on the last.
  let id;
  if (raw === '') {
    id = delta > 0 ? 0 : meta.total - 1;
  } else {
    id = parseInt(raw, 10) + delta;
    if (!Number.isFinite(id)) id = 0;
    id = Math.min(Math.max(id, 0), meta.total - 1);
  }
  idEl.value = String(id);
  idEl.dispatchEvent(new Event('change'));
}

idDecBtn.addEventListener('click', () => stepId(-1));
idIncBtn.addEventListener('click', () => stepId(1));

// Keep the URL in sync with the (ring, sequence) pair so any
// committed state is shareable / bookmarkable.
// Scheme: `?ring=<n>&seq=a,b,c,...` (comma-separated, no spaces
// in the URL). Defaults: ring=12, seq empty.
function syncUrl() {
  const params = new URLSearchParams();
  params.set('ring', ringEl.value);
  const seq = anglesEl.value.trim();
  if (seq.length > 0) {
    params.set('seq', seq.split(/\s+/).join(','));
  }
  const newSearch = '?' + params.toString();
  // Avoid a needless history entry when nothing actually changed
  // (preview scrubbing calls run() many times per gesture but
  // doesn't move the committed angles).
  if (newSearch !== window.location.search) {
    window.history.replaceState(null, '', window.location.pathname + newSearch);
  }
}

// Pull initial state from the URL (ring + comma-separated seq)
// BEFORE the first run() so it's reflected in the rendered SVG
// immediately. Invalid ring values are ignored; the seq is
// converted from comma-separated (URL form) to space-separated
// (input-box form) and passed straight to the engine -- any
// unparseable tokens surface as the usual parse-error fragment.
// Pull initial state from the URL. `?seq=...` wins over `?id=...`
// (so a shared link with both falls back to the explicit angle
// sequence). The `?id=` path needs the DB to be loaded for the
// chosen ring before it can resolve, so we await that here.
const initialParams = new URLSearchParams(window.location.search);
if (initialParams.has('ring')) {
  const r = initialParams.get('ring');
  if (ringEl.querySelector(`option[value="${CSS.escape(r)}"]`)) ringEl.value = r;
}
if (initialParams.has('seq')) {
  anglesEl.value = initialParams.get('seq').replace(/,/g, ' ').trim();
}
// Discover which datasets are shipped (top-level RO-Crate), then
// kick off the DB load for the current ring. The "loading ..." tip
// in the meta strip stays visible while the asset fetch is in flight.
await loadAvailableDatasets();
const initialRing = parseInt(ringEl.value, 10);
updateDbUi(initialRing);
await tryLoadDb(initialRing);
if (
  initialParams.has('id') &&
  !initialParams.has('seq') &&
  dbMeta.get(initialRing)
) {
  const id = parseInt(initialParams.get('id'), 10);
  if (Number.isFinite(id) && id >= 0) {
    const seq = await db_seq_of(initialRing, id);
    if (seq && seq.length > 0) anglesEl.value = formatSeq(seq);
  }
}

// Copy text to the clipboard with a graceful fallback for browser
// contexts where `navigator.clipboard` is unavailable (file://,
// plain http on a LAN IP, very old browsers).
function copyText(text) {
  if (navigator.clipboard?.writeText) {
    return navigator.clipboard.writeText(text);
  }
  return new Promise((resolve, reject) => {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.setAttribute('readonly', '');
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    try {
      const ok = document.execCommand('copy');
      document.body.removeChild(ta);
      ok ? resolve() : reject(new Error('execCommand copy returned false'));
    } catch (err) {
      document.body.removeChild(ta);
      reject(err);
    }
  });
}

// Share button: writes the current URL (kept in sync by run() ->
// syncUrl()) to the clipboard and briefly flashes the button
// green to confirm. Icon-only on purpose so the controls row
// doesn't wrap on narrow viewports.
const shareBtn = document.getElementById('share-btn');
shareBtn.addEventListener('click', async () => {
  try {
    await copyText(window.location.href);
    shareBtn.classList.add('copied');
    setTimeout(() => shareBtn.classList.remove('copied'), 1500);
  } catch (err) {
    // Clipboard genuinely refused (rare). Surface the URL so the
    // user can copy it manually rather than failing silently.
    window.prompt('Copy this URL:', window.location.href);
  }
});

// Clear button: wipes the angle sequence (and any active preview).
clearBtn.addEventListener('click', () => {
  if (anglesEl.value === '' && previewAngle === null) return;
  anglesEl.value = '';
  previewAngle = null;
  run();
  anglesEl.focus();
});

// Dice button: picks a random RatDB ID in [0, total) and loads
// its canonical sequence via the same path as the ID input.
diceBtn.addEventListener('click', async () => {
  const ring = parseInt(ringEl.value, 10);
  const meta = dbMeta.get(ring);
  if (!meta || meta.total === 0) return;
  const id = Math.floor(Math.random() * meta.total);
  idEl.value = String(id);
  const seq = await db_seq_of(ring, id);
  if (seq && seq.length > 0) {
    anglesEl.value = formatSeq(seq);
    previewAngle = null;
    run();
  }
});

// Manual edits or ring changes drop any active preview.
ringEl.addEventListener('change', async () => {
  previewAngle = null;
  const ring = parseInt(ringEl.value, 10);
  updateDbUi(ring);
  await tryLoadDb(ring);
  run();
});
anglesEl.addEventListener('input', () => { previewAngle = null; run(); });

// Loadable elements -- both the button-style example links in
// the hint and the inline `.loadable` spans in the info panel
// (canonical sequences, the "chiral" label, ...) -- carry their
// payload in `data-load-angles` (and optional `data-load-ring`).
// A single delegated handler reads those and loads.
//
// For inline text spans we also want copy-by-selection to keep
// working, so if the user has an active text selection at click
// time (i.e. they just finished dragging to select something),
// we treat the click as the end of the drag and skip the load.
// Buttons never get this check, since the user wouldn't be
// selecting them.
document.addEventListener('click', (e) => {
  const link = e.target.closest('[data-load-angles]');
  if (!link) return;
  const isButton = link.matches('button');
  if (!isButton && window.getSelection().toString().length > 0) return;
  if (link.dataset.loadRing) ringEl.value = link.dataset.loadRing;
  anglesEl.value = link.dataset.loadAngles;
  previewAngle = null;
  run();
  anglesEl.focus();
});

// Document-level keyboard: arrows always drive the preview, even
// when the angle input has focus. We sacrifice cursor navigation
// inside the input (use mouse + typing to edit mid-sequence).
document.addEventListener('keydown', (e) => {
  // Inputs / selects own the arrow keys for their own UX (cursor
  // navigation in text inputs, value step in number inputs, option
  // cycle in selects). Skip the rat-explorer handler so we don't
  // hijack those. Escape is the dedicated "blur and hand control
  // back to me" shortcut.
  const a = document.activeElement;
  const inEditable = a && (
    a.tagName === 'INPUT' || a.tagName === 'TEXTAREA' || a.tagName === 'SELECT'
  );
  if (inEditable) {
    if (e.key === 'Escape') {
      a.blur();
      e.preventDefault();
    }
    return;
  }

  const [lo, hi] = currentRange();

  switch (e.key) {
    case 'ArrowLeft':
      // CCW = positive angle in tilezz convention; first Left
      // press jumps straight to +1 (a single CCW step), so the
      // preview reflects the keypress direction instead of going
      // through 0 first.
      previewAngle = previewAngle === null ? 1
        : (previewAngle >= hi ? lo : previewAngle + 1);
      e.preventDefault();
      run();
      break;
    case 'ArrowRight':
      previewAngle = previewAngle === null ? -1
        : (previewAngle <= lo ? hi : previewAngle - 1);
      e.preventDefault();
      run();
      break;
    case 'ArrowUp': {
      // Closed rats can't be extended -- snake.add rejects it at
      // the type level. Pop the closing edge with Down first.
      if (lastResult?.state.closed) {
        e.preventDefault();
        break;
      }
      // Up always tries to add an edge: with no active preview,
      // treat the press as "extend with angle 0 (straight)" rather
      // than a no-op. We do an extra `run()` so lastResult reflects
      // the angle-0 attempt before we read it for the rejection
      // check below.
      if (previewAngle === null) {
        previewAngle = 0;
        run();
      }
      // Refuse to commit a preview the engine rejected (would
      // self-intersect). The rendered overlay still shows the
      // candidate edge in orange so the user sees what they tried.
      if (lastResult?.preview && !lastResult.preview.accepted) {
        e.preventDefault();
        break;
      }
      // Commit the preview angle into the input, then immediately
      // arm the next preview at 0 -- unless the commit just closed
      // the snake into a rat (in which case clear the preview so
      // the closed shape stands alone until the user pops the
      // closing edge with Down). Rust suppresses the preview
      // overlay on closed snakes, so the single render below is
      // already correct; we only need to update the JS state.
      const t = anglesEl.value.trimEnd();
      anglesEl.value = (t.length === 0 ? '' : t + ' ') + previewAngle;
      previewAngle = 0;
      e.preventDefault();
      run();
      if (lastResult?.state.closed) {
        previewAngle = null;
        // Snake rewrites the first angle when the boundary closes,
        // so the committed angle sequence may differ from what the
        // user typed. Resync the input from the canonical sequence
        // the engine emits.
        anglesEl.value = formatSeq(lastResult.state.angles);
      }
      break;
    }
    case 'ArrowDown': {
      const tokens = anglesEl.value.trim().split(/\s+/).filter(Boolean);
      if (tokens.length > 0) {
        tokens.pop();
        anglesEl.value = tokens.join(' ');
        previewAngle = null;
        e.preventDefault();
        run();
      }
      break;
    }
    case 'Escape':
      if (previewAngle !== null) {
        previewAngle = null;
        e.preventDefault();
        run();
      }
      break;
  }
});

// Mobile gestures on the SVG area:
//
// - Horizontal drag is continuous: each ANGLE_STEP_PX of movement
//   shifts the preview angle by 1, so one slow drag spans many
//   angles instead of requiring one swipe per step. Left = CCW
//   (positive angle), right = CW, matching the keyboard arrows.
// - Vertical drag is discrete: a single up/down swipe past
//   COMMIT_THRESHOLD_PX dispatches Up/Down (commit / pop), same
//   handler as the keyboard.
//
// Once the gesture commits to an axis we call `e.preventDefault()`
// on `touchmove` (with `passive: false`) to keep the page from
// scrolling out from under the user; the SVG also has
// `touch-action: none` in CSS as a belt-and-braces backup.
const AXIS_THRESHOLD_PX = 12;
const ANGLE_STEP_PX = 25;
const COMMIT_THRESHOLD_PX = 40;

let touchState = null;

// Touch listeners go on `document` rather than `outEl` because
// `run()` replaces outEl's innerHTML on every preview update, which
// detaches the original touchstart target. Subsequent touchmove
// events then fire on a node that has no ancestor in the live DOM,
// so they never bubble to outEl. The document is always in the
// propagation path regardless of where the touch started.
// touchstart MUST be passive:false and call preventDefault() so
// the browser doesn't commit the gesture to "page scroll" before
// we've moved enough pixels to decide what kind of swipe it is.
// On iOS Safari especially, once it interprets the initial moves
// as scrolling, it stops delivering touchmove events to JS and
// the gesture goes dark after one step.
document.addEventListener('touchstart', (e) => {
  if (e.touches.length !== 1) return;
  if (!e.target.closest || !e.target.closest('.rat-explorer-svg')) return;
  e.preventDefault();
  const t = e.touches[0];
  touchState = {
    startX: t.clientX,
    startY: t.clientY,
    startAngle: previewAngle,
    axis: null,
  };
}, { passive: false });

document.addEventListener('touchmove', (e) => {
  if (!touchState) return;
  // Always preventDefault while a gesture is in flight. Skipping
  // it on the sub-threshold moves lets the browser steal the
  // gesture and turn it into a scroll, after which we get no
  // more touchmove events.
  e.preventDefault();

  const t = e.touches[0];
  const dx = t.clientX - touchState.startX;
  const dy = t.clientY - touchState.startY;

  if (touchState.axis === null) {
    const ax = Math.abs(dx);
    const ay = Math.abs(dy);
    if (Math.max(ax, ay) < AXIS_THRESHOLD_PX) return;
    touchState.axis = ax > ay ? 'horizontal' : 'vertical';
  }

  if (touchState.axis === 'horizontal') {
    // Continuous scrub. Left swipe (dx<0) maps to a positive
    // delta (CCW), matching the keyboard convention.
    const delta = Math.round(-dx / ANGLE_STEP_PX);
    const [lo, hi] = currentRange();
    const span = hi - lo + 1;
    const base = touchState.startAngle === null ? 0 : touchState.startAngle;
    let v = base + delta;
    // Wrap into [lo, hi].
    v = ((v - lo) % span + span) % span + lo;
    if (v !== previewAngle) {
      previewAngle = v;
      run();
    }
  }
  // Vertical axis: wait for touchend to decide commit/pop.
}, { passive: false });

document.addEventListener('touchend', (e) => {
  if (!touchState) return;
  const t = e.changedTouches[0];
  const dy = t.clientY - touchState.startY;
  const axis = touchState.axis;
  touchState = null;
  if (axis === 'vertical' && Math.abs(dy) >= COMMIT_THRESHOLD_PX) {
    document.dispatchEvent(new KeyboardEvent('keydown', {
      key: dy > 0 ? 'ArrowDown' : 'ArrowUp',
    }));
  }
}, { passive: true });

// If the browser cancels the gesture (e.g. system-level swipe or
// unrelated multi-touch), drop our state so we don't keep
// scrubbing a phantom gesture.
document.addEventListener('touchcancel', () => {
  touchState = null;
}, { passive: true });

// Long-press tooltips for `[data-tooltip]` elements. The CSS shows
// the tooltip on `:hover` (desktop) and `.tip-visible` (mobile);
// this handler adds the class after ~500 ms of held touch with no
// movement, and clears it on the next touch elsewhere.
let longPressTimer = null;
let longPressTipEl = null;
function clearLongPressTimer() {
  if (longPressTimer) {
    clearTimeout(longPressTimer);
    longPressTimer = null;
  }
}
function hideLongPressTip() {
  if (longPressTipEl) {
    longPressTipEl.classList.remove('tip-visible');
    longPressTipEl = null;
  }
}
document.addEventListener('touchstart', (e) => {
  const target = e.target.closest && e.target.closest('[data-tooltip]');
  if (longPressTipEl && longPressTipEl !== target) hideLongPressTip();
  if (!target) return;
  clearLongPressTimer();
  longPressTimer = setTimeout(() => {
    if (longPressTipEl && longPressTipEl !== target) {
      longPressTipEl.classList.remove('tip-visible');
    }
    longPressTipEl = target;
    target.classList.add('tip-visible');
    longPressTimer = null;
  }, 500);
}, { passive: true });
['touchmove', 'touchend', 'touchcancel'].forEach(ev =>
  document.addEventListener(ev, clearLongPressTimer, { passive: true })
);

run();
